#!/bin/bash

if  [ -z ${binpath+x} ]; then
    # The script hasn't run yet, so:

    scriptpath="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    #  Set the path to our binaries --

    export binpath=$(dirname $scriptpath)
    export PATH=$PATH:$scriptpath

    # Find pg_ctl --

    export PATH=$PATH:/usr/lib/postgresql/9.6/bin

    alias pg-stats='psql -X --pset pager=off -c "select datname, application_name, state, waiting, query_start, query from pg_stat_activity;"'
fi
