#!/bin/bash
#  Set up the symbolic links to the files --

set -euo pipefail
scriptname=$(resolvepath "$0")
scriptpath=$(dirname "$scriptname")
scriptname=$(basename "$scriptname")
cd "$scriptpath"


function linkFile() {
    local fileToLink="$1"
    local fileToLinkTo="$2"

    ln -fsv Versions/"$fileToLinkTo"     "$fileToLink"
}


linkFile  BlitzLabs-Server                     BlitzHere-Server.Linux
linkFile  BlitzLabs-Server.config              BlitzLabs-Server.config.1

linkFile  BlitzHere-Server                     BlitzHere-Server.Linux.1.4.2
linkFile  BlitzHere-Server.config              BlitzHere-Server.config.1

linkFile  Signup-Server                        Signup-Server.Linux
linkFile  Signup-Server.config                 Signup-Server.config.1

linkFile  Status-Server                        Status-Server.Linux
linkFile  Status-Server.config                 Status-Server.config.1

