#!/bin/bash
set -euo pipefail
scriptpath="${BASH_SOURCE[0]}"
scriptpath=$(cd "$(dirname "${scriptpath}")" && pwd)
scriptname=$(basename "${BASH_SOURCE[0]}")


echo ">>> Building proto files."
cd "$scriptpath"/Chat

(rm -rf java | true)
mkdir java

(rm -rf obj-c | true)
mkdir obj-c

protoc Chat.proto \
    --go_out=. \
    --java_out=obj-c \
    --objc_out=java \

file=Chat.pb.go
echo ">>> Fixing '$file'."
sed -i'.bak' -e 's,import _ ".",,' "$file"
rm "${file}.bak"
