#!/bin/bash
set -euo pipefail

echo ">>> Building proto files."; \
#go install -v github.com/golang/protobuf/protoc-gen-go;
mkdir -p Build/java
mkdir -p Build/obj-c
mkdir -p Build/golang

cd Source
protoc  google/protobuf/descriptor.proto \
    --java_out=../Build/java

shopt -s extglob
protoc !(objectivec-descriptor).proto \
    --go_out=../Build/golang  \
    --java_out=../Build/java  \
    --objc_out=../Build/obj-c
