#!/bin/bash
set -euo pipefail

if [ -z ${1+x} ]; then
    echo ">>> A database name is expected on the command line." >&2
    exit 1
fi

olddatabase="$1"
if  ! askYN "Load database tables '$olddatabase'?"; then
    exit 1
fi


database=${olddatabase}
databaseuser=${database}

loaded=0
dumppath=~/dump/$olddatabase


for file in $dumppath/*.csv
do

    tablename=$(basename "$file")
    tablename="${tablename%.*}"

    columns="$(head -n1 $dumppath/$tablename.csv)"
    copy="\\copy $tablename ($columns) from '$file' with (format csv, header true)"

    echo ">>> Loading $tablename..." 1>&2
    # echo ">>> Copy statement: $copy" 1>&2
    psql $database -U $database -t -X --pset pager=off -c "truncate $tablename;"
    psql $database -U $database -t -X --pset pager=off -c "$copy"
    psql $database -U $database -t -X --pset pager=off -c "select count(*) from $tablename;"
    let "loaded+=1"

done

echo ">>> Loaded $loaded tables." 1>&2
