// Code generated by protoc-gen-go.
// source: Chat.proto
// DO NOT EDIT!

/*
Package Chat is a generated protocol buffer package.

It is generated from these files:
	Chat.proto

It has these top-level messages:
	ChatMessage
	ChatUser
	ChatRoom
	ChatConnect
	ChatEnterRoom
	ChatPresence
	ChatResponse
	ChatMessageType
*/
package Chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StatusCode int32

const (
	StatusCode_StatusSuccess       StatusCode = 1
	StatusCode_StatusInputInvalid  StatusCode = 2
	StatusCode_StatusNotAuthorized StatusCode = 3
	StatusCode_StatusServerError   StatusCode = 4
)

var StatusCode_name = map[int32]string{
	1: "StatusSuccess",
	2: "StatusInputInvalid",
	3: "StatusNotAuthorized",
	4: "StatusServerError",
}
var StatusCode_value = map[string]int32{
	"StatusSuccess":       1,
	"StatusInputInvalid":  2,
	"StatusNotAuthorized": 3,
	"StatusServerError":   4,
}

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}
func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (x *StatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusCode_value, data, "StatusCode")
	if err != nil {
		return err
	}
	*x = StatusCode(value)
	return nil
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChatMessage struct {
	SenderID         *string  `protobuf:"bytes,1,opt,name=senderID" json:"senderID,omitempty"`
	RoomID           *string  `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	Timestamp        *float64 `protobuf:"fixed64,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string  `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetSenderID() string {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return ""
}

func (m *ChatMessage) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ChatUser struct {
	UserID           *string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatUser) Reset()                    { *m = ChatUser{} }
func (m *ChatUser) String() string            { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()               {}
func (*ChatUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatUser) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *ChatUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type ChatRoom struct {
	RoomID           *string `protobuf:"bytes,1,opt,name=roomID" json:"roomID,omitempty"`
	RoomName         *string `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatRoom) Reset()                    { *m = ChatRoom{} }
func (m *ChatRoom) String() string            { return proto.CompactTextString(m) }
func (*ChatRoom) ProtoMessage()               {}
func (*ChatRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatRoom) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatRoom) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

type ChatConnect struct {
	IsConnecting     *bool       `protobuf:"varint,1,opt,name=isConnecting" json:"isConnecting,omitempty"`
	User             *ChatUser   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Rooms            []*ChatRoom `protobuf:"bytes,3,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatConnect) Reset()                    { *m = ChatConnect{} }
func (m *ChatConnect) String() string            { return proto.CompactTextString(m) }
func (*ChatConnect) ProtoMessage()               {}
func (*ChatConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChatConnect) GetIsConnecting() bool {
	if m != nil && m.IsConnecting != nil {
		return *m.IsConnecting
	}
	return false
}

func (m *ChatConnect) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatConnect) GetRooms() []*ChatRoom {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ChatEnterRoom struct {
	User             *ChatUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	RoomID           *string   `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	UserIsEntering   *bool     `protobuf:"varint,3,opt,name=userIsEntering" json:"userIsEntering,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ChatEnterRoom) Reset()                    { *m = ChatEnterRoom{} }
func (m *ChatEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*ChatEnterRoom) ProtoMessage()               {}
func (*ChatEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChatEnterRoom) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatEnterRoom) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatEnterRoom) GetUserIsEntering() bool {
	if m != nil && m.UserIsEntering != nil {
		return *m.UserIsEntering
	}
	return false
}

type ChatPresence struct {
	Room             *ChatRoom   `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
	Users            []*ChatUser `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatPresence) Reset()                    { *m = ChatPresence{} }
func (m *ChatPresence) String() string            { return proto.CompactTextString(m) }
func (*ChatPresence) ProtoMessage()               {}
func (*ChatPresence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChatPresence) GetRoom() *ChatRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *ChatPresence) GetUsers() []*ChatUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChatResponse struct {
	Code             *StatusCode `protobuf:"varint,1,opt,name=code,enum=Chat.StatusCode" json:"code,omitempty"`
	Message          *string     `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatResponse) Reset()                    { *m = ChatResponse{} }
func (m *ChatResponse) String() string            { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()               {}
func (*ChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChatResponse) GetCode() StatusCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return StatusCode_StatusSuccess
}

func (m *ChatResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ChatMessageType struct {
	ChatMessage      *ChatMessage   `protobuf:"bytes,1,opt,name=chatMessage" json:"chatMessage,omitempty"`
	ChatConnect      *ChatConnect   `protobuf:"bytes,2,opt,name=chatConnect" json:"chatConnect,omitempty"`
	ChatEnterRoom    *ChatEnterRoom `protobuf:"bytes,3,opt,name=chatEnterRoom" json:"chatEnterRoom,omitempty"`
	ChatPresence     *ChatPresence  `protobuf:"bytes,4,opt,name=chatPresence" json:"chatPresence,omitempty"`
	ChatResponse     *ChatResponse  `protobuf:"bytes,5,opt,name=chatResponse" json:"chatResponse,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChatMessageType) Reset()                    { *m = ChatMessageType{} }
func (m *ChatMessageType) String() string            { return proto.CompactTextString(m) }
func (*ChatMessageType) ProtoMessage()               {}
func (*ChatMessageType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ChatMessageType) GetChatMessage() *ChatMessage {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

func (m *ChatMessageType) GetChatConnect() *ChatConnect {
	if m != nil {
		return m.ChatConnect
	}
	return nil
}

func (m *ChatMessageType) GetChatEnterRoom() *ChatEnterRoom {
	if m != nil {
		return m.ChatEnterRoom
	}
	return nil
}

func (m *ChatMessageType) GetChatPresence() *ChatPresence {
	if m != nil {
		return m.ChatPresence
	}
	return nil
}

func (m *ChatMessageType) GetChatResponse() *ChatResponse {
	if m != nil {
		return m.ChatResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "Chat.ChatMessage")
	proto.RegisterType((*ChatUser)(nil), "Chat.ChatUser")
	proto.RegisterType((*ChatRoom)(nil), "Chat.ChatRoom")
	proto.RegisterType((*ChatConnect)(nil), "Chat.ChatConnect")
	proto.RegisterType((*ChatEnterRoom)(nil), "Chat.ChatEnterRoom")
	proto.RegisterType((*ChatPresence)(nil), "Chat.ChatPresence")
	proto.RegisterType((*ChatResponse)(nil), "Chat.ChatResponse")
	proto.RegisterType((*ChatMessageType)(nil), "Chat.ChatMessageType")
	proto.RegisterEnum("Chat.StatusCode", StatusCode_name, StatusCode_value)
}

var fileDescriptor0 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0xe2, 0x42, 0x3a, 0x4e, 0x52, 0x67, 0xcb, 0xc1, 0x1c, 0x85, 0x7c, 0x81, 0xaa,
	0x0a, 0x82, 0x94, 0x07, 0x28, 0x82, 0xd0, 0x8b, 0x08, 0xb5, 0x42, 0x0d, 0xbd, 0xc7, 0x5d, 0x8f,
	0x12, 0x43, 0xbd, 0x6b, 0xed, 0xae, 0x23, 0xd1, 0x27, 0xe0, 0xf9, 0xfa, 0x06, 0xbc, 0x09, 0x7b,
	0xb0, 0xe3, 0xa5, 0xe1, 0x6e, 0x67, 0xfd, 0xcf, 0x3f, 0xff, 0x7e, 0x63, 0x80, 0xf9, 0x3a, 0x53,
	0xd3, 0x4a, 0x70, 0xc5, 0x49, 0x68, 0xce, 0xcf, 0x9e, 0xf3, 0xab, 0x1f, 0x48, 0x55, 0xb1, 0x41,
	0xfa, 0x2e, 0x47, 0x49, 0x45, 0x51, 0x29, 0x2e, 0x9c, 0x24, 0x5d, 0x42, 0x64, 0x44, 0x67, 0x28,
	0x65, 0xb6, 0x42, 0x12, 0xc3, 0x40, 0x22, 0xcb, 0x51, 0x2c, 0x3e, 0x27, 0xc1, 0xeb, 0xe0, 0x68,
	0x9f, 0x8c, 0xe1, 0xbe, 0xe0, 0xbc, 0xd4, 0x75, 0xcf, 0xd6, 0x13, 0xd8, 0x57, 0x45, 0x89, 0x52,
	0x65, 0x65, 0x95, 0xf4, 0xf5, 0x55, 0x40, 0x0e, 0xe0, 0x41, 0xe9, 0xfa, 0x93, 0xd0, 0x68, 0xd2,
	0xb7, 0x30, 0x30, 0xa6, 0x97, 0x12, 0x85, 0xe9, 0xaf, 0xa5, 0xe7, 0xa7, 0x27, 0xb0, 0x82, 0xfe,
	0x64, 0x59, 0x89, 0xce, 0xb1, 0x55, 0x5f, 0xe8, 0x29, 0xde, 0xb4, 0xad, 0xda, 0xd4, 0xe7, 0x9d,
	0xfa, 0xbb, 0x0b, 0x3c, 0xe7, 0x8c, 0xe9, 0x47, 0x91, 0x87, 0x30, 0x2c, 0x64, 0x53, 0x14, 0x6c,
	0x65, 0xdb, 0x06, 0xe4, 0x05, 0x84, 0x66, 0xa8, 0x6d, 0x89, 0x66, 0xe3, 0xa9, 0x65, 0xb2, 0x8d,
	0xf4, 0x12, 0xf6, 0x8c, 0xa9, 0xd4, 0xf1, 0xfb, 0xff, 0x7e, 0x36, 0x19, 0xd2, 0x4b, 0x18, 0x99,
	0xf3, 0x29, 0x53, 0x28, 0x6c, 0xa8, 0xd6, 0x2d, 0xf8, 0xaf, 0xdb, 0x5d, 0x40, 0x8f, 0x61, 0x6c,
	0x1f, 0x2c, 0xad, 0x81, 0xc9, 0x64, 0x28, 0x0d, 0xd2, 0x2f, 0x30, 0x34, 0x3d, 0x5f, 0x05, 0x6a,
	0xc2, 0x14, 0x8d, 0xab, 0xe9, 0xdb, 0x75, 0xb5, 0x33, 0x75, 0x46, 0xe3, 0x22, 0xb5, 0x69, 0x7f,
	0x77, 0x68, 0xfa, 0xc1, 0x99, 0x5d, 0xa0, 0xac, 0x38, 0x93, 0x48, 0x5e, 0x41, 0x48, 0x79, 0x8e,
	0xd6, 0x6c, 0x3c, 0x8b, 0x9d, 0x7a, 0xa9, 0x32, 0x55, 0x6b, 0x38, 0x39, 0xfa, 0x2b, 0x72, 0x18,
	0xff, 0x04, 0x70, 0xe0, 0x2d, 0xfe, 0xdb, 0xaf, 0x0a, 0xc9, 0x1b, 0x88, 0x68, 0x77, 0xd5, 0x04,
	0x9b, 0x74, 0x93, 0xdb, 0x9f, 0xa4, 0xd1, 0x35, 0xd4, 0x1b, 0xc8, 0x9e, 0xae, 0xdd, 0xcd, 0x31,
	0x8c, 0xa8, 0x0f, 0xd2, 0x82, 0x88, 0x66, 0x87, 0x9d, 0xb2, 0x63, 0x7c, 0x04, 0x43, 0xea, 0xd1,
	0xb1, 0x3f, 0x52, 0x34, 0x23, 0x9d, 0x74, 0xcb, 0xad, 0x51, 0xb6, 0x4f, 0x4f, 0xf6, 0xee, 0x2a,
	0xdb, 0x2f, 0xc7, 0x2b, 0x00, 0x0f, 0xc1, 0x04, 0x46, 0xae, 0x5a, 0xd6, 0x94, 0xea, 0x97, 0xc4,
	0x81, 0x5e, 0x15, 0x71, 0x57, 0x0b, 0x56, 0xd5, 0x6a, 0xc1, 0x36, 0xd9, 0x75, 0x91, 0xc7, 0x3d,
	0xf2, 0x04, 0x0e, 0xdd, 0xfd, 0x39, 0x57, 0x1f, 0x6b, 0xb5, 0xe6, 0xa2, 0xb8, 0xc1, 0x3c, 0xee,
	0x93, 0x47, 0x30, 0x69, 0x3c, 0x50, 0x6c, 0x50, 0x9c, 0x0a, 0xc1, 0x45, 0x1c, 0x7e, 0x7a, 0x7f,
	0x7b, 0xd2, 0x83, 0x7b, 0xb7, 0x27, 0x21, 0xe9, 0xcd, 0xcf, 0xf4, 0x39, 0x09, 0xe0, 0x29, 0xe5,
	0xe5, 0xf4, 0xea, 0xba, 0x50, 0x37, 0x6b, 0x14, 0xe8, 0xe3, 0xfb, 0x1d, 0x04, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x97, 0x69, 0x82, 0x5c, 0xa5, 0x03, 0x00, 0x00,
}
