// Code generated by protoc-gen-go.
// source: Chat.proto
// DO NOT EDIT!

/*
Package Chat is a generated protocol buffer package.

It is generated from these files:
	Chat.proto

It has these top-level messages:
	ChatMessage
	ChatUser
	ChatRoom
	ChatConnect
	ChatEnterRoom
	ChatPresence
	ChatResponse
	ChatMessageType
*/
package Chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChatStatusCode int32

const (
	ChatStatusCode_Success       ChatStatusCode = 1
	ChatStatusCode_InputInvalid  ChatStatusCode = 2
	ChatStatusCode_NotAuthorized ChatStatusCode = 3
	ChatStatusCode_ServerError   ChatStatusCode = 4
)

var ChatStatusCode_name = map[int32]string{
	1: "Success",
	2: "InputInvalid",
	3: "NotAuthorized",
	4: "ServerError",
}
var ChatStatusCode_value = map[string]int32{
	"Success":       1,
	"InputInvalid":  2,
	"NotAuthorized": 3,
	"ServerError":   4,
}

func (x ChatStatusCode) Enum() *ChatStatusCode {
	p := new(ChatStatusCode)
	*p = x
	return p
}
func (x ChatStatusCode) String() string {
	return proto.EnumName(ChatStatusCode_name, int32(x))
}
func (x *ChatStatusCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChatStatusCode_value, data, "ChatStatusCode")
	if err != nil {
		return err
	}
	*x = ChatStatusCode(value)
	return nil
}
func (ChatStatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChatMessage struct {
	SenderID         *string  `protobuf:"bytes,1,opt,name=senderID" json:"senderID,omitempty"`
	RoomID           *string  `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	Timestamp        *float64 `protobuf:"fixed64,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string  `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetSenderID() string {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return ""
}

func (m *ChatMessage) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() float64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ChatUser struct {
	UserID           *string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatUser) Reset()                    { *m = ChatUser{} }
func (m *ChatUser) String() string            { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()               {}
func (*ChatUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatUser) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *ChatUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type ChatRoom struct {
	RoomID           *string `protobuf:"bytes,1,opt,name=roomID" json:"roomID,omitempty"`
	RoomName         *string `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatRoom) Reset()                    { *m = ChatRoom{} }
func (m *ChatRoom) String() string            { return proto.CompactTextString(m) }
func (*ChatRoom) ProtoMessage()               {}
func (*ChatRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatRoom) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatRoom) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

type ChatConnect struct {
	IsConnecting     *bool       `protobuf:"varint,1,opt,name=isConnecting" json:"isConnecting,omitempty"`
	User             *ChatUser   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Rooms            []*ChatRoom `protobuf:"bytes,3,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatConnect) Reset()                    { *m = ChatConnect{} }
func (m *ChatConnect) String() string            { return proto.CompactTextString(m) }
func (*ChatConnect) ProtoMessage()               {}
func (*ChatConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChatConnect) GetIsConnecting() bool {
	if m != nil && m.IsConnecting != nil {
		return *m.IsConnecting
	}
	return false
}

func (m *ChatConnect) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatConnect) GetRooms() []*ChatRoom {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ChatEnterRoom struct {
	User             *ChatUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	RoomID           *string   `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	UserIsEntering   *bool     `protobuf:"varint,3,opt,name=userIsEntering" json:"userIsEntering,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ChatEnterRoom) Reset()                    { *m = ChatEnterRoom{} }
func (m *ChatEnterRoom) String() string            { return proto.CompactTextString(m) }
func (*ChatEnterRoom) ProtoMessage()               {}
func (*ChatEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChatEnterRoom) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatEnterRoom) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatEnterRoom) GetUserIsEntering() bool {
	if m != nil && m.UserIsEntering != nil {
		return *m.UserIsEntering
	}
	return false
}

type ChatPresence struct {
	Room             *ChatRoom   `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
	Users            []*ChatUser `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatPresence) Reset()                    { *m = ChatPresence{} }
func (m *ChatPresence) String() string            { return proto.CompactTextString(m) }
func (*ChatPresence) ProtoMessage()               {}
func (*ChatPresence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChatPresence) GetRoom() *ChatRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *ChatPresence) GetUsers() []*ChatUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChatResponse struct {
	Code             *ChatStatusCode `protobuf:"varint,1,opt,name=code,enum=Chat.ChatStatusCode" json:"code,omitempty"`
	Message          *string         `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ChatResponse) Reset()                    { *m = ChatResponse{} }
func (m *ChatResponse) String() string            { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()               {}
func (*ChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChatResponse) GetCode() ChatStatusCode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ChatStatusCode_Success
}

func (m *ChatResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ChatMessageType struct {
	ChatMessage      *ChatMessage   `protobuf:"bytes,1,opt,name=chatMessage" json:"chatMessage,omitempty"`
	ChatConnect      *ChatConnect   `protobuf:"bytes,2,opt,name=chatConnect" json:"chatConnect,omitempty"`
	ChatEnterRoom    *ChatEnterRoom `protobuf:"bytes,3,opt,name=chatEnterRoom" json:"chatEnterRoom,omitempty"`
	ChatPresence     *ChatPresence  `protobuf:"bytes,4,opt,name=chatPresence" json:"chatPresence,omitempty"`
	ChatResponse     *ChatResponse  `protobuf:"bytes,5,opt,name=chatResponse" json:"chatResponse,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ChatMessageType) Reset()                    { *m = ChatMessageType{} }
func (m *ChatMessageType) String() string            { return proto.CompactTextString(m) }
func (*ChatMessageType) ProtoMessage()               {}
func (*ChatMessageType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ChatMessageType) GetChatMessage() *ChatMessage {
	if m != nil {
		return m.ChatMessage
	}
	return nil
}

func (m *ChatMessageType) GetChatConnect() *ChatConnect {
	if m != nil {
		return m.ChatConnect
	}
	return nil
}

func (m *ChatMessageType) GetChatEnterRoom() *ChatEnterRoom {
	if m != nil {
		return m.ChatEnterRoom
	}
	return nil
}

func (m *ChatMessageType) GetChatPresence() *ChatPresence {
	if m != nil {
		return m.ChatPresence
	}
	return nil
}

func (m *ChatMessageType) GetChatResponse() *ChatResponse {
	if m != nil {
		return m.ChatResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "Chat.ChatMessage")
	proto.RegisterType((*ChatUser)(nil), "Chat.ChatUser")
	proto.RegisterType((*ChatRoom)(nil), "Chat.ChatRoom")
	proto.RegisterType((*ChatConnect)(nil), "Chat.ChatConnect")
	proto.RegisterType((*ChatEnterRoom)(nil), "Chat.ChatEnterRoom")
	proto.RegisterType((*ChatPresence)(nil), "Chat.ChatPresence")
	proto.RegisterType((*ChatResponse)(nil), "Chat.ChatResponse")
	proto.RegisterType((*ChatMessageType)(nil), "Chat.ChatMessageType")
	proto.RegisterEnum("Chat.ChatStatusCode", ChatStatusCode_name, ChatStatusCode_value)
}

var fileDescriptor0 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xef, 0x6e, 0xd3, 0x3c,
	0x14, 0xc6, 0x5f, 0xb7, 0xd9, 0xbb, 0xee, 0xa4, 0xcd, 0x32, 0x33, 0xa1, 0xf0, 0x4f, 0x42, 0xf9,
	0x80, 0xa6, 0x09, 0x8a, 0xd4, 0x0b, 0x98, 0x04, 0x65, 0x1f, 0x2a, 0xb4, 0x09, 0x2d, 0xec, 0x3b,
	0x99, 0x73, 0xb4, 0x1a, 0x16, 0x3b, 0xb2, 0x9d, 0x4a, 0xec, 0x0a, 0xb8, 0xbe, 0xdd, 0x01, 0x77,
	0x82, 0xed, 0x24, 0x4d, 0xe8, 0xf8, 0x66, 0x27, 0xcf, 0x79, 0xce, 0x73, 0x7e, 0x3e, 0x00, 0xcb,
	0x75, 0x6e, 0xe6, 0x95, 0x92, 0x46, 0xd2, 0xc0, 0x9d, 0x9f, 0xbf, 0x90, 0x37, 0xdf, 0x91, 0x19,
	0xbe, 0x41, 0xf6, 0xae, 0x40, 0xcd, 0x14, 0xaf, 0x8c, 0x54, 0x8d, 0x24, 0xcd, 0x20, 0x74, 0xa2,
	0x0b, 0xd4, 0x3a, 0xbf, 0x45, 0x1a, 0xc3, 0x44, 0xa3, 0x28, 0x50, 0xad, 0x3e, 0x25, 0xe4, 0x35,
	0x39, 0x39, 0xa0, 0x11, 0xfc, 0xaf, 0xa4, 0x2c, 0xed, 0x7d, 0xe4, 0xef, 0x47, 0x70, 0x60, 0x78,
	0x89, 0xda, 0xe4, 0x65, 0x95, 0x8c, 0xed, 0x27, 0x42, 0x0f, 0x61, 0xbf, 0x6c, 0xea, 0x93, 0xc0,
	0x69, 0xd2, 0xb7, 0x30, 0x71, 0xa6, 0xd7, 0x1a, 0x95, 0xab, 0xaf, 0xf5, 0xc0, 0xcf, 0x76, 0x10,
	0x9c, 0xfd, 0x10, 0x79, 0x89, 0x8d, 0x63, 0xa7, 0xbe, 0xb2, 0x5d, 0x06, 0xdd, 0xb6, 0x6a, 0x77,
	0xbf, 0xec, 0xd5, 0xdf, 0x9a, 0xc0, 0x4b, 0x29, 0x84, 0x1d, 0x8a, 0x1e, 0xc3, 0x94, 0xeb, 0xf6,
	0xc2, 0xc5, 0xad, 0x2f, 0x9b, 0xd0, 0x97, 0x10, 0xb8, 0xa6, 0xbe, 0x24, 0x5c, 0x44, 0x73, 0xcf,
	0x64, 0x1b, 0xe9, 0x15, 0xec, 0x39, 0x53, 0x6d, 0xe3, 0x8f, 0xff, 0xfe, 0xed, 0x32, 0xa4, 0xd7,
	0x30, 0x73, 0xe7, 0x73, 0x61, 0x50, 0xf9, 0x50, 0x9d, 0x1b, 0xf9, 0xa7, 0xdb, 0x2e, 0xa0, 0xa7,
	0x10, 0xf9, 0x81, 0xb5, 0x37, 0x70, 0x99, 0x1c, 0xa5, 0x49, 0xfa, 0x19, 0xa6, 0xae, 0xe6, 0x8b,
	0x42, 0x4b, 0x98, 0xa1, 0x73, 0x75, 0x75, 0x8f, 0x5d, 0x7d, 0x4f, 0x9b, 0xd1, 0xb9, 0x68, 0x6b,
	0x3a, 0x7e, 0xdc, 0x34, 0x5d, 0x36, 0x66, 0x57, 0xa8, 0x2b, 0x29, 0x34, 0xd2, 0x14, 0x02, 0x26,
	0x0b, 0xf4, 0x66, 0xd1, 0xe2, 0xb8, 0x57, 0x67, 0x26, 0x37, 0xb5, 0x05, 0x54, 0xe0, 0xf0, 0x99,
	0x1a, 0x94, 0xbf, 0x09, 0x1c, 0x0e, 0x1e, 0xff, 0xeb, 0xcf, 0x0a, 0xe9, 0x1b, 0x08, 0x59, 0xff,
	0xa9, 0x0d, 0x77, 0xd4, 0xfb, 0x75, 0x8b, 0xd2, 0xea, 0x5a, 0xf2, 0x2d, 0xe8, 0x81, 0xae, 0x7b,
	0x9f, 0x53, 0x98, 0xb1, 0x21, 0x4c, 0x0f, 0x23, 0x5c, 0x3c, 0xe9, 0x95, 0x3d, 0xe7, 0x13, 0x98,
	0xb2, 0x01, 0x21, 0xbf, 0x4c, 0xe1, 0x82, 0xf6, 0xd2, 0x2d, 0xbb, 0x56, 0xd9, 0x8d, 0x9f, 0xec,
	0xed, 0x2a, 0xbb, 0x3f, 0xa7, 0x19, 0x44, 0x3b, 0x18, 0x42, 0xd8, 0xcf, 0x6a, 0xc6, 0xec, 0x1c,
	0x31, 0xb1, 0xfb, 0x35, 0x5d, 0x89, 0xaa, 0x36, 0x2b, 0xb1, 0xc9, 0xef, 0x78, 0x11, 0x8f, 0xec,
	0x7e, 0xcf, 0x2e, 0xa5, 0xf9, 0x50, 0x9b, 0xb5, 0x54, 0xfc, 0x1e, 0x8b, 0x78, 0x6c, 0xc1, 0x85,
	0x19, 0xaa, 0x0d, 0xaa, 0x73, 0xa5, 0xa4, 0x8a, 0x83, 0x8f, 0xef, 0x1f, 0xce, 0x46, 0xf0, 0xdf,
	0xc3, 0x59, 0x40, 0x47, 0xcb, 0x0b, 0x7b, 0x4e, 0x08, 0x3c, 0x63, 0xb2, 0x9c, 0xdf, 0xdc, 0x71,
	0x73, 0xbf, 0x46, 0x85, 0x43, 0x54, 0xbf, 0x08, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x8b,
	0xc1, 0x69, 0x95, 0x03, 0x00, 0x00,
}
