#!/bin/bash
set -euo pipefail

openssl pkcs12 -in Certificates.p12 -out Certificates.pem -nodes
csplit -k Certificates.pem '/Bag Attribute/' '{1000}' || true

for file in xx*; do
    name=$(grep -i friendlyname "$file")
    name="${name#*: }"
    mv "$file" "$name"
done
