// Code generated by protoc-gen-go.
// source: Chat.proto
// DO NOT EDIT!

/*
Package BlitzMessage is a generated protocol buffer package.

It is generated from these files:
	Chat.proto
	Device.proto
	EntityTags.proto
	Feed.proto
	Friends.proto
	Search.proto
	Server.proto
	Types.proto
	UserEvents.proto
	UserMessages.proto
	UserProfiles.proto

It has these top-level messages:
	ChatMessage
	ChatUser
	ChatRoom
	ChatConnect
	ChatRoomEntrance
	ChatPresence
	DeviceInfo
	EntityTag
	EntityTagList
	FeedPost
	FeedPostUpdateRequest
	FeedPostUpdateResponse
	FeedPostFetchRequest
	FeedPostFetchResponse
	Friend
	FriendUpdate
	FriendRequest
	AcceptInviteRequest
	AcceptInviteResponse
	AutocompleteRequest
	AutocompleteResponse
	DebugMessage
	SessionRequest
	BlitzHereAppOptions
	AppOptions
	SessionResponse
	RequestType
	ServerRequest
	ResponseType
	ServerResponse
	Globals
	Coordinate
	Size
	CoordinateRegion
	CoordinatePolygon
	Location
	Timestamp
	Timespan
	Void
	KeyValue
	UserEvent
	UserEventBatch
	UserEventBatchResponse
	UserMessage
	UserMessageUpdate
	SocialIdentity
	ContactInfo
	Employment
	Education
	ImageData
	UserProfile
	ImageUpload
	UserProfileUpdate
	UserProfileQuery
	ConfirmationRequest
	ProfilesFromContactInfo
*/
package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ChatMessage struct {
	SenderID         *string    `protobuf:"bytes,1,opt,name=senderID" json:"senderID,omitempty"`
	RoomID           *string    `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	Timestamp        *Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Message          *string    `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMessage) GetSenderID() string {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return ""
}

func (m *ChatMessage) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatMessage) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type ChatUser struct {
	UserID           *string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	Nickname         *string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatUser) Reset()                    { *m = ChatUser{} }
func (m *ChatUser) String() string            { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()               {}
func (*ChatUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChatUser) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *ChatUser) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type ChatRoom struct {
	RoomID           *string `protobuf:"bytes,1,opt,name=roomID" json:"roomID,omitempty"`
	RoomName         *string `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatRoom) Reset()                    { *m = ChatRoom{} }
func (m *ChatRoom) String() string            { return proto.CompactTextString(m) }
func (*ChatRoom) ProtoMessage()               {}
func (*ChatRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChatRoom) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatRoom) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

type ChatConnect struct {
	IsConnecting     *bool       `protobuf:"varint,1,opt,name=isConnecting" json:"isConnecting,omitempty"`
	User             *ChatUser   `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Rooms            []*ChatRoom `protobuf:"bytes,3,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatConnect) Reset()                    { *m = ChatConnect{} }
func (m *ChatConnect) String() string            { return proto.CompactTextString(m) }
func (*ChatConnect) ProtoMessage()               {}
func (*ChatConnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChatConnect) GetIsConnecting() bool {
	if m != nil && m.IsConnecting != nil {
		return *m.IsConnecting
	}
	return false
}

func (m *ChatConnect) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatConnect) GetRooms() []*ChatRoom {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ChatRoomEntrance struct {
	User             *ChatUser `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	RoomID           *string   `protobuf:"bytes,2,opt,name=roomID" json:"roomID,omitempty"`
	UserIsEntering   *bool     `protobuf:"varint,3,opt,name=userIsEntering" json:"userIsEntering,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ChatRoomEntrance) Reset()                    { *m = ChatRoomEntrance{} }
func (m *ChatRoomEntrance) String() string            { return proto.CompactTextString(m) }
func (*ChatRoomEntrance) ProtoMessage()               {}
func (*ChatRoomEntrance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChatRoomEntrance) GetUser() *ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ChatRoomEntrance) GetRoomID() string {
	if m != nil && m.RoomID != nil {
		return *m.RoomID
	}
	return ""
}

func (m *ChatRoomEntrance) GetUserIsEntering() bool {
	if m != nil && m.UserIsEntering != nil {
		return *m.UserIsEntering
	}
	return false
}

type ChatPresence struct {
	Room             *ChatRoom   `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
	Users            []*ChatUser `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ChatPresence) Reset()                    { *m = ChatPresence{} }
func (m *ChatPresence) String() string            { return proto.CompactTextString(m) }
func (*ChatPresence) ProtoMessage()               {}
func (*ChatPresence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChatPresence) GetRoom() *ChatRoom {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *ChatPresence) GetUsers() []*ChatUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*ChatMessage)(nil), "BlitzMessage.ChatMessage")
	proto.RegisterType((*ChatUser)(nil), "BlitzMessage.ChatUser")
	proto.RegisterType((*ChatRoom)(nil), "BlitzMessage.ChatRoom")
	proto.RegisterType((*ChatConnect)(nil), "BlitzMessage.ChatConnect")
	proto.RegisterType((*ChatRoomEntrance)(nil), "BlitzMessage.ChatRoomEntrance")
	proto.RegisterType((*ChatPresence)(nil), "BlitzMessage.ChatPresence")
}

var fileDescriptor0 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x76, 0x29, 0x6a, 0x99, 0x12, 0x24, 0x1b, 0x83, 0x0d, 0x5e, 0x4c, 0xa3, 0x89, 0x31, 0x5a,
	0x13, 0x1e, 0x80, 0x03, 0xe8, 0xc1, 0x83, 0xc6, 0x18, 0x3c, 0x79, 0xb1, 0x94, 0x09, 0xac, 0xd2,
	0xdd, 0x66, 0x77, 0x35, 0xd1, 0x27, 0xf0, 0xf9, 0x78, 0x22, 0x77, 0x5a, 0x40, 0x30, 0xe2, 0x6d,
	0xbf, 0xe9, 0xf7, 0x37, 0x53, 0x80, 0xfe, 0x24, 0xb1, 0x71, 0xae, 0x95, 0x55, 0xbc, 0xde, 0x9b,
	0x0a, 0xfb, 0x79, 0x8b, 0xc6, 0x24, 0x63, 0x6c, 0x1f, 0xaa, 0xe1, 0x0b, 0xa6, 0x56, 0xbc, 0x63,
	0x7a, 0x31, 0x42, 0x93, 0x6a, 0x91, 0x5b, 0xa5, 0x4b, 0x6a, 0x3b, 0x18, 0x7c, 0xe4, 0x68, 0x4a,
	0x10, 0x4d, 0x21, 0x20, 0x97, 0xb9, 0x90, 0x37, 0xc1, 0x37, 0x28, 0x47, 0xa8, 0x6f, 0xae, 0x42,
	0x76, 0xc4, 0x4e, 0x6b, 0xbc, 0x01, 0x3b, 0x5a, 0xa9, 0xcc, 0xe1, 0x4a, 0x81, 0xcf, 0xa0, 0x66,
	0x45, 0x86, 0xc6, 0x26, 0x59, 0x1e, 0x7a, 0x6e, 0x14, 0x74, 0x0e, 0xe2, 0xd5, 0xf0, 0x78, 0xb0,
	0xf8, 0xcc, 0xf7, 0x60, 0x37, 0x2b, 0x87, 0x61, 0x95, 0xc4, 0xd1, 0x39, 0xf8, 0x94, 0xf6, 0x68,
	0x50, 0x93, 0xf1, 0x9b, 0x59, 0x09, 0x72, 0xd1, 0x52, 0xa4, 0xaf, 0x32, 0xc9, 0xb0, 0x8c, 0x5a,
	0xb0, 0x1f, 0x5c, 0xfc, 0x4a, 0x8d, 0x25, 0x9b, 0xf0, 0xdd, 0x0f, 0x3b, 0x2f, 0x37, 0xe9, 0x2b,
	0x29, 0xdd, 0xea, 0x7c, 0x1f, 0xea, 0xc2, 0xcc, 0x81, 0x90, 0xe3, 0x42, 0xe6, 0xf3, 0x63, 0xa8,
	0x52, 0x68, 0x21, 0x09, 0x3a, 0xad, 0xf5, 0xe2, 0xcb, 0x6a, 0x27, 0xb0, 0x4d, 0xe6, 0xc6, 0xed,
	0xe7, 0xfd, 0x4d, 0xa3, 0x4e, 0xd1, 0x33, 0x34, 0x17, 0xef, 0x6b, 0x69, 0x75, 0x22, 0x53, 0x5c,
	0x06, 0xb0, 0x7f, 0x03, 0x7e, 0x1f, 0xb5, 0x05, 0x8d, 0xe2, 0x16, 0xc6, 0xf9, 0xa0, 0xa6, 0xba,
	0x74, 0x59, 0x3f, 0x7a, 0x82, 0x3a, 0x69, 0xee, 0x35, 0xba, 0xbf, 0x52, 0xba, 0x93, 0x6e, 0xb3,
	0x7b, 0x71, 0x2b, 0x57, 0x9f, 0xdc, 0x8c, 0x33, 0xf7, 0x36, 0x97, 0xe8, 0x5d, 0xce, 0xba, 0x15,
	0xd8, 0x9a, 0x75, 0x3d, 0xce, 0x7a, 0xee, 0x19, 0x32, 0x68, 0xa7, 0x2a, 0x8b, 0x87, 0x44, 0x9e,
	0xa0, 0xc6, 0x35, 0xd9, 0x17, 0x63, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0xe3, 0xa1, 0x2c,
	0x70, 0x02, 0x00, 0x00,
}
