// Code generated by protoc-gen-go.
// source: Feed.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FeedPostType int32

const (
	FeedPostType_FPUnknown           FeedPostType = 0
	FeedPostType_FPOpenEndedQuestion FeedPostType = 1
	FeedPostType_FPOpenEndedReply    FeedPostType = 2
	FeedPostType_FPSurveyQuestion    FeedPostType = 3
	FeedPostType_FPSurveyAnswer      FeedPostType = 4
	FeedPostType_FPWantedQuestion    FeedPostType = 5
	FeedPostType_FPWantedAnswer      FeedPostType = 6
)

var FeedPostType_name = map[int32]string{
	0: "FPUnknown",
	1: "FPOpenEndedQuestion",
	2: "FPOpenEndedReply",
	3: "FPSurveyQuestion",
	4: "FPSurveyAnswer",
	5: "FPWantedQuestion",
	6: "FPWantedAnswer",
}
var FeedPostType_value = map[string]int32{
	"FPUnknown":           0,
	"FPOpenEndedQuestion": 1,
	"FPOpenEndedReply":    2,
	"FPSurveyQuestion":    3,
	"FPSurveyAnswer":      4,
	"FPWantedQuestion":    5,
	"FPWantedAnswer":      6,
}

func (x FeedPostType) Enum() *FeedPostType {
	p := new(FeedPostType)
	*p = x
	return p
}
func (x FeedPostType) String() string {
	return proto.EnumName(FeedPostType_name, int32(x))
}
func (x *FeedPostType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostType_value, data, "FeedPostType")
	if err != nil {
		return err
	}
	*x = FeedPostType(value)
	return nil
}
func (FeedPostType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type FeedPostScope int32

const (
	FeedPostScope_FPScopeUnknown       FeedPostScope = 0
	FeedPostScope_FPScopeLocalNetwork  FeedPostScope = 1
	FeedPostScope_FPScopeGlobalNetwork FeedPostScope = 2
)

var FeedPostScope_name = map[int32]string{
	0: "FPScopeUnknown",
	1: "FPScopeLocalNetwork",
	2: "FPScopeGlobalNetwork",
}
var FeedPostScope_value = map[string]int32{
	"FPScopeUnknown":       0,
	"FPScopeLocalNetwork":  1,
	"FPScopeGlobalNetwork": 2,
}

func (x FeedPostScope) Enum() *FeedPostScope {
	p := new(FeedPostScope)
	*p = x
	return p
}
func (x FeedPostScope) String() string {
	return proto.EnumName(FeedPostScope_name, int32(x))
}
func (x *FeedPostScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostScope_value, data, "FeedPostScope")
	if err != nil {
		return err
	}
	*x = FeedPostScope(value)
	return nil
}
func (FeedPostScope) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type FeedPostStatus int32

const (
	FeedPostStatus_FPSUnknown  FeedPostStatus = 0
	FeedPostStatus_FPSActive   FeedPostStatus = 1
	FeedPostStatus_FPSDeleted  FeedPostStatus = 2
	FeedPostStatus_FPSAnswered FeedPostStatus = 3
)

var FeedPostStatus_name = map[int32]string{
	0: "FPSUnknown",
	1: "FPSActive",
	2: "FPSDeleted",
	3: "FPSAnswered",
}
var FeedPostStatus_value = map[string]int32{
	"FPSUnknown":  0,
	"FPSActive":   1,
	"FPSDeleted":  2,
	"FPSAnswered": 3,
}

func (x FeedPostStatus) Enum() *FeedPostStatus {
	p := new(FeedPostStatus)
	*p = x
	return p
}
func (x FeedPostStatus) String() string {
	return proto.EnumName(FeedPostStatus_name, int32(x))
}
func (x *FeedPostStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostStatus_value, data, "FeedPostStatus")
	if err != nil {
		return err
	}
	*x = FeedPostStatus(value)
	return nil
}
func (FeedPostStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type UpdateVerb int32

const (
	UpdateVerb_UVCreate UpdateVerb = 1
	UpdateVerb_UVUpdate UpdateVerb = 2
	UpdateVerb_UVDelete UpdateVerb = 3
)

var UpdateVerb_name = map[int32]string{
	1: "UVCreate",
	2: "UVUpdate",
	3: "UVDelete",
}
var UpdateVerb_value = map[string]int32{
	"UVCreate": 1,
	"UVUpdate": 2,
	"UVDelete": 3,
}

func (x UpdateVerb) Enum() *UpdateVerb {
	p := new(UpdateVerb)
	*p = x
	return p
}
func (x UpdateVerb) String() string {
	return proto.EnumName(UpdateVerb_name, int32(x))
}
func (x *UpdateVerb) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpdateVerb_value, data, "UpdateVerb")
	if err != nil {
		return err
	}
	*x = UpdateVerb(value)
	return nil
}
func (UpdateVerb) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type FeedPanelMember struct {
	UserID           *string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	BountyAmount     *string    `protobuf:"bytes,2,opt,name=bountyAmount" json:"bountyAmount,omitempty"`
	DateAnswered     *Timestamp `protobuf:"bytes,3,opt,name=dateAnswered" json:"dateAnswered,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *FeedPanelMember) Reset()                    { *m = FeedPanelMember{} }
func (m *FeedPanelMember) String() string            { return proto.CompactTextString(m) }
func (*FeedPanelMember) ProtoMessage()               {}
func (*FeedPanelMember) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *FeedPanelMember) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *FeedPanelMember) GetBountyAmount() string {
	if m != nil && m.BountyAmount != nil {
		return *m.BountyAmount
	}
	return ""
}

func (m *FeedPanelMember) GetDateAnswered() *Timestamp {
	if m != nil {
		return m.DateAnswered
	}
	return nil
}

type FeedPost struct {
	PostID                   *string            `protobuf:"bytes,1,opt,name=postID" json:"postID,omitempty"`
	ParentID                 *string            `protobuf:"bytes,2,opt,name=parentID" json:"parentID,omitempty"`
	PostType                 *FeedPostType      `protobuf:"varint,3,opt,name=postType,enum=BlitzMessage.FeedPostType" json:"postType,omitempty"`
	PostScope                *FeedPostScope     `protobuf:"varint,4,opt,name=postScope,enum=BlitzMessage.FeedPostScope" json:"postScope,omitempty"`
	UserID                   *string            `protobuf:"bytes,5,opt,name=userID" json:"userID,omitempty"`
	AnonymousPost            *bool              `protobuf:"varint,6,opt,name=anonymousPost,def=0" json:"anonymousPost,omitempty"`
	Timestamp                *Timestamp         `protobuf:"bytes,7,opt,name=timestamp" json:"timestamp,omitempty"`
	TimespanActive           *Timespan          `protobuf:"bytes,8,opt,name=timespanActive" json:"timespanActive,omitempty"`
	HeadlineText             *string            `protobuf:"bytes,9,opt,name=headlineText" json:"headlineText,omitempty"`
	BodyText                 *string            `protobuf:"bytes,10,opt,name=bodyText" json:"bodyText,omitempty"`
	PostTags                 []*EntityTag       `protobuf:"bytes,12,rep,name=postTags" json:"postTags,omitempty"`
	RepliesDeprecated        []*FeedPost        `protobuf:"bytes,13,rep,name=replies_deprecated" json:"replies_deprecated,omitempty"`
	MayAddReply              *bool              `protobuf:"varint,14,opt,name=mayAddReply" json:"mayAddReply,omitempty"`
	MayChooseMulitpleReplies *bool              `protobuf:"varint,15,opt,name=mayChooseMulitpleReplies" json:"mayChooseMulitpleReplies,omitempty"`
	SurveyAnswerSequence     *int32             `protobuf:"varint,16,opt,name=surveyAnswerSequence" json:"surveyAnswerSequence,omitempty"`
	AreMoreReplies           *bool              `protobuf:"varint,17,opt,name=areMoreReplies" json:"areMoreReplies,omitempty"`
	TotalVoteCount           *int32             `protobuf:"varint,18,opt,name=totalVoteCount" json:"totalVoteCount,omitempty"`
	AmountPerReplyDeprecated *string            `protobuf:"bytes,19,opt,name=amountPerReply_deprecated" json:"amountPerReply_deprecated,omitempty"`
	AmountTotal              *string            `protobuf:"bytes,20,opt,name=amountTotal" json:"amountTotal,omitempty"`
	PanelUserIDsDeprecated   []string           `protobuf:"bytes,21,rep,name=panelUserIDs_deprecated" json:"panelUserIDs_deprecated,omitempty"`
	Panel                    []*FeedPanelMember `protobuf:"bytes,22,rep,name=panel" json:"panel,omitempty"`
	PostStatus               *FeedPostStatus    `protobuf:"varint,23,opt,name=postStatus,enum=BlitzMessage.FeedPostStatus" json:"postStatus,omitempty"`
	ReferreeID               *string            `protobuf:"bytes,24,opt,name=referreeID" json:"referreeID,omitempty"`
	XXX_unrecognized         []byte             `json:"-"`
}

func (m *FeedPost) Reset()                    { *m = FeedPost{} }
func (m *FeedPost) String() string            { return proto.CompactTextString(m) }
func (*FeedPost) ProtoMessage()               {}
func (*FeedPost) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

const Default_FeedPost_AnonymousPost bool = false

func (m *FeedPost) GetPostID() string {
	if m != nil && m.PostID != nil {
		return *m.PostID
	}
	return ""
}

func (m *FeedPost) GetParentID() string {
	if m != nil && m.ParentID != nil {
		return *m.ParentID
	}
	return ""
}

func (m *FeedPost) GetPostType() FeedPostType {
	if m != nil && m.PostType != nil {
		return *m.PostType
	}
	return FeedPostType_FPUnknown
}

func (m *FeedPost) GetPostScope() FeedPostScope {
	if m != nil && m.PostScope != nil {
		return *m.PostScope
	}
	return FeedPostScope_FPScopeUnknown
}

func (m *FeedPost) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *FeedPost) GetAnonymousPost() bool {
	if m != nil && m.AnonymousPost != nil {
		return *m.AnonymousPost
	}
	return Default_FeedPost_AnonymousPost
}

func (m *FeedPost) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *FeedPost) GetTimespanActive() *Timespan {
	if m != nil {
		return m.TimespanActive
	}
	return nil
}

func (m *FeedPost) GetHeadlineText() string {
	if m != nil && m.HeadlineText != nil {
		return *m.HeadlineText
	}
	return ""
}

func (m *FeedPost) GetBodyText() string {
	if m != nil && m.BodyText != nil {
		return *m.BodyText
	}
	return ""
}

func (m *FeedPost) GetPostTags() []*EntityTag {
	if m != nil {
		return m.PostTags
	}
	return nil
}

func (m *FeedPost) GetRepliesDeprecated() []*FeedPost {
	if m != nil {
		return m.RepliesDeprecated
	}
	return nil
}

func (m *FeedPost) GetMayAddReply() bool {
	if m != nil && m.MayAddReply != nil {
		return *m.MayAddReply
	}
	return false
}

func (m *FeedPost) GetMayChooseMulitpleReplies() bool {
	if m != nil && m.MayChooseMulitpleReplies != nil {
		return *m.MayChooseMulitpleReplies
	}
	return false
}

func (m *FeedPost) GetSurveyAnswerSequence() int32 {
	if m != nil && m.SurveyAnswerSequence != nil {
		return *m.SurveyAnswerSequence
	}
	return 0
}

func (m *FeedPost) GetAreMoreReplies() bool {
	if m != nil && m.AreMoreReplies != nil {
		return *m.AreMoreReplies
	}
	return false
}

func (m *FeedPost) GetTotalVoteCount() int32 {
	if m != nil && m.TotalVoteCount != nil {
		return *m.TotalVoteCount
	}
	return 0
}

func (m *FeedPost) GetAmountPerReplyDeprecated() string {
	if m != nil && m.AmountPerReplyDeprecated != nil {
		return *m.AmountPerReplyDeprecated
	}
	return ""
}

func (m *FeedPost) GetAmountTotal() string {
	if m != nil && m.AmountTotal != nil {
		return *m.AmountTotal
	}
	return ""
}

func (m *FeedPost) GetPanelUserIDsDeprecated() []string {
	if m != nil {
		return m.PanelUserIDsDeprecated
	}
	return nil
}

func (m *FeedPost) GetPanel() []*FeedPanelMember {
	if m != nil {
		return m.Panel
	}
	return nil
}

func (m *FeedPost) GetPostStatus() FeedPostStatus {
	if m != nil && m.PostStatus != nil {
		return *m.PostStatus
	}
	return FeedPostStatus_FPSUnknown
}

func (m *FeedPost) GetReferreeID() string {
	if m != nil && m.ReferreeID != nil {
		return *m.ReferreeID
	}
	return ""
}

type FeedPostUpdateRequest struct {
	UpdateVerb         *UpdateVerb `protobuf:"varint,1,opt,name=updateVerb,enum=BlitzMessage.UpdateVerb" json:"updateVerb,omitempty"`
	FeedPostDeprecated *FeedPost   `protobuf:"bytes,2,opt,name=feedPost_deprecated" json:"feedPost_deprecated,omitempty"`
	FeedPosts          []*FeedPost `protobuf:"bytes,3,rep,name=feedPosts" json:"feedPosts,omitempty"`
	XXX_unrecognized   []byte      `json:"-"`
}

func (m *FeedPostUpdateRequest) Reset()                    { *m = FeedPostUpdateRequest{} }
func (m *FeedPostUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedPostUpdateRequest) ProtoMessage()               {}
func (*FeedPostUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *FeedPostUpdateRequest) GetUpdateVerb() UpdateVerb {
	if m != nil && m.UpdateVerb != nil {
		return *m.UpdateVerb
	}
	return UpdateVerb_UVCreate
}

func (m *FeedPostUpdateRequest) GetFeedPostDeprecated() *FeedPost {
	if m != nil {
		return m.FeedPostDeprecated
	}
	return nil
}

func (m *FeedPostUpdateRequest) GetFeedPosts() []*FeedPost {
	if m != nil {
		return m.FeedPosts
	}
	return nil
}

type FeedPostFetchRequest struct {
	Timespan         *Timespan      `protobuf:"bytes,1,opt,name=timespan" json:"timespan,omitempty"`
	FeedScope        *FeedPostScope `protobuf:"varint,2,opt,name=feedScope,enum=BlitzMessage.FeedPostScope" json:"feedScope,omitempty"`
	ParentID         *string        `protobuf:"bytes,3,opt,name=parentID" json:"parentID,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *FeedPostFetchRequest) Reset()                    { *m = FeedPostFetchRequest{} }
func (m *FeedPostFetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedPostFetchRequest) ProtoMessage()               {}
func (*FeedPostFetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *FeedPostFetchRequest) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *FeedPostFetchRequest) GetFeedScope() FeedPostScope {
	if m != nil && m.FeedScope != nil {
		return *m.FeedScope
	}
	return FeedPostScope_FPScopeUnknown
}

func (m *FeedPostFetchRequest) GetParentID() string {
	if m != nil && m.ParentID != nil {
		return *m.ParentID
	}
	return ""
}

type FeedPostResponse struct {
	FeedPosts        []*FeedPost `protobuf:"bytes,1,rep,name=feedPosts" json:"feedPosts,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FeedPostResponse) Reset()                    { *m = FeedPostResponse{} }
func (m *FeedPostResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedPostResponse) ProtoMessage()               {}
func (*FeedPostResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *FeedPostResponse) GetFeedPosts() []*FeedPost {
	if m != nil {
		return m.FeedPosts
	}
	return nil
}

func init() {
	proto.RegisterType((*FeedPanelMember)(nil), "BlitzMessage.FeedPanelMember")
	proto.RegisterType((*FeedPost)(nil), "BlitzMessage.FeedPost")
	proto.RegisterType((*FeedPostUpdateRequest)(nil), "BlitzMessage.FeedPostUpdateRequest")
	proto.RegisterType((*FeedPostFetchRequest)(nil), "BlitzMessage.FeedPostFetchRequest")
	proto.RegisterType((*FeedPostResponse)(nil), "BlitzMessage.FeedPostResponse")
	proto.RegisterEnum("BlitzMessage.FeedPostType", FeedPostType_name, FeedPostType_value)
	proto.RegisterEnum("BlitzMessage.FeedPostScope", FeedPostScope_name, FeedPostScope_value)
	proto.RegisterEnum("BlitzMessage.FeedPostStatus", FeedPostStatus_name, FeedPostStatus_value)
	proto.RegisterEnum("BlitzMessage.UpdateVerb", UpdateVerb_name, UpdateVerb_value)
}

func init() { proto.RegisterFile("Feed.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 844 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x55, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xce, 0x4a, 0x91, 0x91, 0xda, 0xb2, 0xbc, 0xac, 0x1d, 0x7b, 0x70, 0x4c, 0x61, 0x7c, 0x4a,
	0x54, 0x89, 0xa0, 0x4c, 0x15, 0x07, 0xaa, 0x48, 0x95, 0xed, 0xc4, 0x14, 0x55, 0x18, 0x84, 0x25,
	0x99, 0x23, 0x35, 0xda, 0x6d, 0x47, 0x22, 0xab, 0x99, 0x65, 0x76, 0x14, 0x23, 0x8e, 0x9c, 0x78,
	0x0c, 0x2e, 0xbc, 0x50, 0xde, 0x83, 0x77, 0xa0, 0xa7, 0x47, 0xab, 0xec, 0x82, 0xe2, 0x9c, 0xac,
	0xf9, 0xe6, 0xeb, 0x6f, 0xfa, 0xe7, 0xeb, 0x35, 0xc0, 0x05, 0x62, 0xd2, 0xcb, 0x8c, 0xb6, 0x3a,
	0x6a, 0x9f, 0xa5, 0x53, 0xfb, 0xfb, 0x25, 0xe6, 0xb9, 0x7c, 0x89, 0x07, 0x0f, 0xf5, 0xf8, 0x17,
	0x8c, 0xed, 0xf4, 0x35, 0xc6, 0x4f, 0x13, 0xcc, 0x63, 0x33, 0xcd, 0xac, 0x36, 0x9e, 0x7a, 0xb0,
	0x39, 0x5c, 0x64, 0x98, 0x2f, 0x0f, 0xe1, 0x0b, 0x65, 0xa7, 0x76, 0x31, 0x94, 0x2f, 0x97, 0xc8,
	0xf1, 0x0d, 0x6c, 0x3b, 0xdd, 0xbe, 0x54, 0x98, 0x5e, 0xe2, 0x6c, 0x8c, 0x26, 0xea, 0xc0, 0xc6,
	0x3c, 0x47, 0xf3, 0xed, 0x73, 0x11, 0x1c, 0x05, 0x8f, 0x5a, 0xd1, 0x2e, 0xb4, 0xc7, 0x7a, 0xae,
	0xec, 0xe2, 0x74, 0xe6, 0xfe, 0x88, 0x1a, 0xa3, 0x4f, 0xa1, 0x9d, 0x48, 0x8b, 0xa7, 0x2a, 0xbf,
	0x45, 0x83, 0x89, 0xa8, 0x13, 0xba, 0x79, 0xb2, 0xdf, 0x2b, 0x67, 0xd6, 0x1b, 0x4e, 0x67, 0x98,
	0x5b, 0x39, 0xcb, 0x8e, 0xff, 0x69, 0x40, 0x93, 0x1f, 0xd2, 0xb9, 0x75, 0x2f, 0x64, 0xf4, 0x77,
	0xf5, 0x42, 0x08, 0xcd, 0x4c, 0x1a, 0x54, 0x0e, 0xf1, 0xea, 0x4f, 0x08, 0x21, 0x86, 0xcb, 0x9d,
	0x95, 0x3b, 0x27, 0x07, 0x55, 0xe5, 0x42, 0xcb, 0x31, 0xa2, 0x1e, 0xb4, 0x1c, 0x7b, 0x10, 0x6b,
	0xa2, 0xdf, 0x67, 0xfa, 0xc3, 0xf5, 0x74, 0xa6, 0x94, 0x2a, 0x6c, 0xf0, 0x6b, 0x87, 0xb0, 0x25,
	0x95, 0x56, 0x0b, 0xaa, 0x2f, 0x77, 0x2c, 0xb1, 0x41, 0x70, 0xf3, 0xab, 0xc6, 0x8d, 0x4c, 0x73,
	0x8c, 0xba, 0xd0, 0xb2, 0x45, 0x1d, 0xe2, 0x83, 0x3b, 0xcb, 0xa4, 0x4c, 0x3a, 0xcc, 0xcd, 0xa4,
	0x3a, 0xe5, 0x89, 0x88, 0x26, 0x07, 0xec, 0xad, 0x09, 0x20, 0x8e, 0xeb, 0xed, 0x04, 0x65, 0x92,
	0x4e, 0x15, 0x0e, 0xf1, 0x37, 0x2b, 0x5a, 0x45, 0x3f, 0xc6, 0x3a, 0x59, 0x30, 0x02, 0x8c, 0x3c,
	0x5e, 0xf6, 0x83, 0x06, 0x27, 0xda, 0x47, 0xf5, 0xff, 0xa7, 0xb0, 0x1a, 0x6c, 0x74, 0x02, 0x91,
	0xc1, 0x2c, 0x9d, 0x62, 0xfe, 0x73, 0x82, 0x99, 0xc1, 0x98, 0xa6, 0x94, 0x88, 0x2d, 0x0e, 0xda,
	0x5b, 0xdf, 0x95, 0x68, 0x07, 0x36, 0x67, 0x72, 0x71, 0x9a, 0x24, 0x57, 0x14, 0xb9, 0x10, 0x1d,
	0x57, 0x7e, 0x74, 0x04, 0x82, 0xc0, 0xf3, 0x89, 0xd6, 0x39, 0x5e, 0xce, 0x29, 0x2e, 0x4b, 0xf1,
	0xca, 0x2b, 0x8b, 0x6d, 0x66, 0x1c, 0xc2, 0x6e, 0x3e, 0x37, 0xaf, 0x71, 0xe1, 0x5d, 0x30, 0xc0,
	0x5f, 0xe7, 0xa8, 0x62, 0x14, 0x21, 0xdd, 0x36, 0xa2, 0x3d, 0xe8, 0xd0, 0x50, 0x2f, 0xb5, 0x59,
	0x45, 0x7d, 0xc8, 0x51, 0x84, 0x5b, 0x6d, 0x65, 0x7a, 0xad, 0x2d, 0x9e, 0xb3, 0xa3, 0x22, 0xe6,
	0x7f, 0x0a, 0x1f, 0x49, 0x76, 0x58, 0x1f, 0x0d, 0xe7, 0x51, 0xce, 0x7f, 0x87, 0xdb, 0x40, 0x79,
	0x7a, 0xca, 0xd0, 0x09, 0x88, 0x5d, 0x06, 0x3f, 0x81, 0xfd, 0xcc, 0xd9, 0x77, 0xc4, 0x23, 0xad,
	0x54, 0xfd, 0x80, 0xaa, 0x76, 0x66, 0x6a, 0x30, 0x41, 0xec, 0x71, 0x13, 0x3e, 0x5e, 0xd3, 0x84,
	0x92, 0xfd, 0x3f, 0x07, 0x60, 0x33, 0x59, 0x69, 0xe7, 0xb9, 0xd8, 0x67, 0x37, 0x1d, 0xbe, 0xc3,
	0x4d, 0xcc, 0x89, 0x22, 0x00, 0x83, 0x37, 0x68, 0x0c, 0x22, 0x59, 0x4a, 0xb8, 0xa4, 0x8e, 0xff,
	0x0e, 0xe0, 0x41, 0x41, 0x1b, 0x65, 0x6e, 0x53, 0xae, 0x5c, 0x77, 0xa8, 0xd7, 0x4f, 0x00, 0xe6,
	0x0c, 0x5c, 0xa3, 0x19, 0xf3, 0x02, 0x74, 0x4e, 0x44, 0x55, 0x7f, 0xb4, 0xba, 0x8f, 0xbe, 0x80,
	0x9d, 0x9b, 0xa5, 0x4c, 0xb9, 0xb0, 0xda, 0x3a, 0x57, 0xad, 0xc6, 0xf9, 0x18, 0x5a, 0x45, 0x50,
	0x4e, 0xeb, 0x73, 0xc7, 0xe4, 0x8f, 0xff, 0x08, 0x60, 0xb7, 0x38, 0x5c, 0xa0, 0x8d, 0x27, 0x45,
	0x9a, 0x8f, 0xa0, 0x59, 0x38, 0x99, 0x93, 0x7c, 0xb7, 0x87, 0x7b, 0xfe, 0x35, 0xbf, 0x7d, 0xb5,
	0xf7, 0x6f, 0x5f, 0x79, 0xdb, 0xeb, 0xdc, 0xac, 0xaf, 0x21, 0x2c, 0x28, 0x57, 0xa4, 0xa9, 0x15,
	0x6d, 0x5d, 0xa5, 0x86, 0xe0, 0xae, 0x1a, 0xba, 0x7f, 0x05, 0xd0, 0xae, 0x7c, 0x0f, 0xb6, 0xa0,
	0x75, 0xd1, 0x1f, 0xa9, 0x57, 0x4a, 0xdf, 0xaa, 0xf0, 0x5e, 0xb4, 0x0f, 0x3b, 0x17, 0xfd, 0x1f,
	0x32, 0x54, 0x2f, 0x54, 0x82, 0xc9, 0x8f, 0xae, 0xbc, 0xa9, 0x56, 0x61, 0x40, 0xdb, 0x17, 0x96,
	0x2e, 0xd8, 0x73, 0x61, 0xcd, 0xa3, 0x03, 0xf6, 0xf5, 0x8a, 0x5b, 0xa7, 0x21, 0x77, 0x0a, 0xd4,
	0xbb, 0x3d, 0xbc, 0xef, 0x99, 0x3f, 0x49, 0x65, 0x4b, 0xaa, 0x0d, 0xcf, 0xf4, 0xe8, 0x92, 0xb9,
	0xd1, 0xbd, 0x86, 0xad, 0x6a, 0x13, 0xbc, 0x9c, 0xfb, 0xf9, 0x9f, 0x3c, 0x19, 0xfb, 0x4e, 0xc7,
	0x32, 0xfd, 0x1e, 0xed, 0xad, 0x36, 0xaf, 0x28, 0x4f, 0x41, 0x33, 0xf2, 0x17, 0xdf, 0xa4, 0x7a,
	0xfc, 0xf6, 0xa6, 0xd6, 0xed, 0x93, 0x4c, 0xd5, 0x8c, 0x1d, 0xfa, 0x47, 0xd1, 0x1f, 0xbc, 0x15,
	0xe5, 0x5e, 0x0c, 0xfc, 0xc7, 0x88, 0xa4, 0xfc, 0xf5, 0x73, 0x4c, 0x91, 0xd2, 0xa3, 0x62, 0xb7,
	0x61, 0xd3, 0x5d, 0x2f, 0xbf, 0xe2, 0x61, 0xbd, 0xfb, 0x25, 0x40, 0xc9, 0x7e, 0x6d, 0x68, 0x8e,
	0xae, 0xcf, 0x0d, 0xd2, 0x99, 0x82, 0xf9, 0xe4, 0x6f, 0x29, 0x94, 0x4f, 0x5e, 0x29, 0xac, 0x9f,
	0x7d, 0xf6, 0xe6, 0x59, 0x0d, 0xee, 0xbd, 0x79, 0x56, 0x8f, 0x82, 0x33, 0xfa, 0x29, 0x02, 0x38,
	0x88, 0xf5, 0xac, 0x37, 0x76, 0x13, 0x9b, 0x90, 0x76, 0x65, 0x76, 0x7f, 0x06, 0xc1, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc0, 0xc6, 0xee, 0x92, 0xd0, 0x06, 0x00, 0x00,
}
