// Code generated by protoc-gen-go.
// source: Feed.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FeedPostType int32

const (
	FeedPostType_FPUnknown           FeedPostType = 0
	FeedPostType_FPOpenEndedQuestion FeedPostType = 1
	FeedPostType_FPOpenEndedReply    FeedPostType = 2
	FeedPostType_FPSurveyQuestion    FeedPostType = 3
	FeedPostType_FPSurveyAnswer      FeedPostType = 4
)

var FeedPostType_name = map[int32]string{
	0: "FPUnknown",
	1: "FPOpenEndedQuestion",
	2: "FPOpenEndedReply",
	3: "FPSurveyQuestion",
	4: "FPSurveyAnswer",
}
var FeedPostType_value = map[string]int32{
	"FPUnknown":           0,
	"FPOpenEndedQuestion": 1,
	"FPOpenEndedReply":    2,
	"FPSurveyQuestion":    3,
	"FPSurveyAnswer":      4,
}

func (x FeedPostType) Enum() *FeedPostType {
	p := new(FeedPostType)
	*p = x
	return p
}
func (x FeedPostType) String() string {
	return proto.EnumName(FeedPostType_name, int32(x))
}
func (x *FeedPostType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostType_value, data, "FeedPostType")
	if err != nil {
		return err
	}
	*x = FeedPostType(value)
	return nil
}
func (FeedPostType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type FeedPostScope int32

const (
	FeedPostScope_FPScopeUnknown       FeedPostScope = 0
	FeedPostScope_FPScopeLocalNetwork  FeedPostScope = 1
	FeedPostScope_FPScopeGlobalNetwork FeedPostScope = 2
)

var FeedPostScope_name = map[int32]string{
	0: "FPScopeUnknown",
	1: "FPScopeLocalNetwork",
	2: "FPScopeGlobalNetwork",
}
var FeedPostScope_value = map[string]int32{
	"FPScopeUnknown":       0,
	"FPScopeLocalNetwork":  1,
	"FPScopeGlobalNetwork": 2,
}

func (x FeedPostScope) Enum() *FeedPostScope {
	p := new(FeedPostScope)
	*p = x
	return p
}
func (x FeedPostScope) String() string {
	return proto.EnumName(FeedPostScope_name, int32(x))
}
func (x *FeedPostScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostScope_value, data, "FeedPostScope")
	if err != nil {
		return err
	}
	*x = FeedPostScope(value)
	return nil
}
func (FeedPostScope) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type FeedPostStatus int32

const (
	FeedPostStatus_FPSUnknown FeedPostStatus = 0
	FeedPostStatus_FPSActive  FeedPostStatus = 1
	FeedPostStatus_FPSDeleted FeedPostStatus = 2
)

var FeedPostStatus_name = map[int32]string{
	0: "FPSUnknown",
	1: "FPSActive",
	2: "FPSDeleted",
}
var FeedPostStatus_value = map[string]int32{
	"FPSUnknown": 0,
	"FPSActive":  1,
	"FPSDeleted": 2,
}

func (x FeedPostStatus) Enum() *FeedPostStatus {
	p := new(FeedPostStatus)
	*p = x
	return p
}
func (x FeedPostStatus) String() string {
	return proto.EnumName(FeedPostStatus_name, int32(x))
}
func (x *FeedPostStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedPostStatus_value, data, "FeedPostStatus")
	if err != nil {
		return err
	}
	*x = FeedPostStatus(value)
	return nil
}
func (FeedPostStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type UpdateVerb int32

const (
	UpdateVerb_UVCreate UpdateVerb = 1
	UpdateVerb_UVUpdate UpdateVerb = 2
	UpdateVerb_UVDelete UpdateVerb = 3
)

var UpdateVerb_name = map[int32]string{
	1: "UVCreate",
	2: "UVUpdate",
	3: "UVDelete",
}
var UpdateVerb_value = map[string]int32{
	"UVCreate": 1,
	"UVUpdate": 2,
	"UVDelete": 3,
}

func (x UpdateVerb) Enum() *UpdateVerb {
	p := new(UpdateVerb)
	*p = x
	return p
}
func (x UpdateVerb) String() string {
	return proto.EnumName(UpdateVerb_name, int32(x))
}
func (x *UpdateVerb) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpdateVerb_value, data, "UpdateVerb")
	if err != nil {
		return err
	}
	*x = UpdateVerb(value)
	return nil
}
func (UpdateVerb) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

type FeedPost struct {
	PostID                   *string        `protobuf:"bytes,1,opt,name=postID" json:"postID,omitempty"`
	ParentID                 *string        `protobuf:"bytes,2,opt,name=parentID" json:"parentID,omitempty"`
	PostType                 *FeedPostType  `protobuf:"varint,3,opt,name=postType,enum=BlitzMessage.FeedPostType" json:"postType,omitempty"`
	PostScope                *FeedPostScope `protobuf:"varint,4,opt,name=postScope,enum=BlitzMessage.FeedPostScope" json:"postScope,omitempty"`
	UserID                   *string        `protobuf:"bytes,5,opt,name=userID" json:"userID,omitempty"`
	AnonymousPost            *bool          `protobuf:"varint,6,opt,name=anonymousPost,def=0" json:"anonymousPost,omitempty"`
	Timestamp                *Timestamp     `protobuf:"bytes,7,opt,name=timestamp" json:"timestamp,omitempty"`
	TimespanActive           *Timespan      `protobuf:"bytes,8,opt,name=timespanActive" json:"timespanActive,omitempty"`
	HeadlineText             *string        `protobuf:"bytes,9,opt,name=headlineText" json:"headlineText,omitempty"`
	BodyText                 *string        `protobuf:"bytes,10,opt,name=bodyText" json:"bodyText,omitempty"`
	PostTags                 []*EntityTag   `protobuf:"bytes,12,rep,name=postTags" json:"postTags,omitempty"`
	Replies                  []*FeedPost    `protobuf:"bytes,13,rep,name=replies" json:"replies,omitempty"`
	MayAddReply              *bool          `protobuf:"varint,14,opt,name=mayAddReply" json:"mayAddReply,omitempty"`
	MayChooseMulitpleReplies *bool          `protobuf:"varint,15,opt,name=mayChooseMulitpleReplies" json:"mayChooseMulitpleReplies,omitempty"`
	SurveyAnswerSequence     *int32         `protobuf:"varint,16,opt,name=surveyAnswerSequence" json:"surveyAnswerSequence,omitempty"`
	AreMoreReplies           *bool          `protobuf:"varint,17,opt,name=areMoreReplies" json:"areMoreReplies,omitempty"`
	XXX_unrecognized         []byte         `json:"-"`
}

func (m *FeedPost) Reset()                    { *m = FeedPost{} }
func (m *FeedPost) String() string            { return proto.CompactTextString(m) }
func (*FeedPost) ProtoMessage()               {}
func (*FeedPost) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

const Default_FeedPost_AnonymousPost bool = false

func (m *FeedPost) GetPostID() string {
	if m != nil && m.PostID != nil {
		return *m.PostID
	}
	return ""
}

func (m *FeedPost) GetParentID() string {
	if m != nil && m.ParentID != nil {
		return *m.ParentID
	}
	return ""
}

func (m *FeedPost) GetPostType() FeedPostType {
	if m != nil && m.PostType != nil {
		return *m.PostType
	}
	return FeedPostType_FPUnknown
}

func (m *FeedPost) GetPostScope() FeedPostScope {
	if m != nil && m.PostScope != nil {
		return *m.PostScope
	}
	return FeedPostScope_FPScopeUnknown
}

func (m *FeedPost) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *FeedPost) GetAnonymousPost() bool {
	if m != nil && m.AnonymousPost != nil {
		return *m.AnonymousPost
	}
	return Default_FeedPost_AnonymousPost
}

func (m *FeedPost) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *FeedPost) GetTimespanActive() *Timespan {
	if m != nil {
		return m.TimespanActive
	}
	return nil
}

func (m *FeedPost) GetHeadlineText() string {
	if m != nil && m.HeadlineText != nil {
		return *m.HeadlineText
	}
	return ""
}

func (m *FeedPost) GetBodyText() string {
	if m != nil && m.BodyText != nil {
		return *m.BodyText
	}
	return ""
}

func (m *FeedPost) GetPostTags() []*EntityTag {
	if m != nil {
		return m.PostTags
	}
	return nil
}

func (m *FeedPost) GetReplies() []*FeedPost {
	if m != nil {
		return m.Replies
	}
	return nil
}

func (m *FeedPost) GetMayAddReply() bool {
	if m != nil && m.MayAddReply != nil {
		return *m.MayAddReply
	}
	return false
}

func (m *FeedPost) GetMayChooseMulitpleReplies() bool {
	if m != nil && m.MayChooseMulitpleReplies != nil {
		return *m.MayChooseMulitpleReplies
	}
	return false
}

func (m *FeedPost) GetSurveyAnswerSequence() int32 {
	if m != nil && m.SurveyAnswerSequence != nil {
		return *m.SurveyAnswerSequence
	}
	return 0
}

func (m *FeedPost) GetAreMoreReplies() bool {
	if m != nil && m.AreMoreReplies != nil {
		return *m.AreMoreReplies
	}
	return false
}

type FeedPostUpdateRequest struct {
	UpdateVerb       *UpdateVerb `protobuf:"varint,1,opt,name=updateVerb,enum=BlitzMessage.UpdateVerb" json:"updateVerb,omitempty"`
	FeedPost         *FeedPost   `protobuf:"bytes,2,opt,name=feedPost" json:"feedPost,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FeedPostUpdateRequest) Reset()                    { *m = FeedPostUpdateRequest{} }
func (m *FeedPostUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedPostUpdateRequest) ProtoMessage()               {}
func (*FeedPostUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *FeedPostUpdateRequest) GetUpdateVerb() UpdateVerb {
	if m != nil && m.UpdateVerb != nil {
		return *m.UpdateVerb
	}
	return UpdateVerb_UVCreate
}

func (m *FeedPostUpdateRequest) GetFeedPost() *FeedPost {
	if m != nil {
		return m.FeedPost
	}
	return nil
}

type FeedPostUpdateResponse struct {
	FeedPost         *FeedPost `protobuf:"bytes,1,opt,name=feedPost" json:"feedPost,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *FeedPostUpdateResponse) Reset()                    { *m = FeedPostUpdateResponse{} }
func (m *FeedPostUpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedPostUpdateResponse) ProtoMessage()               {}
func (*FeedPostUpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *FeedPostUpdateResponse) GetFeedPost() *FeedPost {
	if m != nil {
		return m.FeedPost
	}
	return nil
}

type FeedPostFetchRequest struct {
	Timespan         *Timespan      `protobuf:"bytes,1,opt,name=timespan" json:"timespan,omitempty"`
	FeedScope        *FeedPostScope `protobuf:"varint,2,opt,name=feedScope,enum=BlitzMessage.FeedPostScope" json:"feedScope,omitempty"`
	ParentID         *string        `protobuf:"bytes,3,opt,name=parentID" json:"parentID,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *FeedPostFetchRequest) Reset()                    { *m = FeedPostFetchRequest{} }
func (m *FeedPostFetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FeedPostFetchRequest) ProtoMessage()               {}
func (*FeedPostFetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *FeedPostFetchRequest) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *FeedPostFetchRequest) GetFeedScope() FeedPostScope {
	if m != nil && m.FeedScope != nil {
		return *m.FeedScope
	}
	return FeedPostScope_FPScopeUnknown
}

func (m *FeedPostFetchRequest) GetParentID() string {
	if m != nil && m.ParentID != nil {
		return *m.ParentID
	}
	return ""
}

type FeedPostFetchResponse struct {
	FeedPosts        []*FeedPost `protobuf:"bytes,1,rep,name=feedPosts" json:"feedPosts,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FeedPostFetchResponse) Reset()                    { *m = FeedPostFetchResponse{} }
func (m *FeedPostFetchResponse) String() string            { return proto.CompactTextString(m) }
func (*FeedPostFetchResponse) ProtoMessage()               {}
func (*FeedPostFetchResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *FeedPostFetchResponse) GetFeedPosts() []*FeedPost {
	if m != nil {
		return m.FeedPosts
	}
	return nil
}

func init() {
	proto.RegisterType((*FeedPost)(nil), "BlitzMessage.FeedPost")
	proto.RegisterType((*FeedPostUpdateRequest)(nil), "BlitzMessage.FeedPostUpdateRequest")
	proto.RegisterType((*FeedPostUpdateResponse)(nil), "BlitzMessage.FeedPostUpdateResponse")
	proto.RegisterType((*FeedPostFetchRequest)(nil), "BlitzMessage.FeedPostFetchRequest")
	proto.RegisterType((*FeedPostFetchResponse)(nil), "BlitzMessage.FeedPostFetchResponse")
	proto.RegisterEnum("BlitzMessage.FeedPostType", FeedPostType_name, FeedPostType_value)
	proto.RegisterEnum("BlitzMessage.FeedPostScope", FeedPostScope_name, FeedPostScope_value)
	proto.RegisterEnum("BlitzMessage.FeedPostStatus", FeedPostStatus_name, FeedPostStatus_value)
	proto.RegisterEnum("BlitzMessage.UpdateVerb", UpdateVerb_name, UpdateVerb_value)
}

var fileDescriptor2 = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0x4f, 0x53, 0x1a, 0x4f,
	0x10, 0x75, 0xc1, 0x3f, 0xd0, 0x02, 0xbf, 0xfd, 0x8d, 0x8a, 0x53, 0xe8, 0xc1, 0xf2, 0x12, 0xa5,
	0x0c, 0xa9, 0xf2, 0x90, 0x43, 0x0e, 0xa6, 0x44, 0x25, 0x95, 0xaa, 0x98, 0x18, 0x01, 0xef, 0xcb,
	0x6e, 0x2b, 0x1b, 0x97, 0x99, 0xcd, 0xce, 0xa0, 0x21, 0xc7, 0x9c, 0xf2, 0xf9, 0xfc, 0x3e, 0xa9,
	0x4a, 0xcf, 0x2c, 0x8b, 0x60, 0x88, 0x39, 0xed, 0xce, 0xeb, 0xd7, 0xaf, 0xff, 0xcc, 0x1b, 0x80,
	0x16, 0x62, 0xd0, 0x88, 0x13, 0xa9, 0x25, 0x2b, 0x35, 0xa3, 0x50, 0x7f, 0x3f, 0x47, 0xa5, 0xbc,
	0x1b, 0xac, 0x6d, 0xc9, 0xde, 0x17, 0xf4, 0x75, 0x78, 0x87, 0xfe, 0xcb, 0x00, 0x95, 0x9f, 0x84,
	0xb1, 0x96, 0x49, 0x4a, 0xad, 0xad, 0x76, 0x46, 0x31, 0xaa, 0xf1, 0xc1, 0x3d, 0x13, 0x3a, 0xd4,
	0xa3, 0x8e, 0x77, 0x33, 0x46, 0x76, 0x7f, 0xe5, 0xa1, 0x60, 0x84, 0x2f, 0xa4, 0xd2, 0xac, 0x02,
	0xcb, 0x31, 0x7d, 0xdf, 0x9f, 0x72, 0x67, 0xc7, 0xd9, 0x2b, 0x32, 0x17, 0x0a, 0xb1, 0x97, 0xa0,
	0x30, 0x48, 0xce, 0x22, 0x07, 0x84, 0x10, 0xc3, 0x68, 0xf2, 0x3c, 0x21, 0x95, 0xc3, 0x5a, 0x63,
	0xba, 0x97, 0x46, 0xa6, 0x65, 0x18, 0xac, 0x01, 0x45, 0xc3, 0x6e, 0xfb, 0x92, 0xe8, 0x8b, 0x96,
	0xbe, 0x35, 0x9f, 0x6e, 0x29, 0xa6, 0xfe, 0x50, 0x61, 0x42, 0xd5, 0x96, 0x6c, 0xb5, 0x6d, 0x28,
	0x7b, 0x42, 0x8a, 0xd1, 0x40, 0x0e, 0x95, 0x61, 0xf1, 0x65, 0x82, 0x0b, 0x6f, 0x96, 0xae, 0xbd,
	0x48, 0x21, 0xab, 0x43, 0x51, 0x87, 0x03, 0x54, 0xda, 0x1b, 0xc4, 0x7c, 0x85, 0x22, 0xab, 0x87,
	0x9b, 0xb3, 0xea, 0x9d, 0x2c, 0x4c, 0x9d, 0x54, 0x2c, 0x37, 0xf6, 0xc4, 0xb1, 0xdd, 0x14, 0x2f,
	0xd8, 0x84, 0xea, 0x9c, 0x04, 0xe2, 0xb0, 0x75, 0x28, 0xf5, 0xd1, 0x0b, 0xa2, 0x50, 0x60, 0x07,
	0xbf, 0x69, 0x5e, 0xcc, 0xf6, 0xd1, 0x93, 0xc1, 0xc8, 0x22, 0x60, 0x91, 0xfd, 0xf1, 0x3e, 0x68,
	0xa1, 0xbc, 0xb4, 0x93, 0xff, 0xb3, 0x85, 0xc9, 0xc2, 0xd9, 0x0b, 0x58, 0x49, 0x30, 0x8e, 0x42,
	0x54, 0xbc, 0x6c, 0x99, 0xd5, 0xf9, 0xab, 0x60, 0x6b, 0xb0, 0x3a, 0xf0, 0x46, 0xc7, 0x41, 0x70,
	0x49, 0xf4, 0x11, 0xaf, 0x98, 0x99, 0xd9, 0x0e, 0x70, 0x02, 0x4f, 0xfa, 0x52, 0x2a, 0x3c, 0x1f,
	0x52, 0x5e, 0x1c, 0xe1, 0xe5, 0x58, 0xee, 0x3f, 0xcb, 0xd8, 0x86, 0x75, 0x35, 0x4c, 0xee, 0x70,
	0x74, 0x2c, 0xd4, 0x3d, 0x26, 0x6d, 0xfc, 0x3a, 0x44, 0xe1, 0x23, 0x77, 0x29, 0xba, 0xc4, 0xaa,
	0x50, 0xa1, 0x9b, 0x3c, 0x97, 0xc9, 0x24, 0xeb, 0x7f, 0x93, 0xb5, 0x2b, 0x61, 0x23, 0x2b, 0xdc,
	0x8d, 0x03, 0x4f, 0x53, 0x98, 0xf2, 0xa8, 0x8b, 0x03, 0x80, 0xa1, 0x05, 0xae, 0x30, 0xe9, 0x59,
	0x3f, 0x54, 0x0e, 0xf9, 0x6c, 0xc7, 0xdd, 0x49, 0x9c, 0xed, 0x41, 0xe1, 0x7a, 0x2c, 0x63, 0x9d,
	0xf2, 0xd7, 0xe9, 0x76, 0x9b, 0x50, 0x7d, 0x5a, 0x50, 0xc5, 0x52, 0xd0, 0x7d, 0x4e, 0x6b, 0x38,
	0xcf, 0x6a, 0xfc, 0x70, 0x60, 0x3d, 0x3b, 0xb4, 0x50, 0xfb, 0xfd, 0xac, 0x69, 0x92, 0xc8, 0xae,
	0x79, 0xbe, 0xc4, 0xe4, 0x82, 0xc9, 0x9a, 0xa6, 0x58, 0x6a, 0xcd, 0xdc, 0xbf, 0xad, 0x39, 0xfd,
	0x14, 0x8c, 0xf1, 0x8b, 0x34, 0xc8, 0xc6, 0x93, 0x1e, 0xc6, 0x73, 0xec, 0xa7, 0xd2, 0x26, 0xa0,
	0xa8, 0x8b, 0x67, 0xae, 0xba, 0x7e, 0x07, 0xa5, 0x99, 0x07, 0x53, 0x86, 0x62, 0xeb, 0xa2, 0x2b,
	0x6e, 0x85, 0xbc, 0x17, 0xee, 0x02, 0xdb, 0x84, 0xb5, 0xd6, 0xc5, 0xa7, 0x18, 0xc5, 0x99, 0x08,
	0x30, 0xf8, 0x6c, 0x46, 0x0c, 0xa5, 0x70, 0x1d, 0xb2, 0xa7, 0x3b, 0x15, 0xb0, 0x3e, 0x71, 0x73,
	0x29, 0xda, 0xb6, 0x1e, 0x98, 0x70, 0xf3, 0x8c, 0x41, 0x25, 0x43, 0x53, 0x67, 0xb8, 0x8b, 0xf5,
	0x2b, 0x28, 0xcf, 0x8e, 0x97, 0x92, 0xcc, 0xef, 0x93, 0xea, 0x16, 0xfb, 0x20, 0x7d, 0x2f, 0xfa,
	0x88, 0xfa, 0x5e, 0x26, 0xb7, 0x54, 0x9d, 0xd3, 0xf6, 0xd3, 0xc0, 0xbb, 0x48, 0xf6, 0x1e, 0x23,
	0xb9, 0xfa, 0x5b, 0x92, 0xc9, 0x74, 0xb5, 0xa7, 0x87, 0x8a, 0x9e, 0x34, 0x10, 0xf7, 0x51, 0xd4,
	0x4e, 0xd8, 0x4e, 0xdf, 0x20, 0x49, 0xa5, 0xe1, 0x53, 0x8c, 0x50, 0x63, 0x40, 0x02, 0xaf, 0x01,
	0xa6, 0x5c, 0x55, 0x82, 0x42, 0xf7, 0xea, 0x24, 0x41, 0x3a, 0x13, 0xd7, 0x9e, 0xd2, 0x28, 0x0d,
	0x6b, 0x4f, 0x69, 0xa2, 0x9b, 0x6f, 0xbe, 0x7a, 0x38, 0xca, 0xc1, 0xc2, 0xc3, 0x51, 0x9e, 0x39,
	0x4d, 0xfa, 0xe5, 0x0e, 0xd4, 0x7c, 0x39, 0x68, 0xf4, 0xcc, 0xd6, 0xfb, 0x98, 0xe0, 0xcc, 0xfe,
	0x7f, 0x3a, 0xce, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x61, 0x30, 0x95, 0x4e, 0x05, 0x00,
	0x00,
}
