// Code generated by protoc-gen-go.
// source: Payments.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CardStatus int32

const (
	CardStatus_CSUnknown  CardStatus = 0
	CardStatus_CSStandard CardStatus = 1
	CardStatus_CSDeleted  CardStatus = 2
)

var CardStatus_name = map[int32]string{
	0: "CSUnknown",
	1: "CSStandard",
	2: "CSDeleted",
}
var CardStatus_value = map[string]int32{
	"CSUnknown":  0,
	"CSStandard": 1,
	"CSDeleted":  2,
}

func (x CardStatus) Enum() *CardStatus {
	p := new(CardStatus)
	*p = x
	return p
}
func (x CardStatus) String() string {
	return proto.EnumName(CardStatus_name, int32(x))
}
func (x *CardStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CardStatus_value, data, "CardStatus")
	if err != nil {
		return err
	}
	*x = CardStatus(value)
	return nil
}
func (CardStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type ChargeTokenType int32

const (
	ChargeTokenType_CTTApplePay    ChargeTokenType = 0
	ChargeTokenType_CTTStripeToken ChargeTokenType = 1
	ChargeTokenType_CTTCardToken   ChargeTokenType = 2
)

var ChargeTokenType_name = map[int32]string{
	0: "CTTApplePay",
	1: "CTTStripeToken",
	2: "CTTCardToken",
}
var ChargeTokenType_value = map[string]int32{
	"CTTApplePay":    0,
	"CTTStripeToken": 1,
	"CTTCardToken":   2,
}

func (x ChargeTokenType) Enum() *ChargeTokenType {
	p := new(ChargeTokenType)
	*p = x
	return p
}
func (x ChargeTokenType) String() string {
	return proto.EnumName(ChargeTokenType_name, int32(x))
}
func (x *ChargeTokenType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChargeTokenType_value, data, "ChargeTokenType")
	if err != nil {
		return err
	}
	*x = ChargeTokenType(value)
	return nil
}
func (ChargeTokenType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type ChargeStatus int32

const (
	ChargeStatus_CSChargeUnknown ChargeStatus = 0
	ChargeStatus_CSChargeRequest ChargeStatus = 1
	ChargeStatus_CSDeclined      ChargeStatus = 2
	ChargeStatus_CSPreauthorized ChargeStatus = 3
	ChargeStatus_CSCharged       ChargeStatus = 4
)

var ChargeStatus_name = map[int32]string{
	0: "CSChargeUnknown",
	1: "CSChargeRequest",
	2: "CSDeclined",
	3: "CSPreauthorized",
	4: "CSCharged",
}
var ChargeStatus_value = map[string]int32{
	"CSChargeUnknown": 0,
	"CSChargeRequest": 1,
	"CSDeclined":      2,
	"CSPreauthorized": 3,
	"CSCharged":       4,
}

func (x ChargeStatus) Enum() *ChargeStatus {
	p := new(ChargeStatus)
	*p = x
	return p
}
func (x ChargeStatus) String() string {
	return proto.EnumName(ChargeStatus_name, int32(x))
}
func (x *ChargeStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChargeStatus_value, data, "ChargeStatus")
	if err != nil {
		return err
	}
	*x = ChargeStatus(value)
	return nil
}
func (ChargeStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type CardInfo struct {
	CardStatus       *CardStatus `protobuf:"varint,1,opt,name=cardStatus,enum=BlitzMessage.CardStatus" json:"cardStatus,omitempty"`
	CardHolderName   *string     `protobuf:"bytes,2,opt,name=cardHolderName" json:"cardHolderName,omitempty"`
	MemoText         *string     `protobuf:"bytes,3,opt,name=memoText" json:"memoText,omitempty"`
	Brand            *string     `protobuf:"bytes,4,opt,name=brand" json:"brand,omitempty"`
	Last4            *string     `protobuf:"bytes,5,opt,name=last4" json:"last4,omitempty"`
	ExpireMonth      *int32      `protobuf:"varint,6,opt,name=expireMonth" json:"expireMonth,omitempty"`
	ExpireYear       *int32      `protobuf:"varint,7,opt,name=expireYear" json:"expireYear,omitempty"`
	Token            *string     `protobuf:"bytes,8,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CardInfo) Reset()                    { *m = CardInfo{} }
func (m *CardInfo) String() string            { return proto.CompactTextString(m) }
func (*CardInfo) ProtoMessage()               {}
func (*CardInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *CardInfo) GetCardStatus() CardStatus {
	if m != nil && m.CardStatus != nil {
		return *m.CardStatus
	}
	return CardStatus_CSUnknown
}

func (m *CardInfo) GetCardHolderName() string {
	if m != nil && m.CardHolderName != nil {
		return *m.CardHolderName
	}
	return ""
}

func (m *CardInfo) GetMemoText() string {
	if m != nil && m.MemoText != nil {
		return *m.MemoText
	}
	return ""
}

func (m *CardInfo) GetBrand() string {
	if m != nil && m.Brand != nil {
		return *m.Brand
	}
	return ""
}

func (m *CardInfo) GetLast4() string {
	if m != nil && m.Last4 != nil {
		return *m.Last4
	}
	return ""
}

func (m *CardInfo) GetExpireMonth() int32 {
	if m != nil && m.ExpireMonth != nil {
		return *m.ExpireMonth
	}
	return 0
}

func (m *CardInfo) GetExpireYear() int32 {
	if m != nil && m.ExpireYear != nil {
		return *m.ExpireYear
	}
	return 0
}

func (m *CardInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type UserCardInfo struct {
	UserID           *string     `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	CardInfo         []*CardInfo `protobuf:"bytes,2,rep,name=cardInfo" json:"cardInfo,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UserCardInfo) Reset()                    { *m = UserCardInfo{} }
func (m *UserCardInfo) String() string            { return proto.CompactTextString(m) }
func (*UserCardInfo) ProtoMessage()               {}
func (*UserCardInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *UserCardInfo) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *UserCardInfo) GetCardInfo() []*CardInfo {
	if m != nil {
		return m.CardInfo
	}
	return nil
}

type Charge struct {
	ChargeID         *string          `protobuf:"bytes,1,opt,name=chargeID" json:"chargeID,omitempty"`
	Timestamp        *Timestamp       `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	ChargeStatus     *ChargeStatus    `protobuf:"varint,3,opt,name=chargeStatus,enum=BlitzMessage.ChargeStatus" json:"chargeStatus,omitempty"`
	PayerID          *string          `protobuf:"bytes,4,opt,name=payerID" json:"payerID,omitempty"`
	PayeeID          *string          `protobuf:"bytes,5,opt,name=payeeID" json:"payeeID,omitempty"`
	ConversationID   *string          `protobuf:"bytes,6,opt,name=conversationID" json:"conversationID,omitempty"`
	MemoText         *string          `protobuf:"bytes,7,opt,name=memoText" json:"memoText,omitempty"`
	Amount           *string          `protobuf:"bytes,8,opt,name=amount" json:"amount,omitempty"`
	Currency         *string          `protobuf:"bytes,9,opt,name=currency" json:"currency,omitempty"`
	TokenType        *ChargeTokenType `protobuf:"varint,10,opt,name=tokenType,enum=BlitzMessage.ChargeTokenType" json:"tokenType,omitempty"`
	ChargeToken      *string          `protobuf:"bytes,11,opt,name=chargeToken" json:"chargeToken,omitempty"`
	ProcessorReason  *string          `protobuf:"bytes,12,opt,name=processorReason" json:"processorReason,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Charge) Reset()                    { *m = Charge{} }
func (m *Charge) String() string            { return proto.CompactTextString(m) }
func (*Charge) ProtoMessage()               {}
func (*Charge) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Charge) GetChargeID() string {
	if m != nil && m.ChargeID != nil {
		return *m.ChargeID
	}
	return ""
}

func (m *Charge) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Charge) GetChargeStatus() ChargeStatus {
	if m != nil && m.ChargeStatus != nil {
		return *m.ChargeStatus
	}
	return ChargeStatus_CSChargeUnknown
}

func (m *Charge) GetPayerID() string {
	if m != nil && m.PayerID != nil {
		return *m.PayerID
	}
	return ""
}

func (m *Charge) GetPayeeID() string {
	if m != nil && m.PayeeID != nil {
		return *m.PayeeID
	}
	return ""
}

func (m *Charge) GetConversationID() string {
	if m != nil && m.ConversationID != nil {
		return *m.ConversationID
	}
	return ""
}

func (m *Charge) GetMemoText() string {
	if m != nil && m.MemoText != nil {
		return *m.MemoText
	}
	return ""
}

func (m *Charge) GetAmount() string {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return ""
}

func (m *Charge) GetCurrency() string {
	if m != nil && m.Currency != nil {
		return *m.Currency
	}
	return ""
}

func (m *Charge) GetTokenType() ChargeTokenType {
	if m != nil && m.TokenType != nil {
		return *m.TokenType
	}
	return ChargeTokenType_CTTApplePay
}

func (m *Charge) GetChargeToken() string {
	if m != nil && m.ChargeToken != nil {
		return *m.ChargeToken
	}
	return ""
}

func (m *Charge) GetProcessorReason() string {
	if m != nil && m.ProcessorReason != nil {
		return *m.ProcessorReason
	}
	return ""
}

func init() {
	proto.RegisterType((*CardInfo)(nil), "BlitzMessage.CardInfo")
	proto.RegisterType((*UserCardInfo)(nil), "BlitzMessage.UserCardInfo")
	proto.RegisterType((*Charge)(nil), "BlitzMessage.Charge")
	proto.RegisterEnum("BlitzMessage.CardStatus", CardStatus_name, CardStatus_value)
	proto.RegisterEnum("BlitzMessage.ChargeTokenType", ChargeTokenType_name, ChargeTokenType_value)
	proto.RegisterEnum("BlitzMessage.ChargeStatus", ChargeStatus_name, ChargeStatus_value)
}

var fileDescriptor3 = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4e, 0xdb, 0x40,
	0x10, 0xc6, 0x71, 0x02, 0x21, 0x19, 0x87, 0xc4, 0x32, 0x12, 0xac, 0x52, 0x55, 0xaa, 0x38, 0xa1,
	0xa8, 0x4d, 0x11, 0xea, 0xa9, 0x07, 0xa4, 0x62, 0x0e, 0xe1, 0x40, 0x85, 0x88, 0x39, 0xf4, 0xb8,
	0xb1, 0xa7, 0xc4, 0xc5, 0xde, 0x75, 0xd7, 0x6b, 0x4a, 0x78, 0x82, 0x3e, 0x52, 0x9f, 0xa0, 0x0f,
	0xc0, 0x13, 0x75, 0x76, 0x37, 0x09, 0x01, 0x7a, 0xdb, 0xfd, 0xcd, 0x9f, 0xfd, 0xe6, 0xdb, 0x81,
	0xde, 0x25, 0x9f, 0x17, 0x28, 0x74, 0x35, 0x2a, 0x95, 0xd4, 0x32, 0xec, 0x9e, 0xe6, 0x99, 0x7e,
	0xb8, 0xc0, 0xaa, 0xe2, 0x37, 0x38, 0x78, 0x23, 0xa7, 0x3f, 0x30, 0xd1, 0xd9, 0x1d, 0x26, 0x1f,
	0x52, 0xac, 0x12, 0x95, 0x95, 0x5a, 0x2a, 0x97, 0x3a, 0xf0, 0xe3, 0x79, 0x89, 0x8b, 0xba, 0x83,
	0x3f, 0x1e, 0xb4, 0x23, 0xae, 0xd2, 0x73, 0xf1, 0x5d, 0x86, 0xef, 0x01, 0x12, 0x3a, 0x4f, 0x34,
	0xd7, 0x75, 0xc5, 0xbc, 0x77, 0xde, 0x61, 0xef, 0x98, 0x8d, 0xd6, 0x3b, 0x8f, 0xa2, 0x55, 0x3c,
	0xdc, 0x83, 0x9e, 0xc9, 0x1e, 0xcb, 0x3c, 0x45, 0xf5, 0x95, 0x17, 0xc8, 0x1a, 0x54, 0xd1, 0x09,
	0x03, 0x68, 0x17, 0x58, 0xc8, 0x18, 0xef, 0x35, 0x6b, 0x5a, 0xb2, 0x03, 0x5b, 0x53, 0xc5, 0x45,
	0xca, 0x36, 0x97, 0xd7, 0x9c, 0x57, 0xfa, 0x13, 0xdb, 0xb2, 0xd7, 0x5d, 0xf0, 0xf1, 0xbe, 0xcc,
	0x14, 0x5e, 0x48, 0xa1, 0x67, 0xac, 0x45, 0x70, 0x2b, 0x0c, 0x01, 0x1c, 0xfc, 0x86, 0x5c, 0xb1,
	0x6d, 0xcb, 0xa8, 0x4e, 0xcb, 0x5b, 0x14, 0xac, 0x6d, 0xea, 0x0e, 0xc6, 0xd0, 0xbd, 0xae, 0x50,
	0xad, 0xd4, 0xf7, 0xa0, 0x55, 0xd3, 0xfd, 0xfc, 0xcc, 0x2a, 0xef, 0x84, 0x87, 0xd0, 0x4e, 0x16,
	0x31, 0x52, 0xd6, 0x3c, 0xf4, 0x8f, 0xf7, 0x5e, 0xcf, 0x62, 0xa2, 0x07, 0x7f, 0x1b, 0xd0, 0x8a,
	0x66, 0x5c, 0xdd, 0xa0, 0x11, 0x9f, 0xd8, 0xd3, 0xaa, 0xcd, 0x10, 0x3a, 0x3a, 0x2b, 0xb0, 0xd2,
	0xbc, 0x28, 0xed, 0x84, 0xfe, 0xf1, 0xfe, 0xf3, 0x3e, 0xf1, 0x32, 0x1c, 0x1e, 0x41, 0xd7, 0x55,
	0x2f, 0x2c, 0x6c, 0x5a, 0x0b, 0x07, 0x2f, 0x9e, 0x5d, 0xcb, 0x08, 0xfb, 0xb0, 0x5d, 0xf2, 0xb9,
	0x55, 0xed, 0xcc, 0x59, 0x00, 0xf3, 0xbe, 0xb3, 0xc7, 0xd8, 0x2c, 0xc5, 0x1d, 0xaa, 0x8a, 0xeb,
	0x4c, 0x0a, 0xe2, 0xad, 0x57, 0x36, 0x6f, 0x5b, 0x42, 0x06, 0xf0, 0x42, 0xd6, 0x42, 0x3b, 0x83,
	0xec, 0x2c, 0xb5, 0x52, 0x28, 0x92, 0x39, 0xeb, 0x58, 0x72, 0x44, 0xb3, 0x18, 0x07, 0xcd, 0x06,
	0x30, 0xb0, 0xe2, 0xde, 0xfe, 0x4f, 0x5c, 0xbc, 0x4c, 0x32, 0x9f, 0x93, 0x3c, 0x21, 0xe6, 0xdb,
	0x36, 0xfb, 0xd0, 0xa7, 0xed, 0x49, 0xa8, 0x44, 0xaa, 0x2b, 0xe4, 0x95, 0x14, 0xac, 0x6b, 0x02,
	0xc3, 0xcf, 0x00, 0x6b, 0x0b, 0xb2, 0x03, 0x9d, 0x68, 0x72, 0x2d, 0x6e, 0x85, 0xfc, 0x25, 0x82,
	0x0d, 0x92, 0x07, 0xd1, 0x84, 0x42, 0x22, 0xa5, 0x94, 0xc0, 0x73, 0xe1, 0x33, 0xcc, 0x51, 0x63,
	0x1a, 0x34, 0x86, 0x63, 0xe8, 0xbf, 0x7c, 0xbc, 0x0f, 0x7e, 0x14, 0xc7, 0x5f, 0xca, 0x32, 0x47,
	0x5a, 0x77, 0x6a, 0x11, 0x42, 0x8f, 0xc0, 0x44, 0xd3, 0x3e, 0xbb, 0x34, 0x6a, 0x13, 0x40, 0x97,
	0x98, 0x79, 0xd6, 0x91, 0xc6, 0x30, 0x27, 0xb2, 0xee, 0xf1, 0x2e, 0x75, 0x9e, 0x38, 0xf2, 0xa4,
	0x66, 0x0d, 0x5e, 0xe1, 0xcf, 0x9a, 0x3e, 0x90, 0x7a, 0x59, 0x89, 0x67, 0x98, 0xe4, 0x99, 0x30,
	0x9a, 0x5c, 0xd2, 0xa5, 0x42, 0x5e, 0xeb, 0x99, 0x54, 0xd9, 0x03, 0xc1, 0xa6, 0xd3, 0xed, 0x2a,
	0xd3, 0x60, 0xf3, 0xf4, 0xe3, 0xe3, 0x49, 0x03, 0x36, 0x1e, 0x4f, 0x9a, 0xa1, 0x77, 0x4a, 0x47,
	0xe6, 0xc1, 0x20, 0x91, 0xc5, 0x68, 0x6a, 0x5c, 0x9d, 0xa1, 0xc2, 0x67, 0xfe, 0xfe, 0xf6, 0xbc,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0x6e, 0x04, 0x1a, 0xbb, 0x03, 0x00, 0x00,
}
