// Code generated by protoc-gen-go.
// source: Server.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseCode int32

const (
	ResponseCode_RCSuccess       ResponseCode = 1
	ResponseCode_RCInputCorrupt  ResponseCode = 2
	ResponseCode_RCInputInvalid  ResponseCode = 3
	ResponseCode_RCServerWarning ResponseCode = 4
	ResponseCode_RCServerError   ResponseCode = 5
	ResponseCode_RCNotAuthorized ResponseCode = 6
	ResponseCode_RCClientTooOld  ResponseCode = 7
)

var ResponseCode_name = map[int32]string{
	1: "RCSuccess",
	2: "RCInputCorrupt",
	3: "RCInputInvalid",
	4: "RCServerWarning",
	5: "RCServerError",
	6: "RCNotAuthorized",
	7: "RCClientTooOld",
}
var ResponseCode_value = map[string]int32{
	"RCSuccess":       1,
	"RCInputCorrupt":  2,
	"RCInputInvalid":  3,
	"RCServerWarning": 4,
	"RCServerError":   5,
	"RCNotAuthorized": 6,
	"RCClientTooOld":  7,
}

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}
func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}
func (x *ResponseCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseCode_value, data, "ResponseCode")
	if err != nil {
		return err
	}
	*x = ResponseCode(value)
	return nil
}
func (ResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type DebugMessage struct {
	DebugText        []string `protobuf:"bytes,1,rep,name=debugText" json:"debugText,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DebugMessage) Reset()                    { *m = DebugMessage{} }
func (m *DebugMessage) String() string            { return proto.CompactTextString(m) }
func (*DebugMessage) ProtoMessage()               {}
func (*DebugMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *DebugMessage) GetDebugText() []string {
	if m != nil {
		return m.DebugText
	}
	return nil
}

type SessionRequest struct {
	Location             *Location    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	DeviceInfo           *DeviceInfo  `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	LastAppDataResetDate *Timestamp   `protobuf:"bytes,4,opt,name=lastAppDataResetDate" json:"lastAppDataResetDate,omitempty"`
	XXX_unrecognized     []byte       `json:"-"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SessionRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SessionRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *SessionRequest) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SessionRequest) GetLastAppDataResetDate() *Timestamp {
	if m != nil {
		return m.LastAppDataResetDate
	}
	return nil
}

type BlitzHereAppOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BlitzHereAppOptions) Reset()                    { *m = BlitzHereAppOptions{} }
func (m *BlitzHereAppOptions) String() string            { return proto.CompactTextString(m) }
func (*BlitzHereAppOptions) ProtoMessage()               {}
func (*BlitzHereAppOptions) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type AppOptions struct {
	BlitzHereOptions *BlitzHereAppOptions `protobuf:"bytes,1,opt,name=blitzHereOptions" json:"blitzHereOptions,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AppOptions) Reset()                    { *m = AppOptions{} }
func (m *AppOptions) String() string            { return proto.CompactTextString(m) }
func (*AppOptions) ProtoMessage()               {}
func (*AppOptions) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *AppOptions) GetBlitzHereOptions() *BlitzHereAppOptions {
	if m != nil {
		return m.BlitzHereOptions
	}
	return nil
}

type SessionResponse struct {
	UserID           *string              `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	SessionToken     *string              `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	ServerURL        *string              `protobuf:"bytes,3,opt,name=serverURL" json:"serverURL,omitempty"`
	UserMessages     []*UserMessage       `protobuf:"bytes,4,rep,name=userMessages" json:"userMessages,omitempty"`
	UserProfile      *UserProfile         `protobuf:"bytes,5,opt,name=userProfile" json:"userProfile,omitempty"`
	ResetAllAppData  *bool                `protobuf:"varint,6,opt,name=resetAllAppData" json:"resetAllAppData,omitempty"`
	InviteRequest    *AcceptInviteRequest `protobuf:"bytes,7,opt,name=inviteRequest" json:"inviteRequest,omitempty"`
	AppOptions       *AppOptions          `protobuf:"bytes,8,opt,name=appOptions" json:"appOptions,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *SessionResponse) Reset()                    { *m = SessionResponse{} }
func (m *SessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()               {}
func (*SessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *SessionResponse) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *SessionResponse) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *SessionResponse) GetServerURL() string {
	if m != nil && m.ServerURL != nil {
		return *m.ServerURL
	}
	return ""
}

func (m *SessionResponse) GetUserMessages() []*UserMessage {
	if m != nil {
		return m.UserMessages
	}
	return nil
}

func (m *SessionResponse) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *SessionResponse) GetResetAllAppData() bool {
	if m != nil && m.ResetAllAppData != nil {
		return *m.ResetAllAppData
	}
	return false
}

func (m *SessionResponse) GetInviteRequest() *AcceptInviteRequest {
	if m != nil {
		return m.InviteRequest
	}
	return nil
}

func (m *SessionResponse) GetAppOptions() *AppOptions {
	if m != nil {
		return m.AppOptions
	}
	return nil
}

type PushConnect struct {
	UserID           *string `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushConnect) Reset()                    { *m = PushConnect{} }
func (m *PushConnect) String() string            { return proto.CompactTextString(m) }
func (*PushConnect) ProtoMessage()               {}
func (*PushConnect) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *PushConnect) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

type PushDisconnect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushDisconnect) Reset()                    { *m = PushDisconnect{} }
func (m *PushDisconnect) String() string            { return proto.CompactTextString(m) }
func (*PushDisconnect) ProtoMessage()               {}
func (*PushDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

type RequestType struct {
	SessionRequest        *SessionRequest        `protobuf:"bytes,1,opt,name=sessionRequest" json:"sessionRequest,omitempty"`
	UserEventBatch        *UserEventBatch        `protobuf:"bytes,2,opt,name=userEventBatch" json:"userEventBatch,omitempty"`
	UserProfileUpdate     *UserProfileUpdate     `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery      *UserProfileQuery      `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest   *ConfirmationRequest   `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	MessageSendRequest    *UserMessageUpdate     `protobuf:"bytes,6,opt,name=messageSendRequest" json:"messageSendRequest,omitempty"`
	MessageFetchRequest   *UserMessageUpdate     `protobuf:"bytes,7,opt,name=messageFetchRequest" json:"messageFetchRequest,omitempty"`
	DebugMessage          *DebugMessage          `protobuf:"bytes,8,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUpload           *ImageUpload           `protobuf:"bytes,9,opt,name=imageUpload" json:"imageUpload,omitempty"`
	AcceptInviteRequest   *AcceptInviteRequest   `protobuf:"bytes,10,opt,name=acceptInviteRequest" json:"acceptInviteRequest,omitempty"`
	FeedPostFetchRequest  *FeedPostFetchRequest  `protobuf:"bytes,11,opt,name=feedPostFetchRequest" json:"feedPostFetchRequest,omitempty"`
	FeedPostUpdateRequest *FeedPostUpdateRequest `protobuf:"bytes,12,opt,name=feedPostUpdateRequest" json:"feedPostUpdateRequest,omitempty"`
	AutocompleteRequest   *AutocompleteRequest   `protobuf:"bytes,13,opt,name=autocompleteRequest" json:"autocompleteRequest,omitempty"`
	EntityTagUpdate       *EntityTagList         `protobuf:"bytes,14,opt,name=entityTagUpdate" json:"entityTagUpdate,omitempty"`
	UserSearchRequest     *UserSearchRequest     `protobuf:"bytes,15,opt,name=userSearchRequest" json:"userSearchRequest,omitempty"`
	PushConnect           *PushConnect           `protobuf:"bytes,16,opt,name=pushConnect" json:"pushConnect,omitempty"`
	PushDisconnect        *PushDisconnect        `protobuf:"bytes,17,opt,name=pushDisconnect" json:"pushDisconnect,omitempty"`
	ConversationRequest   *ConversationRequest   `protobuf:"bytes,18,opt,name=conversationRequest" json:"conversationRequest,omitempty"`
	FetchConversations    *FetchConversations    `protobuf:"bytes,19,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	UserReview            *UserReview            `protobuf:"bytes,20,opt,name=userReview" json:"userReview,omitempty"`
	XXX_unrecognized      []byte                 `json:"-"`
}

func (m *RequestType) Reset()                    { *m = RequestType{} }
func (m *RequestType) String() string            { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()               {}
func (*RequestType) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *RequestType) GetSessionRequest() *SessionRequest {
	if m != nil {
		return m.SessionRequest
	}
	return nil
}

func (m *RequestType) GetUserEventBatch() *UserEventBatch {
	if m != nil {
		return m.UserEventBatch
	}
	return nil
}

func (m *RequestType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *RequestType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *RequestType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *RequestType) GetMessageSendRequest() *UserMessageUpdate {
	if m != nil {
		return m.MessageSendRequest
	}
	return nil
}

func (m *RequestType) GetMessageFetchRequest() *UserMessageUpdate {
	if m != nil {
		return m.MessageFetchRequest
	}
	return nil
}

func (m *RequestType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *RequestType) GetImageUpload() *ImageUpload {
	if m != nil {
		return m.ImageUpload
	}
	return nil
}

func (m *RequestType) GetAcceptInviteRequest() *AcceptInviteRequest {
	if m != nil {
		return m.AcceptInviteRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostFetchRequest() *FeedPostFetchRequest {
	if m != nil {
		return m.FeedPostFetchRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostUpdateRequest() *FeedPostUpdateRequest {
	if m != nil {
		return m.FeedPostUpdateRequest
	}
	return nil
}

func (m *RequestType) GetAutocompleteRequest() *AutocompleteRequest {
	if m != nil {
		return m.AutocompleteRequest
	}
	return nil
}

func (m *RequestType) GetEntityTagUpdate() *EntityTagList {
	if m != nil {
		return m.EntityTagUpdate
	}
	return nil
}

func (m *RequestType) GetUserSearchRequest() *UserSearchRequest {
	if m != nil {
		return m.UserSearchRequest
	}
	return nil
}

func (m *RequestType) GetPushConnect() *PushConnect {
	if m != nil {
		return m.PushConnect
	}
	return nil
}

func (m *RequestType) GetPushDisconnect() *PushDisconnect {
	if m != nil {
		return m.PushDisconnect
	}
	return nil
}

func (m *RequestType) GetConversationRequest() *ConversationRequest {
	if m != nil {
		return m.ConversationRequest
	}
	return nil
}

func (m *RequestType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

func (m *RequestType) GetUserReview() *UserReview {
	if m != nil {
		return m.UserReview
	}
	return nil
}

type ServerRequest struct {
	SessionToken     *string      `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RequestType      *RequestType `protobuf:"bytes,2,opt,name=requestType" json:"requestType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ServerRequest) Reset()                    { *m = ServerRequest{} }
func (m *ServerRequest) String() string            { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()               {}
func (*ServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *ServerRequest) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *ServerRequest) GetRequestType() *RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

type ResponseType struct {
	SessionResponse        *SessionResponse        `protobuf:"bytes,1,opt,name=sessionResponse" json:"sessionResponse,omitempty"`
	UserEventBatchResponse *UserEventBatchResponse `protobuf:"bytes,2,opt,name=userEventBatchResponse" json:"userEventBatchResponse,omitempty"`
	UserProfileUpdate      *UserProfileUpdate      `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery       *UserProfileQuery       `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest    *ConfirmationRequest    `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	UserMessageUpdate      *UserMessageUpdate      `protobuf:"bytes,6,opt,name=userMessageUpdate" json:"userMessageUpdate,omitempty"`
	DebugMessage           *DebugMessage           `protobuf:"bytes,7,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUploadReply       *ImageUpload            `protobuf:"bytes,8,opt,name=imageUploadReply" json:"imageUploadReply,omitempty"`
	AcceptInviteResponse   *AcceptInviteResponse   `protobuf:"bytes,9,opt,name=acceptInviteResponse" json:"acceptInviteResponse,omitempty"`
	FeedPostFetchResponse  *FeedPostFetchResponse  `protobuf:"bytes,10,opt,name=feedPostFetchResponse" json:"feedPostFetchResponse,omitempty"`
	FeedPostUpdateResponse *FeedPostUpdateResponse `protobuf:"bytes,11,opt,name=feedPostUpdateResponse" json:"feedPostUpdateResponse,omitempty"`
	AutocompleteResponse   *AutocompleteResponse   `protobuf:"bytes,12,opt,name=autocompleteResponse" json:"autocompleteResponse,omitempty"`
	UserSearchResponse     *UserSearchResponse     `protobuf:"bytes,13,opt,name=userSearchResponse" json:"userSearchResponse,omitempty"`
	ConversationResponse   *ConversationResponse   `protobuf:"bytes,14,opt,name=conversationResponse" json:"conversationResponse,omitempty"`
	FetchConversations     *FetchConversations     `protobuf:"bytes,15,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	XXX_unrecognized       []byte                  `json:"-"`
}

func (m *ResponseType) Reset()                    { *m = ResponseType{} }
func (m *ResponseType) String() string            { return proto.CompactTextString(m) }
func (*ResponseType) ProtoMessage()               {}
func (*ResponseType) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *ResponseType) GetSessionResponse() *SessionResponse {
	if m != nil {
		return m.SessionResponse
	}
	return nil
}

func (m *ResponseType) GetUserEventBatchResponse() *UserEventBatchResponse {
	if m != nil {
		return m.UserEventBatchResponse
	}
	return nil
}

func (m *ResponseType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *ResponseType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *ResponseType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *ResponseType) GetUserMessageUpdate() *UserMessageUpdate {
	if m != nil {
		return m.UserMessageUpdate
	}
	return nil
}

func (m *ResponseType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *ResponseType) GetImageUploadReply() *ImageUpload {
	if m != nil {
		return m.ImageUploadReply
	}
	return nil
}

func (m *ResponseType) GetAcceptInviteResponse() *AcceptInviteResponse {
	if m != nil {
		return m.AcceptInviteResponse
	}
	return nil
}

func (m *ResponseType) GetFeedPostFetchResponse() *FeedPostFetchResponse {
	if m != nil {
		return m.FeedPostFetchResponse
	}
	return nil
}

func (m *ResponseType) GetFeedPostUpdateResponse() *FeedPostUpdateResponse {
	if m != nil {
		return m.FeedPostUpdateResponse
	}
	return nil
}

func (m *ResponseType) GetAutocompleteResponse() *AutocompleteResponse {
	if m != nil {
		return m.AutocompleteResponse
	}
	return nil
}

func (m *ResponseType) GetUserSearchResponse() *UserSearchResponse {
	if m != nil {
		return m.UserSearchResponse
	}
	return nil
}

func (m *ResponseType) GetConversationResponse() *ConversationResponse {
	if m != nil {
		return m.ConversationResponse
	}
	return nil
}

func (m *ResponseType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

type ServerResponse struct {
	ResponseCode     *ResponseCode `protobuf:"varint,1,opt,name=responseCode,enum=BlitzMessage.ResponseCode" json:"responseCode,omitempty"`
	ResponseMessage  *string       `protobuf:"bytes,2,opt,name=responseMessage" json:"responseMessage,omitempty"`
	ResponseType     *ResponseType `protobuf:"bytes,3,opt,name=responseType" json:"responseType,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ServerResponse) Reset()                    { *m = ServerResponse{} }
func (m *ServerResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()               {}
func (*ServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *ServerResponse) GetResponseCode() ResponseCode {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return ResponseCode_RCSuccess
}

func (m *ServerResponse) GetResponseMessage() string {
	if m != nil && m.ResponseMessage != nil {
		return *m.ResponseMessage
	}
	return ""
}

func (m *ServerResponse) GetResponseType() *ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugMessage)(nil), "BlitzMessage.DebugMessage")
	proto.RegisterType((*SessionRequest)(nil), "BlitzMessage.SessionRequest")
	proto.RegisterType((*BlitzHereAppOptions)(nil), "BlitzMessage.BlitzHereAppOptions")
	proto.RegisterType((*AppOptions)(nil), "BlitzMessage.AppOptions")
	proto.RegisterType((*SessionResponse)(nil), "BlitzMessage.SessionResponse")
	proto.RegisterType((*PushConnect)(nil), "BlitzMessage.PushConnect")
	proto.RegisterType((*PushDisconnect)(nil), "BlitzMessage.PushDisconnect")
	proto.RegisterType((*RequestType)(nil), "BlitzMessage.RequestType")
	proto.RegisterType((*ServerRequest)(nil), "BlitzMessage.ServerRequest")
	proto.RegisterType((*ResponseType)(nil), "BlitzMessage.ResponseType")
	proto.RegisterType((*ServerResponse)(nil), "BlitzMessage.ServerResponse")
	proto.RegisterEnum("BlitzMessage.ResponseCode", ResponseCode_name, ResponseCode_value)
}

var fileDescriptor5 = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x72, 0xe3, 0x34,
	0x14, 0x26, 0xcd, 0x6e, 0xdb, 0x9c, 0xfc, 0xb9, 0x6a, 0x77, 0xd7, 0x74, 0x77, 0x61, 0xd7, 0x70,
	0xd1, 0xd9, 0x81, 0x2e, 0xc3, 0xdf, 0x30, 0xc0, 0x74, 0x68, 0x92, 0x66, 0xc8, 0x4c, 0x61, 0x4b,
	0x7e, 0x86, 0x6b, 0xd7, 0x56, 0x1a, 0x83, 0x63, 0x19, 0x49, 0x0e, 0x74, 0x9f, 0x80, 0x1b, 0x6e,
	0xf7, 0x29, 0xb8, 0xe1, 0x39, 0xb8, 0xdb, 0x27, 0x42, 0x96, 0xe5, 0xc4, 0x72, 0x94, 0xb6, 0xb7,
	0xdc, 0x59, 0xd2, 0x77, 0x8e, 0x74, 0xce, 0xf9, 0xce, 0x27, 0x19, 0x1a, 0x23, 0x4c, 0x17, 0x98,
	0x1e, 0xc7, 0x94, 0x70, 0x82, 0x1a, 0x9d, 0x30, 0xe0, 0xaf, 0x7f, 0xc0, 0x8c, 0xb9, 0x57, 0xf8,
	0xf0, 0x31, 0xb9, 0xfc, 0x05, 0x7b, 0x3c, 0x58, 0x60, 0xef, 0x63, 0x1f, 0x33, 0x8f, 0x06, 0x31,
	0x27, 0x0a, 0x7a, 0x58, 0x1f, 0x5f, 0xc7, 0x98, 0xa9, 0x81, 0x75, 0x16, 0xf1, 0x80, 0x5f, 0x8f,
	0xdd, 0xab, 0x7c, 0x06, 0xfa, 0x18, 0xfb, 0xea, 0xbb, 0xd1, 0xc3, 0x8b, 0xc0, 0xc3, 0xf9, 0x68,
	0x84, 0x5d, 0xea, 0xcd, 0xd4, 0xa8, 0xd9, 0xa7, 0x01, 0x8e, 0xfc, 0xa5, 0xa3, 0x09, 0xc3, 0xf4,
	0x6c, 0x81, 0x23, 0x9e, 0xcf, 0xa0, 0x74, 0x46, 0x9d, 0x48, 0x9b, 0xbb, 0xa0, 0x64, 0x1a, 0x84,
	0xf9, 0x9c, 0xf3, 0x1c, 0xc4, 0x36, 0x97, 0xc9, 0x95, 0x82, 0xa2, 0x3d, 0xa8, 0xf9, 0xe9, 0x78,
	0x8c, 0xff, 0xe0, 0x76, 0xe5, 0x59, 0xf5, 0xa8, 0xe6, 0xfc, 0x5b, 0x81, 0xd6, 0x48, 0x2c, 0x07,
	0x24, 0x1a, 0xe2, 0xdf, 0x12, 0xcc, 0x38, 0x3a, 0x82, 0xdd, 0x90, 0x78, 0x2e, 0x17, 0x53, 0x02,
	0x54, 0x39, 0xaa, 0x7f, 0xfa, 0xf0, 0xb8, 0x98, 0x83, 0xe3, 0x73, 0xb5, 0x8a, 0x3e, 0x02, 0xf0,
	0x65, 0x18, 0x83, 0x68, 0x4a, 0xec, 0x2d, 0x89, 0xb5, 0x75, 0x6c, 0x6f, 0xb9, 0x8e, 0x5e, 0xc0,
	0x4e, 0x9c, 0x9d, 0xcf, 0xae, 0x4a, 0xe8, 0xbb, 0x3a, 0xb4, 0x10, 0x00, 0xfa, 0x02, 0x0e, 0x42,
	0x97, 0xf1, 0xd3, 0x38, 0xee, 0xb9, 0xdc, 0x1d, 0x62, 0x86, 0xb9, 0xf8, 0xc0, 0xf6, 0x3d, 0x69,
	0xf8, 0x48, 0x37, 0x1c, 0x07, 0x73, 0x71, 0x6e, 0x77, 0x1e, 0x3b, 0x0f, 0x60, 0x5f, 0xae, 0x7c,
	0x8f, 0x29, 0x16, 0xb6, 0xaf, 0xe2, 0xf4, 0x98, 0xcc, 0x19, 0x00, 0xac, 0x46, 0xe8, 0x1b, 0xb0,
	0x2e, 0x73, 0x90, 0x9a, 0x53, 0x71, 0x3e, 0xd7, 0xfd, 0x9a, 0x5c, 0xfd, 0xbd, 0x05, 0xed, 0x65,
	0xbe, 0x58, 0x2c, 0xa6, 0x30, 0x6a, 0xc1, 0x76, 0x22, 0xce, 0x3e, 0xe8, 0x49, 0x37, 0x35, 0x74,
	0x00, 0x0d, 0x96, 0x41, 0xc6, 0xe4, 0x57, 0x1c, 0xc9, 0xc4, 0xd4, 0xd2, 0xe4, 0x33, 0xc9, 0xab,
	0xc9, 0xf0, 0x5c, 0x26, 0xa0, 0x86, 0x5e, 0x42, 0x23, 0x29, 0x54, 0x52, 0x44, 0x57, 0x35, 0xa7,
	0x25, 0x2f, 0xe0, 0x31, 0xd4, 0x93, 0x55, 0x96, 0xec, 0xfb, 0xb7, 0xa5, 0xf1, 0x11, 0xb4, 0x69,
	0x9a, 0xbb, 0xd3, 0x30, 0x54, 0xa9, 0xb4, 0xb7, 0x85, 0xcd, 0x2e, 0xfa, 0x0a, 0x9a, 0x41, 0xb4,
	0x08, 0x38, 0x56, 0x45, 0xb7, 0x77, 0x4c, 0x09, 0x38, 0xf5, 0x3c, 0x1c, 0xf3, 0x41, 0x11, 0x98,
	0xd6, 0xdc, 0x5d, 0xa6, 0xc3, 0xde, 0x35, 0xd5, 0xbc, 0x90, 0xae, 0xa7, 0x50, 0xbf, 0x48, 0xd8,
	0xac, 0x4b, 0xa2, 0x48, 0x74, 0x4d, 0x39, 0x53, 0x8e, 0x05, 0xad, 0x74, 0xb9, 0x17, 0x30, 0x2f,
	0x43, 0x38, 0x6f, 0x6a, 0x50, 0x57, 0x5b, 0xa5, 0xcd, 0x84, 0x3e, 0x87, 0x16, 0xd3, 0xe8, 0xa9,
	0x4a, 0xf5, 0x44, 0xdf, 0xb2, 0x44, 0x61, 0x61, 0x95, 0xe4, 0x4d, 0xd3, 0x71, 0xb9, 0x37, 0x53,
	0xe4, 0x7c, 0xb2, 0x9e, 0xaa, 0x15, 0x06, 0x7d, 0x0d, 0x7b, 0x85, 0xec, 0x4e, 0x62, 0x3f, 0x65,
	0x5c, 0x46, 0xd5, 0xf7, 0x37, 0xe6, 0x38, 0x83, 0x89, 0x84, 0x5a, 0x05, 0xdb, 0x9f, 0x12, 0x4c,
	0xaf, 0x15, 0x59, 0xdf, 0xdb, 0x68, 0x2a, 0x51, 0xe8, 0x04, 0xf6, 0x45, 0xf0, 0xd3, 0x80, 0xce,
	0x65, 0x53, 0xe5, 0x61, 0xde, 0x37, 0x15, 0xa4, 0xbb, 0x0e, 0x14, 0x74, 0x46, 0xf3, 0x6c, 0x79,
	0x24, 0x44, 0x23, 0x37, 0xdf, 0xde, 0x74, 0x6c, 0xf5, 0xad, 0x8e, 0xfd, 0x2d, 0xec, 0x2b, 0xe3,
	0x3e, 0x16, 0x29, 0xd0, 0xd9, 0x70, 0xab, 0xf5, 0x27, 0xd0, 0xf0, 0x0b, 0xfa, 0xa2, 0xd8, 0x70,
	0x58, 0x56, 0x80, 0x82, 0x02, 0x09, 0x02, 0x07, 0x73, 0xe9, 0x20, 0x24, 0xae, 0x6f, 0xd7, 0x4c,
	0x04, 0x1e, 0xac, 0x00, 0x69, 0x72, 0xdc, 0x75, 0x12, 0xda, 0x70, 0x57, 0xb6, 0x7e, 0x07, 0x07,
	0x53, 0x21, 0xba, 0x17, 0x84, 0x71, 0x2d, 0xc0, 0xba, 0x74, 0xe0, 0xe8, 0x0e, 0xfa, 0x06, 0x24,
	0xea, 0xc0, 0x83, 0xdc, 0x43, 0x16, 0x75, 0xee, 0xa2, 0x21, 0x5d, 0x7c, 0x60, 0x76, 0xa1, 0x41,
	0x65, 0x14, 0x09, 0x27, 0x1e, 0x99, 0xc7, 0x21, 0x5e, 0x79, 0x68, 0x1a, 0xa3, 0x58, 0x07, 0x0a,
	0x3a, 0xb7, 0x71, 0x7e, 0x99, 0x28, 0x5a, 0xb6, 0xa4, 0xed, 0x63, 0xdd, 0x76, 0x79, 0xe3, 0x9c,
	0x07, 0xc2, 0x4a, 0xd1, 0x39, 0xbb, 0x5a, 0xf2, 0x3d, 0xdb, 0x9b, 0x2a, 0xab, 0xc1, 0xd2, 0x3a,
	0xc5, 0xab, 0xbe, 0xb5, 0x2d, 0x53, 0x9d, 0x8a, 0x8d, 0x2d, 0x1a, 0x2e, 0xd6, 0x1a, 0xd9, 0xde,
	0x33, 0x35, 0x9c, 0xde, 0xec, 0x8a, 0xfa, 0x42, 0x12, 0x99, 0x46, 0x7d, 0xb4, 0x81, 0xfa, 0x65,
	0xa0, 0x60, 0x2f, 0x9a, 0xa6, 0xb5, 0x2a, 0xae, 0x31, 0x7b, 0x5f, 0x9a, 0x3f, 0x2b, 0x17, 0xa6,
	0x8c, 0x4b, 0x95, 0x2c, 0xcd, 0xcf, 0x50, 0xdc, 0x50, 0xf8, 0x77, 0xfb, 0xc0, 0xa4, 0x64, 0x93,
	0xe5, 0xba, 0x33, 0x81, 0x66, 0xf6, 0x2c, 0xc8, 0x37, 0x2f, 0xab, 0x7c, 0xa6, 0xfd, 0x22, 0x71,
	0x74, 0x25, 0x5f, 0x4a, 0x76, 0x4a, 0x89, 0x2b, 0xe8, 0x9b, 0xf3, 0xcf, 0x0e, 0x34, 0xf2, 0x8b,
	0x44, 0x0a, 0xde, 0x97, 0xd0, 0x66, 0xfa, 0xfd, 0xa2, 0x14, 0xef, 0xe9, 0x06, 0xc5, 0x53, 0x97,
	0x50, 0x0f, 0x1e, 0xea, 0x92, 0xb7, 0x34, 0xcf, 0xce, 0xf0, 0xe1, 0x4d, 0xd2, 0xb7, 0xf4, 0xf2,
	0xff, 0x94, 0x40, 0x75, 0x6a, 0x4d, 0x9c, 0xee, 0xaa, 0x80, 0x65, 0x0d, 0xdb, 0xb9, 0x55, 0xc3,
	0x3e, 0x03, 0xab, 0xa0, 0x61, 0x43, 0x1c, 0x87, 0xd7, 0x4a, 0xf9, 0x6e, 0x10, 0x32, 0x21, 0x44,
	0xba, 0x90, 0xa9, 0xe2, 0xd4, 0x4c, 0x42, 0x74, 0x6a, 0x40, 0x16, 0x85, 0x48, 0x09, 0x94, 0x72,
	0x01, 0x37, 0x09, 0x91, 0x06, 0x4d, 0x49, 0x52, 0x16, 0x33, 0xe5, 0xa4, 0x6e, 0x22, 0x49, 0xdf,
	0x88, 0x95, 0xb1, 0x68, 0x2a, 0xa5, 0x7c, 0x34, 0x8c, 0xb1, 0x18, 0x90, 0x69, 0xe3, 0x16, 0xa5,
	0x49, 0xd9, 0x37, 0x4d, 0x8d, 0x3b, 0x59, 0xc3, 0xa5, 0xfb, 0xeb, 0xb2, 0xa1, 0xec, 0x5b, 0xa6,
	0xfd, 0xbb, 0x06, 0xe4, 0x06, 0xe1, 0x68, 0xdf, 0x4d, 0x38, 0x9c, 0xbf, 0xe4, 0x9b, 0x39, 0xd3,
	0x02, 0xe5, 0x50, 0xb0, 0x88, 0xaa, 0xef, 0x2e, 0xf1, 0xb3, 0x96, 0x6d, 0x95, 0x59, 0x34, 0x2c,
	0x20, 0xd4, 0xd3, 0x4c, 0x8e, 0x73, 0xea, 0x65, 0xef, 0xc4, 0x82, 0x2b, 0x29, 0x21, 0x55, 0x13,
	0x21, 0x8b, 0x92, 0xf1, 0xe2, 0x4d, 0x65, 0xa5, 0x21, 0xd2, 0x77, 0x13, 0x6a, 0xc3, 0xee, 0x28,
	0x11, 0x2c, 0x62, 0xcc, 0xaa, 0x20, 0x04, 0xad, 0x61, 0x77, 0x10, 0xc5, 0x09, 0xef, 0x12, 0x4a,
	0x93, 0x98, 0x5b, 0x5b, 0x85, 0x39, 0x41, 0x33, 0x37, 0x0c, 0x7c, 0xab, 0x8a, 0xf6, 0xa1, 0x2d,
	0xcc, 0x64, 0x60, 0x3f, 0xbb, 0x34, 0x0a, 0xa2, 0x2b, 0xeb, 0x9e, 0x78, 0xb6, 0x36, 0xf3, 0xc9,
	0x33, 0x4a, 0x09, 0xb5, 0xee, 0x67, 0xb8, 0x1f, 0x09, 0x17, 0xa5, 0x9d, 0x11, 0x1a, 0xbc, 0xc6,
	0xbe, 0xb5, 0x9d, 0x39, 0xec, 0x86, 0xe2, 0xc7, 0x85, 0x8f, 0x09, 0x79, 0x15, 0xfa, 0xd6, 0x4e,
	0xe7, 0xe5, 0xdb, 0x93, 0x2d, 0x78, 0xe7, 0xed, 0x49, 0x15, 0x55, 0x3a, 0xe2, 0xd3, 0xae, 0xc0,
	0xa1, 0xa0, 0xc2, 0xb1, 0x7c, 0x7d, 0xcf, 0xc4, 0xbb, 0x5a, 0x8b, 0xe9, 0xcf, 0x4a, 0xe5, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x20, 0x3c, 0x3f, 0x7a, 0x0d, 0x00, 0x00,
}
