// Code generated by protoc-gen-go.
// source: Server.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseCode int32

const (
	ResponseCode_RCSuccess          ResponseCode = 1
	ResponseCode_RCInputCorrupt     ResponseCode = 2
	ResponseCode_RCInputInvalid     ResponseCode = 3
	ResponseCode_RCServerWarning    ResponseCode = 4
	ResponseCode_RCServerError      ResponseCode = 5
	ResponseCode_RCNotAuthorized    ResponseCode = 6
	ResponseCode_RCClientTooOld     ResponseCode = 7
	ResponseCode_RCPaymentError     ResponseCode = 8
	ResponseCode_RCPurchaseRequired ResponseCode = 9
)

var ResponseCode_name = map[int32]string{
	1: "RCSuccess",
	2: "RCInputCorrupt",
	3: "RCInputInvalid",
	4: "RCServerWarning",
	5: "RCServerError",
	6: "RCNotAuthorized",
	7: "RCClientTooOld",
	8: "RCPaymentError",
	9: "RCPurchaseRequired",
}
var ResponseCode_value = map[string]int32{
	"RCSuccess":          1,
	"RCInputCorrupt":     2,
	"RCInputInvalid":     3,
	"RCServerWarning":    4,
	"RCServerError":      5,
	"RCNotAuthorized":    6,
	"RCClientTooOld":     7,
	"RCPaymentError":     8,
	"RCPurchaseRequired": 9,
}

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}
func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}
func (x *ResponseCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseCode_value, data, "ResponseCode")
	if err != nil {
		return err
	}
	*x = ResponseCode(value)
	return nil
}
func (ResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type DebugMessage struct {
	DebugText        []string `protobuf:"bytes,1,rep,name=debugText" json:"debugText,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DebugMessage) Reset()                    { *m = DebugMessage{} }
func (m *DebugMessage) String() string            { return proto.CompactTextString(m) }
func (*DebugMessage) ProtoMessage()               {}
func (*DebugMessage) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *DebugMessage) GetDebugText() []string {
	if m != nil {
		return m.DebugText
	}
	return nil
}

type SessionRequest struct {
	Location             *Location    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	DeviceInfo           *DeviceInfo  `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	LastAppDataResetDate *Timestamp   `protobuf:"bytes,4,opt,name=lastAppDataResetDate" json:"lastAppDataResetDate,omitempty"`
	Logout               *bool        `protobuf:"varint,5,opt,name=logout" json:"logout,omitempty"`
	Login                *string      `protobuf:"bytes,6,opt,name=login" json:"login,omitempty"`
	Secret               *string      `protobuf:"bytes,7,opt,name=secret" json:"secret,omitempty"`
	XXX_unrecognized     []byte       `json:"-"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *SessionRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SessionRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *SessionRequest) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SessionRequest) GetLastAppDataResetDate() *Timestamp {
	if m != nil {
		return m.LastAppDataResetDate
	}
	return nil
}

func (m *SessionRequest) GetLogout() bool {
	if m != nil && m.Logout != nil {
		return *m.Logout
	}
	return false
}

func (m *SessionRequest) GetLogin() string {
	if m != nil && m.Login != nil {
		return *m.Login
	}
	return ""
}

func (m *SessionRequest) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

type BlitzHereAppOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BlitzHereAppOptions) Reset()                    { *m = BlitzHereAppOptions{} }
func (m *BlitzHereAppOptions) String() string            { return proto.CompactTextString(m) }
func (*BlitzHereAppOptions) ProtoMessage()               {}
func (*BlitzHereAppOptions) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

type AppOptions struct {
	BlitzHereOptions *BlitzHereAppOptions `protobuf:"bytes,1,opt,name=blitzHereOptions" json:"blitzHereOptions,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AppOptions) Reset()                    { *m = AppOptions{} }
func (m *AppOptions) String() string            { return proto.CompactTextString(m) }
func (*AppOptions) ProtoMessage()               {}
func (*AppOptions) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *AppOptions) GetBlitzHereOptions() *BlitzHereAppOptions {
	if m != nil {
		return m.BlitzHereOptions
	}
	return nil
}

type SessionResponse struct {
	UserID           *string        `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	SessionToken     *string        `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	ServerURL        *string        `protobuf:"bytes,3,opt,name=serverURL" json:"serverURL,omitempty"`
	UserMessages     []*UserMessage `protobuf:"bytes,4,rep,name=userMessages" json:"userMessages,omitempty"`
	UserProfile      *UserProfile   `protobuf:"bytes,5,opt,name=userProfile" json:"userProfile,omitempty"`
	ResetAllAppData  *bool          `protobuf:"varint,6,opt,name=resetAllAppData" json:"resetAllAppData,omitempty"`
	InviteRequest    *UserInvite    `protobuf:"bytes,7,opt,name=inviteRequest" json:"inviteRequest,omitempty"`
	AppOptions       *AppOptions    `protobuf:"bytes,8,opt,name=appOptions" json:"appOptions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SessionResponse) Reset()                    { *m = SessionResponse{} }
func (m *SessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()               {}
func (*SessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *SessionResponse) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *SessionResponse) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *SessionResponse) GetServerURL() string {
	if m != nil && m.ServerURL != nil {
		return *m.ServerURL
	}
	return ""
}

func (m *SessionResponse) GetUserMessages() []*UserMessage {
	if m != nil {
		return m.UserMessages
	}
	return nil
}

func (m *SessionResponse) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *SessionResponse) GetResetAllAppData() bool {
	if m != nil && m.ResetAllAppData != nil {
		return *m.ResetAllAppData
	}
	return false
}

func (m *SessionResponse) GetInviteRequest() *UserInvite {
	if m != nil {
		return m.InviteRequest
	}
	return nil
}

func (m *SessionResponse) GetAppOptions() *AppOptions {
	if m != nil {
		return m.AppOptions
	}
	return nil
}

type LoginAsAdmin struct {
	AdminProfile     *UserProfile `protobuf:"bytes,1,opt,name=adminProfile" json:"adminProfile,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *LoginAsAdmin) Reset()                    { *m = LoginAsAdmin{} }
func (m *LoginAsAdmin) String() string            { return proto.CompactTextString(m) }
func (*LoginAsAdmin) ProtoMessage()               {}
func (*LoginAsAdmin) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *LoginAsAdmin) GetAdminProfile() *UserProfile {
	if m != nil {
		return m.AdminProfile
	}
	return nil
}

type PushConnect struct {
	UserID               *string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	LastMessageTimestamp *Timestamp `protobuf:"bytes,2,opt,name=lastMessageTimestamp" json:"lastMessageTimestamp,omitempty"`
	XXX_unrecognized     []byte     `json:"-"`
}

func (m *PushConnect) Reset()                    { *m = PushConnect{} }
func (m *PushConnect) String() string            { return proto.CompactTextString(m) }
func (*PushConnect) ProtoMessage()               {}
func (*PushConnect) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *PushConnect) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *PushConnect) GetLastMessageTimestamp() *Timestamp {
	if m != nil {
		return m.LastMessageTimestamp
	}
	return nil
}

type PushDisconnect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushDisconnect) Reset()                    { *m = PushDisconnect{} }
func (m *PushDisconnect) String() string            { return proto.CompactTextString(m) }
func (*PushDisconnect) ProtoMessage()               {}
func (*PushDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type RequestType struct {
	SessionRequest               *SessionRequest           `protobuf:"bytes,1,opt,name=sessionRequest" json:"sessionRequest,omitempty"`
	UserEventBatch               *UserEventBatch           `protobuf:"bytes,2,opt,name=userEventBatch" json:"userEventBatch,omitempty"`
	UserProfileUpdate            *UserProfileUpdate        `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery             *UserProfileQuery         `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest          *ConfirmationRequest      `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	MessageSendRequestDeprecated *UserMessageUpdate        `protobuf:"bytes,6,opt,name=messageSendRequest_deprecated" json:"messageSendRequest_deprecated,omitempty"`
	MessageFetchRequest          *UserMessageUpdate        `protobuf:"bytes,7,opt,name=messageFetchRequest" json:"messageFetchRequest,omitempty"`
	DebugMessage                 *DebugMessage             `protobuf:"bytes,8,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUpload                  *ImageUpload              `protobuf:"bytes,9,opt,name=imageUpload" json:"imageUpload,omitempty"`
	AcceptInviteRequest          *UserInvite               `protobuf:"bytes,10,opt,name=acceptInviteRequest" json:"acceptInviteRequest,omitempty"`
	FeedPostFetchRequest         *FeedPostFetchRequest     `protobuf:"bytes,11,opt,name=feedPostFetchRequest" json:"feedPostFetchRequest,omitempty"`
	FeedPostUpdateRequest        *FeedPostUpdateRequest    `protobuf:"bytes,12,opt,name=feedPostUpdateRequest" json:"feedPostUpdateRequest,omitempty"`
	AutocompleteRequest          *AutocompleteRequest      `protobuf:"bytes,13,opt,name=autocompleteRequest" json:"autocompleteRequest,omitempty"`
	EntityTagUpdate              *EntityTagList            `protobuf:"bytes,14,opt,name=entityTagUpdate" json:"entityTagUpdate,omitempty"`
	UserSearchRequest            *UserSearchRequest        `protobuf:"bytes,15,opt,name=userSearchRequest" json:"userSearchRequest,omitempty"`
	PushConnect                  *PushConnect              `protobuf:"bytes,16,opt,name=pushConnect" json:"pushConnect,omitempty"`
	PushDisconnect               *PushDisconnect           `protobuf:"bytes,17,opt,name=pushDisconnect" json:"pushDisconnect,omitempty"`
	ConversationRequest          *ConversationRequest      `protobuf:"bytes,18,opt,name=conversationRequest" json:"conversationRequest,omitempty"`
	FetchConversations           *FetchConversations       `protobuf:"bytes,19,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	UserReview                   *UserReview               `protobuf:"bytes,20,opt,name=userReview" json:"userReview,omitempty"`
	UpdateConversationStatus     *UpdateConversationStatus `protobuf:"bytes,21,opt,name=updateConversationStatus" json:"updateConversationStatus,omitempty"`
	UserCardInfo                 *UserCardInfo             `protobuf:"bytes,22,opt,name=userCardInfo" json:"userCardInfo,omitempty"`
	ChargeRequest                *Charge                   `protobuf:"bytes,23,opt,name=chargeRequest" json:"chargeRequest,omitempty"`
	FriendRequest                *FriendUpdate             `protobuf:"bytes,24,opt,name=friendRequest" json:"friendRequest,omitempty"`
	SearchCategories             *SearchCategories         `protobuf:"bytes,25,opt,name=searchCategories" json:"searchCategories,omitempty"`
	SendMessage                  *UserMessage              `protobuf:"bytes,26,opt,name=sendMessage" json:"sendMessage,omitempty"`
	EditProfile                  *EditProfile              `protobuf:"bytes,27,opt,name=editProfile" json:"editProfile,omitempty"`
	FetchConversationGroups      *FetchConversationGroups  `protobuf:"bytes,28,opt,name=fetchConversationGroups" json:"fetchConversationGroups,omitempty"`
	LoginAsAdmin                 *LoginAsAdmin             `protobuf:"bytes,29,opt,name=loginAsAdmin" json:"loginAsAdmin,omitempty"`
	FetchPurchaseDescription     *FetchPurchaseDescription `protobuf:"bytes,30,opt,name=fetchPurchaseDescription" json:"fetchPurchaseDescription,omitempty"`
	UserInvitesRequest           *UserInvites              `protobuf:"bytes,31,opt,name=userInvitesRequest" json:"userInvitesRequest,omitempty"`
	FetchFeedReplyUpvoteProfiles *FeedReplyFetchRequest    `protobuf:"bytes,32,opt,name=fetchFeedReplyUpvoteProfiles" json:"fetchFeedReplyUpvoteProfiles,omitempty"`
	XXX_unrecognized             []byte                    `json:"-"`
}

func (m *RequestType) Reset()                    { *m = RequestType{} }
func (m *RequestType) String() string            { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()               {}
func (*RequestType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *RequestType) GetSessionRequest() *SessionRequest {
	if m != nil {
		return m.SessionRequest
	}
	return nil
}

func (m *RequestType) GetUserEventBatch() *UserEventBatch {
	if m != nil {
		return m.UserEventBatch
	}
	return nil
}

func (m *RequestType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *RequestType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *RequestType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *RequestType) GetMessageSendRequestDeprecated() *UserMessageUpdate {
	if m != nil {
		return m.MessageSendRequestDeprecated
	}
	return nil
}

func (m *RequestType) GetMessageFetchRequest() *UserMessageUpdate {
	if m != nil {
		return m.MessageFetchRequest
	}
	return nil
}

func (m *RequestType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *RequestType) GetImageUpload() *ImageUpload {
	if m != nil {
		return m.ImageUpload
	}
	return nil
}

func (m *RequestType) GetAcceptInviteRequest() *UserInvite {
	if m != nil {
		return m.AcceptInviteRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostFetchRequest() *FeedPostFetchRequest {
	if m != nil {
		return m.FeedPostFetchRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostUpdateRequest() *FeedPostUpdateRequest {
	if m != nil {
		return m.FeedPostUpdateRequest
	}
	return nil
}

func (m *RequestType) GetAutocompleteRequest() *AutocompleteRequest {
	if m != nil {
		return m.AutocompleteRequest
	}
	return nil
}

func (m *RequestType) GetEntityTagUpdate() *EntityTagList {
	if m != nil {
		return m.EntityTagUpdate
	}
	return nil
}

func (m *RequestType) GetUserSearchRequest() *UserSearchRequest {
	if m != nil {
		return m.UserSearchRequest
	}
	return nil
}

func (m *RequestType) GetPushConnect() *PushConnect {
	if m != nil {
		return m.PushConnect
	}
	return nil
}

func (m *RequestType) GetPushDisconnect() *PushDisconnect {
	if m != nil {
		return m.PushDisconnect
	}
	return nil
}

func (m *RequestType) GetConversationRequest() *ConversationRequest {
	if m != nil {
		return m.ConversationRequest
	}
	return nil
}

func (m *RequestType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

func (m *RequestType) GetUserReview() *UserReview {
	if m != nil {
		return m.UserReview
	}
	return nil
}

func (m *RequestType) GetUpdateConversationStatus() *UpdateConversationStatus {
	if m != nil {
		return m.UpdateConversationStatus
	}
	return nil
}

func (m *RequestType) GetUserCardInfo() *UserCardInfo {
	if m != nil {
		return m.UserCardInfo
	}
	return nil
}

func (m *RequestType) GetChargeRequest() *Charge {
	if m != nil {
		return m.ChargeRequest
	}
	return nil
}

func (m *RequestType) GetFriendRequest() *FriendUpdate {
	if m != nil {
		return m.FriendRequest
	}
	return nil
}

func (m *RequestType) GetSearchCategories() *SearchCategories {
	if m != nil {
		return m.SearchCategories
	}
	return nil
}

func (m *RequestType) GetSendMessage() *UserMessage {
	if m != nil {
		return m.SendMessage
	}
	return nil
}

func (m *RequestType) GetEditProfile() *EditProfile {
	if m != nil {
		return m.EditProfile
	}
	return nil
}

func (m *RequestType) GetFetchConversationGroups() *FetchConversationGroups {
	if m != nil {
		return m.FetchConversationGroups
	}
	return nil
}

func (m *RequestType) GetLoginAsAdmin() *LoginAsAdmin {
	if m != nil {
		return m.LoginAsAdmin
	}
	return nil
}

func (m *RequestType) GetFetchPurchaseDescription() *FetchPurchaseDescription {
	if m != nil {
		return m.FetchPurchaseDescription
	}
	return nil
}

func (m *RequestType) GetUserInvitesRequest() *UserInvites {
	if m != nil {
		return m.UserInvitesRequest
	}
	return nil
}

func (m *RequestType) GetFetchFeedReplyUpvoteProfiles() *FeedReplyFetchRequest {
	if m != nil {
		return m.FetchFeedReplyUpvoteProfiles
	}
	return nil
}

type ServerRequest struct {
	SessionToken     *string      `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RequestType      *RequestType `protobuf:"bytes,2,opt,name=requestType" json:"requestType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ServerRequest) Reset()                    { *m = ServerRequest{} }
func (m *ServerRequest) String() string            { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()               {}
func (*ServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *ServerRequest) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *ServerRequest) GetRequestType() *RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

type ResponseType struct {
	SessionResponse        *SessionResponse        `protobuf:"bytes,1,opt,name=sessionResponse" json:"sessionResponse,omitempty"`
	UserEventBatchResponse *UserEventBatchResponse `protobuf:"bytes,2,opt,name=userEventBatchResponse" json:"userEventBatchResponse,omitempty"`
	UserProfileUpdate      *UserProfileUpdate      `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery       *UserProfileQuery       `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest    *ConfirmationRequest    `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	UserMessageUpdate      *UserMessageUpdate      `protobuf:"bytes,6,opt,name=userMessageUpdate" json:"userMessageUpdate,omitempty"`
	DebugMessage           *DebugMessage           `protobuf:"bytes,7,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUploadReply       *ImageUpload            `protobuf:"bytes,8,opt,name=imageUploadReply" json:"imageUploadReply,omitempty"`
	AcceptInviteResponse   *UserInvite             `protobuf:"bytes,9,opt,name=acceptInviteResponse" json:"acceptInviteResponse,omitempty"`
	// optional FeedPostFetchResponse  feedPostFetchResponse   = 10; Deprecated
	// optional FeedPostUpdateResponse feedPostUpdateResponse  = 11; Deprecated
	AutocompleteResponse     *AutocompleteResponse     `protobuf:"bytes,12,opt,name=autocompleteResponse" json:"autocompleteResponse,omitempty"`
	UserSearchResponse       *UserSearchResponse       `protobuf:"bytes,13,opt,name=userSearchResponse" json:"userSearchResponse,omitempty"`
	ConversationResponse     *ConversationResponse     `protobuf:"bytes,14,opt,name=conversationResponse" json:"conversationResponse,omitempty"`
	FetchConversations       *FetchConversations       `protobuf:"bytes,15,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	UserCardInfo             *UserCardInfo             `protobuf:"bytes,16,opt,name=userCardInfo" json:"userCardInfo,omitempty"`
	ChargeResponse           *Charge                   `protobuf:"bytes,17,opt,name=chargeResponse" json:"chargeResponse,omitempty"`
	FriendResponse           *FriendUpdate             `protobuf:"bytes,18,opt,name=friendResponse" json:"friendResponse,omitempty"`
	SearchCategories         *SearchCategories         `protobuf:"bytes,19,opt,name=searchCategories" json:"searchCategories,omitempty"`
	FeedPostResponse         *FeedPostResponse         `protobuf:"bytes,20,opt,name=feedPostResponse" json:"feedPostResponse,omitempty"`
	PurchaseDescription      *PurchaseDescription      `protobuf:"bytes,21,opt,name=purchaseDescription" json:"purchaseDescription,omitempty"`
	EditProfile              *EditProfile              `protobuf:"bytes,22,opt,name=editProfile" json:"editProfile,omitempty"`
	FetchConversationGroups  *FetchConversationGroups  `protobuf:"bytes,23,opt,name=fetchConversationGroups" json:"fetchConversationGroups,omitempty"`
	LoginAsAdmin             *LoginAsAdmin             `protobuf:"bytes,24,opt,name=loginAsAdmin" json:"loginAsAdmin,omitempty"`
	FetchPurchaseDescription *FetchPurchaseDescription `protobuf:"bytes,25,opt,name=fetchPurchaseDescription" json:"fetchPurchaseDescription,omitempty"`
	UserInvitesResponse      *UserInvites              `protobuf:"bytes,26,opt,name=userInvitesResponse" json:"userInvitesResponse,omitempty"`
	XXX_unrecognized         []byte                    `json:"-"`
}

func (m *ResponseType) Reset()                    { *m = ResponseType{} }
func (m *ResponseType) String() string            { return proto.CompactTextString(m) }
func (*ResponseType) ProtoMessage()               {}
func (*ResponseType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *ResponseType) GetSessionResponse() *SessionResponse {
	if m != nil {
		return m.SessionResponse
	}
	return nil
}

func (m *ResponseType) GetUserEventBatchResponse() *UserEventBatchResponse {
	if m != nil {
		return m.UserEventBatchResponse
	}
	return nil
}

func (m *ResponseType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *ResponseType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *ResponseType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *ResponseType) GetUserMessageUpdate() *UserMessageUpdate {
	if m != nil {
		return m.UserMessageUpdate
	}
	return nil
}

func (m *ResponseType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *ResponseType) GetImageUploadReply() *ImageUpload {
	if m != nil {
		return m.ImageUploadReply
	}
	return nil
}

func (m *ResponseType) GetAcceptInviteResponse() *UserInvite {
	if m != nil {
		return m.AcceptInviteResponse
	}
	return nil
}

func (m *ResponseType) GetAutocompleteResponse() *AutocompleteResponse {
	if m != nil {
		return m.AutocompleteResponse
	}
	return nil
}

func (m *ResponseType) GetUserSearchResponse() *UserSearchResponse {
	if m != nil {
		return m.UserSearchResponse
	}
	return nil
}

func (m *ResponseType) GetConversationResponse() *ConversationResponse {
	if m != nil {
		return m.ConversationResponse
	}
	return nil
}

func (m *ResponseType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

func (m *ResponseType) GetUserCardInfo() *UserCardInfo {
	if m != nil {
		return m.UserCardInfo
	}
	return nil
}

func (m *ResponseType) GetChargeResponse() *Charge {
	if m != nil {
		return m.ChargeResponse
	}
	return nil
}

func (m *ResponseType) GetFriendResponse() *FriendUpdate {
	if m != nil {
		return m.FriendResponse
	}
	return nil
}

func (m *ResponseType) GetSearchCategories() *SearchCategories {
	if m != nil {
		return m.SearchCategories
	}
	return nil
}

func (m *ResponseType) GetFeedPostResponse() *FeedPostResponse {
	if m != nil {
		return m.FeedPostResponse
	}
	return nil
}

func (m *ResponseType) GetPurchaseDescription() *PurchaseDescription {
	if m != nil {
		return m.PurchaseDescription
	}
	return nil
}

func (m *ResponseType) GetEditProfile() *EditProfile {
	if m != nil {
		return m.EditProfile
	}
	return nil
}

func (m *ResponseType) GetFetchConversationGroups() *FetchConversationGroups {
	if m != nil {
		return m.FetchConversationGroups
	}
	return nil
}

func (m *ResponseType) GetLoginAsAdmin() *LoginAsAdmin {
	if m != nil {
		return m.LoginAsAdmin
	}
	return nil
}

func (m *ResponseType) GetFetchPurchaseDescription() *FetchPurchaseDescription {
	if m != nil {
		return m.FetchPurchaseDescription
	}
	return nil
}

func (m *ResponseType) GetUserInvitesResponse() *UserInvites {
	if m != nil {
		return m.UserInvitesResponse
	}
	return nil
}

type ServerResponse struct {
	ResponseCode     *ResponseCode `protobuf:"varint,1,opt,name=responseCode,enum=BlitzMessage.ResponseCode" json:"responseCode,omitempty"`
	ResponseMessage  *string       `protobuf:"bytes,2,opt,name=responseMessage" json:"responseMessage,omitempty"`
	ResponseType     *ResponseType `protobuf:"bytes,3,opt,name=responseType" json:"responseType,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ServerResponse) Reset()                    { *m = ServerResponse{} }
func (m *ServerResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()               {}
func (*ServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *ServerResponse) GetResponseCode() ResponseCode {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return ResponseCode_RCSuccess
}

func (m *ServerResponse) GetResponseMessage() string {
	if m != nil && m.ResponseMessage != nil {
		return *m.ResponseMessage
	}
	return ""
}

func (m *ServerResponse) GetResponseType() *ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugMessage)(nil), "BlitzMessage.DebugMessage")
	proto.RegisterType((*SessionRequest)(nil), "BlitzMessage.SessionRequest")
	proto.RegisterType((*BlitzHereAppOptions)(nil), "BlitzMessage.BlitzHereAppOptions")
	proto.RegisterType((*AppOptions)(nil), "BlitzMessage.AppOptions")
	proto.RegisterType((*SessionResponse)(nil), "BlitzMessage.SessionResponse")
	proto.RegisterType((*LoginAsAdmin)(nil), "BlitzMessage.LoginAsAdmin")
	proto.RegisterType((*PushConnect)(nil), "BlitzMessage.PushConnect")
	proto.RegisterType((*PushDisconnect)(nil), "BlitzMessage.PushDisconnect")
	proto.RegisterType((*RequestType)(nil), "BlitzMessage.RequestType")
	proto.RegisterType((*ServerRequest)(nil), "BlitzMessage.ServerRequest")
	proto.RegisterType((*ResponseType)(nil), "BlitzMessage.ResponseType")
	proto.RegisterType((*ServerResponse)(nil), "BlitzMessage.ServerResponse")
	proto.RegisterEnum("BlitzMessage.ResponseCode", ResponseCode_name, ResponseCode_value)
}

func init() { proto.RegisterFile("Server.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 1504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x58, 0xdd, 0x72, 0xdb, 0x44,
	0x1b, 0xfe, 0x9c, 0x34, 0x4d, 0xfc, 0xda, 0x56, 0x94, 0x75, 0x7e, 0xd4, 0x34, 0x6d, 0x53, 0x7f,
	0x3f, 0x93, 0xe9, 0x57, 0xd2, 0x52, 0xd2, 0x4e, 0x07, 0x3a, 0x01, 0xc7, 0x8e, 0xa9, 0x67, 0x02,
	0x0d, 0x4e, 0x32, 0x1c, 0x32, 0xaa, 0xf4, 0xc6, 0x16, 0xc8, 0x5a, 0xb1, 0xbb, 0x32, 0xa4, 0x57,
	0xc0, 0x09, 0x07, 0x5c, 0x03, 0x77, 0xc2, 0x25, 0x74, 0xb8, 0x1a, 0x8e, 0x98, 0x5d, 0xad, 0x6c,
	0x49, 0x96, 0xe3, 0x42, 0x8f, 0x38, 0x93, 0x76, 0x9f, 0xf7, 0xd5, 0xbe, 0x7f, 0xcf, 0xb3, 0x36,
	0x54, 0xcf, 0x90, 0x8d, 0x90, 0xed, 0x87, 0x8c, 0x0a, 0x4a, 0xaa, 0x47, 0xbe, 0x27, 0xde, 0x7c,
	0x81, 0x9c, 0xdb, 0x7d, 0xdc, 0xbe, 0x4d, 0x5f, 0x7f, 0x8b, 0x8e, 0xf0, 0x46, 0xe8, 0x7c, 0xe0,
	0x22, 0x77, 0x98, 0x17, 0x0a, 0xaa, 0xa1, 0xdb, 0x95, 0xf3, 0xab, 0x10, 0xb9, 0x7e, 0xa9, 0xb6,
	0x71, 0xe4, 0x39, 0xa8, 0xdf, 0xcc, 0xe3, 0x40, 0x78, 0xe2, 0xea, 0xdc, 0xee, 0x27, 0xfb, 0xd0,
	0x41, 0x74, 0xf5, 0xb3, 0x71, 0x6a, 0x5f, 0x0d, 0x31, 0x10, 0x63, 0xdb, 0x33, 0xb4, 0x99, 0x33,
	0x48, 0x6c, 0x2f, 0x38, 0xb2, 0xe3, 0x51, 0x6a, 0x9f, 0xc8, 0x15, 0x7d, 0xa4, 0xcc, 0xda, 0x29,
	0xa3, 0x97, 0x9e, 0x9f, 0xac, 0x35, 0xee, 0x43, 0xb5, 0x8d, 0xaf, 0xa3, 0xbe, 0x86, 0x92, 0x35,
	0x28, 0xbb, 0xf2, 0xfd, 0x1c, 0x7f, 0x14, 0x56, 0x69, 0x77, 0x71, 0xaf, 0xdc, 0xf8, 0xa3, 0x04,
	0xc6, 0x19, 0x72, 0xee, 0xd1, 0xa0, 0x87, 0xdf, 0x47, 0xc8, 0x05, 0xd9, 0x83, 0x15, 0x9f, 0x3a,
	0xb6, 0xf0, 0x68, 0x60, 0x95, 0x76, 0x4b, 0x7b, 0x95, 0x27, 0x9b, 0xfb, 0xe9, 0x24, 0xec, 0x9f,
	0xe8, 0x5d, 0xf2, 0x10, 0xc0, 0x55, 0x51, 0x76, 0x83, 0x4b, 0x6a, 0x2d, 0x28, 0xac, 0x95, 0xc5,
	0xb6, 0xc7, 0xfb, 0xe4, 0x01, 0x2c, 0x87, 0xf1, 0xf9, 0xac, 0x45, 0x05, 0xbd, 0x95, 0x85, 0xa6,
	0x02, 0x20, 0x4f, 0x61, 0xdd, 0xb7, 0xb9, 0x68, 0x86, 0x61, 0xdb, 0x16, 0x76, 0x0f, 0x39, 0x8a,
	0xb6, 0x2d, 0xd0, 0xba, 0xa1, 0x0c, 0xb7, 0xb2, 0x86, 0xe7, 0xde, 0x10, 0xb9, 0xb0, 0x87, 0x21,
	0x31, 0xe0, 0xa6, 0x4f, 0xfb, 0x34, 0x12, 0xd6, 0xd2, 0x6e, 0x69, 0x6f, 0x85, 0xd4, 0x60, 0xc9,
	0xa7, 0x7d, 0x2f, 0xb0, 0x6e, 0xee, 0x96, 0xf6, 0xca, 0x72, 0x9b, 0xa3, 0xc3, 0x50, 0x58, 0xcb,
	0xf2, 0xbd, 0xb1, 0x01, 0x75, 0xe5, 0xe8, 0x25, 0x32, 0x6c, 0x86, 0xe1, 0xab, 0x50, 0x46, 0xc5,
	0x1b, 0x5d, 0x80, 0xc9, 0x1b, 0xf9, 0x04, 0xcc, 0xd7, 0x09, 0x48, 0xaf, 0xe9, 0xb4, 0xdc, 0xcf,
	0x1e, 0xa3, 0xc8, 0xd5, 0xaf, 0x0b, 0xb0, 0x3a, 0x4e, 0x2f, 0x0f, 0x69, 0xc0, 0x51, 0x9e, 0x22,
	0xe2, 0xc8, 0xba, 0x6d, 0xe5, 0xa6, 0x4c, 0xd6, 0xa1, 0xca, 0x63, 0xc8, 0x39, 0xfd, 0x0e, 0x03,
	0x95, 0xc7, 0xb2, 0xac, 0x15, 0x57, 0x7d, 0x78, 0xd1, 0x3b, 0x51, 0xf9, 0x2a, 0x93, 0x47, 0x50,
	0x8d, 0x52, 0x85, 0xb7, 0x6e, 0xec, 0x2e, 0x16, 0x67, 0x31, 0xa9, 0xf7, 0x3e, 0x54, 0xa2, 0x49,
	0x52, 0x55, 0x4e, 0xae, 0xcd, 0xfa, 0x16, 0xac, 0x32, 0x99, 0xea, 0xa6, 0xef, 0xeb, 0xcc, 0xab,
	0xc4, 0xad, 0x90, 0x47, 0x50, 0xf3, 0x82, 0x91, 0x27, 0x50, 0xf7, 0x88, 0xca, 0xdf, 0x54, 0xad,
	0xa5, 0xab, 0xae, 0x82, 0xc9, 0xce, 0xb0, 0xc7, 0x59, 0xb0, 0x56, 0x8a, 0xd0, 0xa9, 0x2c, 0x7d,
	0x0a, 0xd5, 0x13, 0x59, 0xa6, 0x26, 0x6f, 0xba, 0x43, 0x2f, 0x90, 0x81, 0xda, 0xf2, 0x21, 0x39,
	0x78, 0x69, 0xce, 0xc1, 0x1b, 0xe7, 0x50, 0x39, 0x8d, 0xf8, 0xa0, 0x45, 0x83, 0x00, 0x1d, 0x31,
	0x95, 0x61, 0xdd, 0x4d, 0xda, 0x72, 0xdc, 0x2e, 0xba, 0x63, 0x67, 0x75, 0x53, 0xc3, 0x04, 0x43,
	0x7a, 0x6d, 0x7b, 0xdc, 0x89, 0x1d, 0x37, 0x7e, 0x37, 0xa0, 0xa2, 0x53, 0x20, 0x67, 0x9d, 0x1c,
	0x80, 0xc1, 0x33, 0xc3, 0xa3, 0x8f, 0xba, 0x93, 0x75, 0x99, 0x1b, 0xb0, 0x03, 0x30, 0xa2, 0x64,
	0xa4, 0x8f, 0x6c, 0xe1, 0x0c, 0xf4, 0x41, 0x76, 0xa6, 0x03, 0x9c, 0x60, 0xc8, 0xc7, 0xb0, 0x96,
	0x2a, 0xe6, 0x45, 0xe8, 0xca, 0x79, 0x88, 0x07, 0xe9, 0xde, 0xcc, 0xcc, 0xc4, 0x30, 0xf2, 0x1c,
	0xcc, 0x94, 0xed, 0x57, 0x11, 0xb2, 0x2b, 0x3d, 0x4a, 0x77, 0x67, 0x9a, 0x2a, 0x14, 0x39, 0x84,
	0xba, 0x43, 0x83, 0x4b, 0x8f, 0x0d, 0xd5, 0xc8, 0x27, 0x61, 0x2e, 0x15, 0x0d, 0x40, 0x6b, 0x1a,
	0x48, 0x3a, 0x70, 0x67, 0x18, 0x6f, 0x9f, 0x61, 0xe0, 0xea, 0xd5, 0x6f, 0x5c, 0x0c, 0x19, 0x3a,
	0xb6, 0x40, 0x57, 0x35, 0x58, 0x61, 0x04, 0xfa, 0x59, 0x47, 0xf0, 0x02, 0xea, 0xda, 0x4f, 0x07,
	0x85, 0x33, 0xc8, 0xf6, 0xe1, 0x5c, 0xeb, 0xc7, 0x50, 0x75, 0x53, 0x44, 0xa8, 0x1b, 0x72, 0x3b,
	0x4f, 0x55, 0x29, 0xaa, 0xdc, 0x87, 0x8a, 0x37, 0x54, 0x0e, 0x7c, 0x6a, 0xbb, 0x56, 0xb9, 0xa8,
	0x03, 0xbb, 0x13, 0x00, 0x79, 0x0a, 0x75, 0xdb, 0x71, 0x30, 0x14, 0xdd, 0xcc, 0x9c, 0xc0, 0x9c,
	0x39, 0xf9, 0x0c, 0xd6, 0x2f, 0x11, 0xdd, 0x53, 0xca, 0x45, 0x26, 0xae, 0x8a, 0xb2, 0x6b, 0x64,
	0xed, 0x3a, 0x05, 0x48, 0x72, 0x04, 0x1b, 0x89, 0x87, 0x38, 0xd8, 0xc4, 0x45, 0x55, 0xb9, 0xf8,
	0x77, 0xb1, 0x8b, 0x0c, 0x54, 0x16, 0xd9, 0x8e, 0x04, 0x75, 0xe8, 0x30, 0xf4, 0x71, 0xe2, 0xa1,
	0x56, 0x54, 0xe4, 0xe6, 0x34, 0x90, 0x1c, 0xc0, 0x2a, 0x26, 0xfa, 0xa6, 0x1b, 0xd3, 0x50, 0xb6,
	0xb7, 0xb3, 0xb6, 0x63, 0x11, 0x3c, 0xf1, 0xb8, 0x48, 0x1a, 0x3a, 0xd6, 0xba, 0xe4, 0x9b, 0xab,
	0xb3, 0x0a, 0x9a, 0x81, 0xc9, 0xf2, 0x84, 0x93, 0x81, 0xb7, 0xcc, 0xa2, 0xf2, 0xa4, 0x19, 0xe1,
	0x00, 0x8c, 0x30, 0x33, 0xca, 0xd6, 0x5a, 0xd1, 0xc8, 0x65, 0xc7, 0x5d, 0x37, 0xff, 0x08, 0x19,
	0xcf, 0x34, 0x3f, 0x99, 0xd1, 0xfc, 0x79, 0x20, 0x79, 0x01, 0xe4, 0x52, 0xd6, 0x2a, 0xbd, 0xc7,
	0xad, 0xba, 0x32, 0xdf, 0xcd, 0x17, 0x26, 0x8f, 0x93, 0x1c, 0x2a, 0xf3, 0xd3, 0xc3, 0x91, 0x87,
	0x3f, 0x58, 0xeb, 0xb3, 0x3a, 0x29, 0xde, 0x27, 0x2f, 0xc1, 0x8a, 0x54, 0xea, 0xd3, 0x4e, 0xce,
	0x84, 0x2d, 0x22, 0x6e, 0x6d, 0x28, 0xdb, 0xff, 0xe5, 0x6c, 0x67, 0xa0, 0xe5, 0xb0, 0xc8, 0xef,
	0xb6, 0x6c, 0xe6, 0x2a, 0x5d, 0xdf, 0x2c, 0x1a, 0x96, 0x8b, 0x14, 0x82, 0xfc, 0x1f, 0x6a, 0xce,
	0xc0, 0x66, 0xfd, 0x71, 0xe7, 0x6c, 0x29, 0x93, 0xf5, 0x5c, 0x86, 0x14, 0x84, 0x7c, 0x08, 0xb5,
	0x4b, 0xe6, 0x4d, 0xc8, 0xc0, 0xb2, 0x8a, 0xfc, 0x77, 0x14, 0x64, 0x42, 0x5f, 0x5c, 0x95, 0xbf,
	0x65, 0x0b, 0xec, 0x53, 0xe6, 0x21, 0xb7, 0x6e, 0x15, 0xd1, 0xd7, 0x59, 0x0e, 0x25, 0xfb, 0x84,
	0x63, 0xe0, 0x26, 0x73, 0xbf, 0x3d, 0x4b, 0x48, 0x52, 0x63, 0x8f, 0xae, 0x27, 0x12, 0xe1, 0xb9,
	0x5d, 0x84, 0x3f, 0x9e, 0x00, 0x48, 0x07, 0xb6, 0xa6, 0x2a, 0xfc, 0x39, 0xa3, 0x51, 0xc8, 0xad,
	0x1d, 0x65, 0xfb, 0xdf, 0x39, 0x65, 0x8e, 0xc1, 0x32, 0xe7, 0x7e, 0x4a, 0x01, 0xad, 0x3b, 0x45,
	0x39, 0xc9, 0x68, 0xe4, 0x4b, 0xb0, 0xd4, 0x97, 0x4f, 0x23, 0xe6, 0x0c, 0x6c, 0x8e, 0x6d, 0x7d,
	0x1b, 0x95, 0xb7, 0xb6, 0xbb, 0x45, 0xf5, 0xee, 0xcc, 0x40, 0x93, 0xa7, 0x40, 0xa2, 0x31, 0x23,
	0xf1, 0xa4, 0x2a, 0xf7, 0x66, 0xa5, 0x4a, 0xe3, 0x48, 0x17, 0x76, 0xd4, 0x01, 0x24, 0xa5, 0xf4,
	0x30, 0xf4, 0xaf, 0x2e, 0xc2, 0x11, 0x15, 0x98, 0x5c, 0x41, 0xad, 0xdd, 0x59, 0xfc, 0xa3, 0xc0,
	0x69, 0x0e, 0x6b, 0x5c, 0x40, 0x2d, 0xbe, 0x73, 0x27, 0x83, 0x93, 0xbf, 0x12, 0xc5, 0x32, 0xbe,
	0x0f, 0x15, 0x36, 0x11, 0x5f, 0x2d, 0x9a, 0xb9, 0x13, 0xa6, 0xd4, 0xb9, 0xf1, 0x4b, 0x05, 0xaa,
	0xc9, 0xad, 0x4b, 0xc9, 0xf5, 0x33, 0x58, 0xe5, 0xd9, 0xcb, 0x98, 0xd6, 0xeb, 0x3b, 0x33, 0xf4,
	0x5a, 0xdf, 0xd8, 0xda, 0xb0, 0x99, 0x15, 0xec, 0xb1, 0x79, 0x7c, 0x86, 0xff, 0x5c, 0x27, 0xdc,
	0x63, 0x2f, 0xff, 0x4c, 0x01, 0xd7, 0xa7, 0xce, 0xe8, 0xe9, 0xbb, 0x8a, 0x76, 0x5e, 0x76, 0x97,
	0xe7, 0xca, 0xee, 0x47, 0x60, 0xa6, 0x64, 0x57, 0x75, 0x8a, 0x16, 0xeb, 0x6b, 0xb4, 0xf7, 0x19,
	0xac, 0x67, 0xb5, 0x57, 0x17, 0xa7, 0x3c, 0x5f, 0x7c, 0xb3, 0xb2, 0xa7, 0xed, 0xaa, 0x45, 0xe2,
	0xdb, 0x2c, 0x40, 0x4a, 0x82, 0x4f, 0x4b, 0x98, 0xb6, 0xaf, 0x15, 0x11, 0xfc, 0xc5, 0x14, 0x4e,
	0x7e, 0x3f, 0x2b, 0x2f, 0xda, 0xde, 0x28, 0xfa, 0x7e, 0xab, 0x00, 0x39, 0x43, 0x60, 0x56, 0xdf,
	0x51, 0x60, 0xf2, 0x44, 0x6f, 0xce, 0x25, 0xfa, 0x87, 0x60, 0x24, 0x44, 0xaf, 0xcf, 0xba, 0x76,
	0x0d, 0xd3, 0x3f, 0x01, 0x23, 0x61, 0x7a, 0x8d, 0x26, 0x7f, 0x8b, 0xea, 0xeb, 0xef, 0x44, 0xf5,
	0xcf, 0xc1, 0x4c, 0x2e, 0x42, 0xe3, 0xef, 0xad, 0x17, 0x59, 0x76, 0x72, 0x28, 0x39, 0x22, 0x61,
	0x01, 0x8b, 0x6e, 0x14, 0x8d, 0x48, 0x11, 0x81, 0xe6, 0x44, 0x63, 0xf3, 0x3d, 0x44, 0x63, 0xeb,
	0x7d, 0x44, 0xc3, 0x7a, 0x2f, 0xd1, 0xb8, 0xf5, 0x97, 0x44, 0xe3, 0x19, 0xd4, 0x33, 0xa2, 0xa1,
	0x13, 0xbe, 0x3d, 0x47, 0x35, 0x1a, 0x3f, 0xab, 0xff, 0x1b, 0x62, 0xae, 0xd7, 0xe9, 0x7f, 0x0c,
	0x55, 0xa6, 0x9f, 0x5b, 0xd4, 0x8d, 0x29, 0xd9, 0xc8, 0x87, 0xd1, 0x4b, 0x21, 0xf4, 0xef, 0x54,
	0xf5, 0x9e, 0x50, 0x4b, 0xfc, 0xa3, 0x39, 0xe5, 0x4a, 0x49, 0xc4, 0x62, 0x51, 0x46, 0xd2, 0x92,
	0xf0, 0xe0, 0xb7, 0xd2, 0x44, 0x23, 0x94, 0xef, 0x1a, 0x94, 0x7b, 0xad, 0xb3, 0xc8, 0x71, 0x90,
	0x73, 0xb3, 0x44, 0x08, 0x18, 0xbd, 0x56, 0x37, 0x08, 0x23, 0xd1, 0xa2, 0x8c, 0x45, 0xa1, 0x30,
	0x17, 0x52, 0x6b, 0xdd, 0x60, 0x64, 0xfb, 0x9e, 0x6b, 0x2e, 0x92, 0x3a, 0xac, 0xf6, 0x5a, 0x71,
	0x60, 0x5f, 0xdb, 0x2c, 0xf0, 0x82, 0xbe, 0x79, 0x83, 0xac, 0x41, 0x2d, 0x59, 0x3c, 0x66, 0x8c,
	0x32, 0x73, 0x29, 0xc6, 0x7d, 0x49, 0x45, 0x33, 0x12, 0x03, 0xca, 0xbc, 0x37, 0xe8, 0x9a, 0x37,
	0x63, 0x87, 0x2d, 0xdf, 0xc3, 0x40, 0x9c, 0x53, 0xfa, 0xca, 0x77, 0xcd, 0xe5, 0x78, 0x4d, 0xff,
	0x2f, 0x14, 0x1b, 0xaf, 0x90, 0x4d, 0x20, 0xbd, 0x56, 0x52, 0x0d, 0x49, 0xd0, 0x1e, 0x43, 0xd7,
	0x2c, 0x1f, 0x3d, 0x7a, 0x7b, 0xb8, 0x00, 0xff, 0x7a, 0x7b, 0xb8, 0x48, 0x4a, 0x47, 0x6f, 0x0f,
	0x17, 0xac, 0x12, 0x6c, 0x3b, 0x74, 0xb8, 0xaf, 0xfe, 0xb6, 0x18, 0x20, 0xc3, 0x4c, 0xfc, 0x3f,
	0x95, 0x4a, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xa8, 0xf0, 0x5f, 0xe3, 0x12, 0x00, 0x00,
}
