// Code generated by protoc-gen-go.
// source: Server.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ResponseCode int32

const (
	ResponseCode_RCSuccess          ResponseCode = 1
	ResponseCode_RCInputCorrupt     ResponseCode = 2
	ResponseCode_RCInputInvalid     ResponseCode = 3
	ResponseCode_RCServerWarning    ResponseCode = 4
	ResponseCode_RCServerError      ResponseCode = 5
	ResponseCode_RCNotAuthorized    ResponseCode = 6
	ResponseCode_RCClientTooOld     ResponseCode = 7
	ResponseCode_RCPaymentError     ResponseCode = 8
	ResponseCode_RCPurchaseRequired ResponseCode = 9
)

var ResponseCode_name = map[int32]string{
	1: "RCSuccess",
	2: "RCInputCorrupt",
	3: "RCInputInvalid",
	4: "RCServerWarning",
	5: "RCServerError",
	6: "RCNotAuthorized",
	7: "RCClientTooOld",
	8: "RCPaymentError",
	9: "RCPurchaseRequired",
}
var ResponseCode_value = map[string]int32{
	"RCSuccess":          1,
	"RCInputCorrupt":     2,
	"RCInputInvalid":     3,
	"RCServerWarning":    4,
	"RCServerError":      5,
	"RCNotAuthorized":    6,
	"RCClientTooOld":     7,
	"RCPaymentError":     8,
	"RCPurchaseRequired": 9,
}

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}
func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}
func (x *ResponseCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseCode_value, data, "ResponseCode")
	if err != nil {
		return err
	}
	*x = ResponseCode(value)
	return nil
}
func (ResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type DebugMessage struct {
	DebugText        []string `protobuf:"bytes,1,rep,name=debugText" json:"debugText,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DebugMessage) Reset()                    { *m = DebugMessage{} }
func (m *DebugMessage) String() string            { return proto.CompactTextString(m) }
func (*DebugMessage) ProtoMessage()               {}
func (*DebugMessage) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *DebugMessage) GetDebugText() []string {
	if m != nil {
		return m.DebugText
	}
	return nil
}

type SessionRequest struct {
	Location             *Location    `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	DeviceInfo           *DeviceInfo  `protobuf:"bytes,2,opt,name=deviceInfo" json:"deviceInfo,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	LastAppDataResetDate *Timestamp   `protobuf:"bytes,4,opt,name=lastAppDataResetDate" json:"lastAppDataResetDate,omitempty"`
	XXX_unrecognized     []byte       `json:"-"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SessionRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SessionRequest) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *SessionRequest) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SessionRequest) GetLastAppDataResetDate() *Timestamp {
	if m != nil {
		return m.LastAppDataResetDate
	}
	return nil
}

type BlitzHereAppOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BlitzHereAppOptions) Reset()                    { *m = BlitzHereAppOptions{} }
func (m *BlitzHereAppOptions) String() string            { return proto.CompactTextString(m) }
func (*BlitzHereAppOptions) ProtoMessage()               {}
func (*BlitzHereAppOptions) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type AppOptions struct {
	BlitzHereOptions *BlitzHereAppOptions `protobuf:"bytes,1,opt,name=blitzHereOptions" json:"blitzHereOptions,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AppOptions) Reset()                    { *m = AppOptions{} }
func (m *AppOptions) String() string            { return proto.CompactTextString(m) }
func (*AppOptions) ProtoMessage()               {}
func (*AppOptions) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *AppOptions) GetBlitzHereOptions() *BlitzHereAppOptions {
	if m != nil {
		return m.BlitzHereOptions
	}
	return nil
}

type SessionResponse struct {
	UserID           *string        `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	SessionToken     *string        `protobuf:"bytes,2,opt,name=sessionToken" json:"sessionToken,omitempty"`
	ServerURL        *string        `protobuf:"bytes,3,opt,name=serverURL" json:"serverURL,omitempty"`
	UserMessages     []*UserMessage `protobuf:"bytes,4,rep,name=userMessages" json:"userMessages,omitempty"`
	UserProfile      *UserProfile   `protobuf:"bytes,5,opt,name=userProfile" json:"userProfile,omitempty"`
	ResetAllAppData  *bool          `protobuf:"varint,6,opt,name=resetAllAppData" json:"resetAllAppData,omitempty"`
	InviteRequest    *UserInvite    `protobuf:"bytes,7,opt,name=inviteRequest" json:"inviteRequest,omitempty"`
	AppOptions       *AppOptions    `protobuf:"bytes,8,opt,name=appOptions" json:"appOptions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SessionResponse) Reset()                    { *m = SessionResponse{} }
func (m *SessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()               {}
func (*SessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *SessionResponse) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *SessionResponse) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *SessionResponse) GetServerURL() string {
	if m != nil && m.ServerURL != nil {
		return *m.ServerURL
	}
	return ""
}

func (m *SessionResponse) GetUserMessages() []*UserMessage {
	if m != nil {
		return m.UserMessages
	}
	return nil
}

func (m *SessionResponse) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *SessionResponse) GetResetAllAppData() bool {
	if m != nil && m.ResetAllAppData != nil {
		return *m.ResetAllAppData
	}
	return false
}

func (m *SessionResponse) GetInviteRequest() *UserInvite {
	if m != nil {
		return m.InviteRequest
	}
	return nil
}

func (m *SessionResponse) GetAppOptions() *AppOptions {
	if m != nil {
		return m.AppOptions
	}
	return nil
}

type PushConnect struct {
	UserID               *string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	LastMessageTimestamp *Timestamp `protobuf:"bytes,2,opt,name=lastMessageTimestamp" json:"lastMessageTimestamp,omitempty"`
	XXX_unrecognized     []byte     `json:"-"`
}

func (m *PushConnect) Reset()                    { *m = PushConnect{} }
func (m *PushConnect) String() string            { return proto.CompactTextString(m) }
func (*PushConnect) ProtoMessage()               {}
func (*PushConnect) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *PushConnect) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *PushConnect) GetLastMessageTimestamp() *Timestamp {
	if m != nil {
		return m.LastMessageTimestamp
	}
	return nil
}

type PushDisconnect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushDisconnect) Reset()                    { *m = PushDisconnect{} }
func (m *PushDisconnect) String() string            { return proto.CompactTextString(m) }
func (*PushDisconnect) ProtoMessage()               {}
func (*PushDisconnect) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

type RequestType struct {
	SessionRequest               *SessionRequest           `protobuf:"bytes,1,opt,name=sessionRequest" json:"sessionRequest,omitempty"`
	UserEventBatch               *UserEventBatch           `protobuf:"bytes,2,opt,name=userEventBatch" json:"userEventBatch,omitempty"`
	UserProfileUpdate            *UserProfileUpdate        `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery             *UserProfileQuery         `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest          *ConfirmationRequest      `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	MessageSendRequestDeprecated *UserMessageUpdate        `protobuf:"bytes,6,opt,name=messageSendRequest_deprecated" json:"messageSendRequest_deprecated,omitempty"`
	MessageFetchRequest          *UserMessageUpdate        `protobuf:"bytes,7,opt,name=messageFetchRequest" json:"messageFetchRequest,omitempty"`
	DebugMessage                 *DebugMessage             `protobuf:"bytes,8,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUpload                  *ImageUpload              `protobuf:"bytes,9,opt,name=imageUpload" json:"imageUpload,omitempty"`
	AcceptInviteRequest          *UserInvite               `protobuf:"bytes,10,opt,name=acceptInviteRequest" json:"acceptInviteRequest,omitempty"`
	FeedPostFetchRequest         *FeedPostFetchRequest     `protobuf:"bytes,11,opt,name=feedPostFetchRequest" json:"feedPostFetchRequest,omitempty"`
	FeedPostUpdateRequest        *FeedPostUpdateRequest    `protobuf:"bytes,12,opt,name=feedPostUpdateRequest" json:"feedPostUpdateRequest,omitempty"`
	AutocompleteRequest          *AutocompleteRequest      `protobuf:"bytes,13,opt,name=autocompleteRequest" json:"autocompleteRequest,omitempty"`
	EntityTagUpdate              *EntityTagList            `protobuf:"bytes,14,opt,name=entityTagUpdate" json:"entityTagUpdate,omitempty"`
	UserSearchRequest            *UserSearchRequest        `protobuf:"bytes,15,opt,name=userSearchRequest" json:"userSearchRequest,omitempty"`
	PushConnect                  *PushConnect              `protobuf:"bytes,16,opt,name=pushConnect" json:"pushConnect,omitempty"`
	PushDisconnect               *PushDisconnect           `protobuf:"bytes,17,opt,name=pushDisconnect" json:"pushDisconnect,omitempty"`
	ConversationRequest          *ConversationRequest      `protobuf:"bytes,18,opt,name=conversationRequest" json:"conversationRequest,omitempty"`
	FetchConversations           *FetchConversations       `protobuf:"bytes,19,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	UserReview                   *UserReview               `protobuf:"bytes,20,opt,name=userReview" json:"userReview,omitempty"`
	UpdateConversationStatus     *UpdateConversationStatus `protobuf:"bytes,21,opt,name=updateConversationStatus" json:"updateConversationStatus,omitempty"`
	UserCardInfo                 *UserCardInfo             `protobuf:"bytes,22,opt,name=userCardInfo" json:"userCardInfo,omitempty"`
	ChargeRequest                *Charge                   `protobuf:"bytes,23,opt,name=chargeRequest" json:"chargeRequest,omitempty"`
	FriendRequest                *FriendUpdate             `protobuf:"bytes,24,opt,name=friendRequest" json:"friendRequest,omitempty"`
	SearchCategories             *SearchCategories         `protobuf:"bytes,25,opt,name=searchCategories" json:"searchCategories,omitempty"`
	SendMessage                  *UserMessage              `protobuf:"bytes,26,opt,name=sendMessage" json:"sendMessage,omitempty"`
	XXX_unrecognized             []byte                    `json:"-"`
}

func (m *RequestType) Reset()                    { *m = RequestType{} }
func (m *RequestType) String() string            { return proto.CompactTextString(m) }
func (*RequestType) ProtoMessage()               {}
func (*RequestType) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *RequestType) GetSessionRequest() *SessionRequest {
	if m != nil {
		return m.SessionRequest
	}
	return nil
}

func (m *RequestType) GetUserEventBatch() *UserEventBatch {
	if m != nil {
		return m.UserEventBatch
	}
	return nil
}

func (m *RequestType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *RequestType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *RequestType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *RequestType) GetMessageSendRequestDeprecated() *UserMessageUpdate {
	if m != nil {
		return m.MessageSendRequestDeprecated
	}
	return nil
}

func (m *RequestType) GetMessageFetchRequest() *UserMessageUpdate {
	if m != nil {
		return m.MessageFetchRequest
	}
	return nil
}

func (m *RequestType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *RequestType) GetImageUpload() *ImageUpload {
	if m != nil {
		return m.ImageUpload
	}
	return nil
}

func (m *RequestType) GetAcceptInviteRequest() *UserInvite {
	if m != nil {
		return m.AcceptInviteRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostFetchRequest() *FeedPostFetchRequest {
	if m != nil {
		return m.FeedPostFetchRequest
	}
	return nil
}

func (m *RequestType) GetFeedPostUpdateRequest() *FeedPostUpdateRequest {
	if m != nil {
		return m.FeedPostUpdateRequest
	}
	return nil
}

func (m *RequestType) GetAutocompleteRequest() *AutocompleteRequest {
	if m != nil {
		return m.AutocompleteRequest
	}
	return nil
}

func (m *RequestType) GetEntityTagUpdate() *EntityTagList {
	if m != nil {
		return m.EntityTagUpdate
	}
	return nil
}

func (m *RequestType) GetUserSearchRequest() *UserSearchRequest {
	if m != nil {
		return m.UserSearchRequest
	}
	return nil
}

func (m *RequestType) GetPushConnect() *PushConnect {
	if m != nil {
		return m.PushConnect
	}
	return nil
}

func (m *RequestType) GetPushDisconnect() *PushDisconnect {
	if m != nil {
		return m.PushDisconnect
	}
	return nil
}

func (m *RequestType) GetConversationRequest() *ConversationRequest {
	if m != nil {
		return m.ConversationRequest
	}
	return nil
}

func (m *RequestType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

func (m *RequestType) GetUserReview() *UserReview {
	if m != nil {
		return m.UserReview
	}
	return nil
}

func (m *RequestType) GetUpdateConversationStatus() *UpdateConversationStatus {
	if m != nil {
		return m.UpdateConversationStatus
	}
	return nil
}

func (m *RequestType) GetUserCardInfo() *UserCardInfo {
	if m != nil {
		return m.UserCardInfo
	}
	return nil
}

func (m *RequestType) GetChargeRequest() *Charge {
	if m != nil {
		return m.ChargeRequest
	}
	return nil
}

func (m *RequestType) GetFriendRequest() *FriendUpdate {
	if m != nil {
		return m.FriendRequest
	}
	return nil
}

func (m *RequestType) GetSearchCategories() *SearchCategories {
	if m != nil {
		return m.SearchCategories
	}
	return nil
}

func (m *RequestType) GetSendMessage() *UserMessage {
	if m != nil {
		return m.SendMessage
	}
	return nil
}

type ServerRequest struct {
	SessionToken     *string      `protobuf:"bytes,1,opt,name=sessionToken" json:"sessionToken,omitempty"`
	RequestType      *RequestType `protobuf:"bytes,2,opt,name=requestType" json:"requestType,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ServerRequest) Reset()                    { *m = ServerRequest{} }
func (m *ServerRequest) String() string            { return proto.CompactTextString(m) }
func (*ServerRequest) ProtoMessage()               {}
func (*ServerRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *ServerRequest) GetSessionToken() string {
	if m != nil && m.SessionToken != nil {
		return *m.SessionToken
	}
	return ""
}

func (m *ServerRequest) GetRequestType() *RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

type ResponseType struct {
	SessionResponse        *SessionResponse        `protobuf:"bytes,1,opt,name=sessionResponse" json:"sessionResponse,omitempty"`
	UserEventBatchResponse *UserEventBatchResponse `protobuf:"bytes,2,opt,name=userEventBatchResponse" json:"userEventBatchResponse,omitempty"`
	UserProfileUpdate      *UserProfileUpdate      `protobuf:"bytes,3,opt,name=userProfileUpdate" json:"userProfileUpdate,omitempty"`
	UserProfileQuery       *UserProfileQuery       `protobuf:"bytes,4,opt,name=userProfileQuery" json:"userProfileQuery,omitempty"`
	ConfirmationRequest    *ConfirmationRequest    `protobuf:"bytes,5,opt,name=confirmationRequest" json:"confirmationRequest,omitempty"`
	UserMessageUpdate      *UserMessageUpdate      `protobuf:"bytes,6,opt,name=userMessageUpdate" json:"userMessageUpdate,omitempty"`
	DebugMessage           *DebugMessage           `protobuf:"bytes,7,opt,name=debugMessage" json:"debugMessage,omitempty"`
	ImageUploadReply       *ImageUpload            `protobuf:"bytes,8,opt,name=imageUploadReply" json:"imageUploadReply,omitempty"`
	AcceptInviteResponse   *UserInvite             `protobuf:"bytes,9,opt,name=acceptInviteResponse" json:"acceptInviteResponse,omitempty"`
	// optional FeedPostFetchResponse  feedPostFetchResponse   = 10; Deprecated
	// optional FeedPostUpdateResponse feedPostUpdateResponse  = 11; Deprecated
	AutocompleteResponse *AutocompleteResponse `protobuf:"bytes,12,opt,name=autocompleteResponse" json:"autocompleteResponse,omitempty"`
	UserSearchResponse   *UserSearchResponse   `protobuf:"bytes,13,opt,name=userSearchResponse" json:"userSearchResponse,omitempty"`
	ConversationResponse *ConversationResponse `protobuf:"bytes,14,opt,name=conversationResponse" json:"conversationResponse,omitempty"`
	FetchConversations   *FetchConversations   `protobuf:"bytes,15,opt,name=fetchConversations" json:"fetchConversations,omitempty"`
	UserCardInfo         *UserCardInfo         `protobuf:"bytes,16,opt,name=userCardInfo" json:"userCardInfo,omitempty"`
	ChargeResponse       *Charge               `protobuf:"bytes,17,opt,name=chargeResponse" json:"chargeResponse,omitempty"`
	FriendResponse       *FriendUpdate         `protobuf:"bytes,18,opt,name=friendResponse" json:"friendResponse,omitempty"`
	SearchCategories     *SearchCategories     `protobuf:"bytes,19,opt,name=searchCategories" json:"searchCategories,omitempty"`
	FeedPostResponse     *FeedPostResponse     `protobuf:"bytes,20,opt,name=feedPostResponse" json:"feedPostResponse,omitempty"`
	PurchaseDescription  *PurchaseDescription  `protobuf:"bytes,21,opt,name=purchaseDescription" json:"purchaseDescription,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *ResponseType) Reset()                    { *m = ResponseType{} }
func (m *ResponseType) String() string            { return proto.CompactTextString(m) }
func (*ResponseType) ProtoMessage()               {}
func (*ResponseType) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *ResponseType) GetSessionResponse() *SessionResponse {
	if m != nil {
		return m.SessionResponse
	}
	return nil
}

func (m *ResponseType) GetUserEventBatchResponse() *UserEventBatchResponse {
	if m != nil {
		return m.UserEventBatchResponse
	}
	return nil
}

func (m *ResponseType) GetUserProfileUpdate() *UserProfileUpdate {
	if m != nil {
		return m.UserProfileUpdate
	}
	return nil
}

func (m *ResponseType) GetUserProfileQuery() *UserProfileQuery {
	if m != nil {
		return m.UserProfileQuery
	}
	return nil
}

func (m *ResponseType) GetConfirmationRequest() *ConfirmationRequest {
	if m != nil {
		return m.ConfirmationRequest
	}
	return nil
}

func (m *ResponseType) GetUserMessageUpdate() *UserMessageUpdate {
	if m != nil {
		return m.UserMessageUpdate
	}
	return nil
}

func (m *ResponseType) GetDebugMessage() *DebugMessage {
	if m != nil {
		return m.DebugMessage
	}
	return nil
}

func (m *ResponseType) GetImageUploadReply() *ImageUpload {
	if m != nil {
		return m.ImageUploadReply
	}
	return nil
}

func (m *ResponseType) GetAcceptInviteResponse() *UserInvite {
	if m != nil {
		return m.AcceptInviteResponse
	}
	return nil
}

func (m *ResponseType) GetAutocompleteResponse() *AutocompleteResponse {
	if m != nil {
		return m.AutocompleteResponse
	}
	return nil
}

func (m *ResponseType) GetUserSearchResponse() *UserSearchResponse {
	if m != nil {
		return m.UserSearchResponse
	}
	return nil
}

func (m *ResponseType) GetConversationResponse() *ConversationResponse {
	if m != nil {
		return m.ConversationResponse
	}
	return nil
}

func (m *ResponseType) GetFetchConversations() *FetchConversations {
	if m != nil {
		return m.FetchConversations
	}
	return nil
}

func (m *ResponseType) GetUserCardInfo() *UserCardInfo {
	if m != nil {
		return m.UserCardInfo
	}
	return nil
}

func (m *ResponseType) GetChargeResponse() *Charge {
	if m != nil {
		return m.ChargeResponse
	}
	return nil
}

func (m *ResponseType) GetFriendResponse() *FriendUpdate {
	if m != nil {
		return m.FriendResponse
	}
	return nil
}

func (m *ResponseType) GetSearchCategories() *SearchCategories {
	if m != nil {
		return m.SearchCategories
	}
	return nil
}

func (m *ResponseType) GetFeedPostResponse() *FeedPostResponse {
	if m != nil {
		return m.FeedPostResponse
	}
	return nil
}

func (m *ResponseType) GetPurchaseDescription() *PurchaseDescription {
	if m != nil {
		return m.PurchaseDescription
	}
	return nil
}

type ServerResponse struct {
	ResponseCode     *ResponseCode `protobuf:"varint,1,opt,name=responseCode,enum=BlitzMessage.ResponseCode" json:"responseCode,omitempty"`
	ResponseMessage  *string       `protobuf:"bytes,2,opt,name=responseMessage" json:"responseMessage,omitempty"`
	ResponseType     *ResponseType `protobuf:"bytes,3,opt,name=responseType" json:"responseType,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ServerResponse) Reset()                    { *m = ServerResponse{} }
func (m *ServerResponse) String() string            { return proto.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()               {}
func (*ServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *ServerResponse) GetResponseCode() ResponseCode {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return ResponseCode_RCSuccess
}

func (m *ServerResponse) GetResponseMessage() string {
	if m != nil && m.ResponseMessage != nil {
		return *m.ResponseMessage
	}
	return ""
}

func (m *ServerResponse) GetResponseType() *ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugMessage)(nil), "BlitzMessage.DebugMessage")
	proto.RegisterType((*SessionRequest)(nil), "BlitzMessage.SessionRequest")
	proto.RegisterType((*BlitzHereAppOptions)(nil), "BlitzMessage.BlitzHereAppOptions")
	proto.RegisterType((*AppOptions)(nil), "BlitzMessage.AppOptions")
	proto.RegisterType((*SessionResponse)(nil), "BlitzMessage.SessionResponse")
	proto.RegisterType((*PushConnect)(nil), "BlitzMessage.PushConnect")
	proto.RegisterType((*PushDisconnect)(nil), "BlitzMessage.PushDisconnect")
	proto.RegisterType((*RequestType)(nil), "BlitzMessage.RequestType")
	proto.RegisterType((*ServerRequest)(nil), "BlitzMessage.ServerRequest")
	proto.RegisterType((*ResponseType)(nil), "BlitzMessage.ResponseType")
	proto.RegisterType((*ServerResponse)(nil), "BlitzMessage.ServerResponse")
	proto.RegisterEnum("BlitzMessage.ResponseCode", ResponseCode_name, ResponseCode_value)
}

var fileDescriptor5 = []byte{
	// 1310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xc6, 0x71, 0x9b, 0xc4, 0xc7, 0x7f, 0xca, 0xda, 0x49, 0xd4, 0xb4, 0x85, 0xd6, 0x30, 0x4c,
	0xa6, 0x94, 0x14, 0x0a, 0x74, 0x18, 0x60, 0x32, 0x24, 0x76, 0x3c, 0xf5, 0x4c, 0xa0, 0xc1, 0x3f,
	0xc3, 0x25, 0xa3, 0x48, 0x6b, 0x5b, 0x20, 0x4b, 0x62, 0x77, 0x15, 0x48, 0x9f, 0x80, 0x1b, 0x9e,
	0x82, 0x37, 0xe1, 0x96, 0xbb, 0x3e, 0x00, 0x77, 0xbc, 0x07, 0xab, 0xd5, 0xca, 0xd6, 0xca, 0xeb,
	0x38, 0xc3, 0x1d, 0x77, 0xd2, 0xee, 0x77, 0x8e, 0xf6, 0xfc, 0x7d, 0x9f, 0x16, 0x2a, 0x03, 0x4c,
	0xae, 0x30, 0x39, 0x0a, 0x49, 0xc0, 0x02, 0x54, 0x39, 0xf5, 0x5c, 0xf6, 0xfa, 0x1b, 0x4c, 0xa9,
	0x35, 0xc1, 0x07, 0xf7, 0x83, 0xcb, 0x1f, 0xb1, 0xcd, 0xdc, 0x2b, 0x6c, 0x7f, 0xe8, 0x60, 0x6a,
	0x13, 0x37, 0x64, 0x81, 0x84, 0x1e, 0x94, 0x87, 0xd7, 0x21, 0xa6, 0xf2, 0xa5, 0xd2, 0xc1, 0x57,
	0xae, 0x8d, 0xe5, 0x9b, 0x71, 0xe6, 0x33, 0x97, 0x5d, 0x0f, 0xad, 0x49, 0xba, 0x0f, 0x5d, 0x8c,
	0x1d, 0xf9, 0x5c, 0xbb, 0xb0, 0xae, 0x67, 0xd8, 0x67, 0x73, 0xdb, 0x01, 0xb6, 0x88, 0x3d, 0x4d,
	0x6d, 0x47, 0x14, 0x93, 0xb3, 0xab, 0xcc, 0x3e, 0x8a, 0x57, 0xe4, 0x91, 0x94, 0xb5, 0x0b, 0x12,
	0x8c, 0x5d, 0x2f, 0x5d, 0x6b, 0x3d, 0x06, 0x7e, 0x8a, 0xcb, 0x68, 0x22, 0xa1, 0x68, 0x07, 0x4a,
	0x4e, 0xfc, 0x3e, 0xc4, 0xbf, 0x32, 0xb3, 0xf0, 0xa8, 0x78, 0x58, 0x6a, 0xfd, 0x55, 0x80, 0xda,
	0x80, 0x6f, 0xbb, 0x81, 0xdf, 0xc7, 0x3f, 0x47, 0x98, 0x32, 0x74, 0x08, 0xdb, 0x5e, 0x60, 0x5b,
	0x8c, 0x2f, 0x71, 0x50, 0xe1, 0xb0, 0xfc, 0x7c, 0xef, 0x28, 0x9b, 0x84, 0xa3, 0x73, 0xb9, 0x8b,
	0x9e, 0x02, 0x38, 0x22, 0xca, 0x9e, 0x3f, 0x0e, 0xcc, 0x0d, 0x81, 0x35, 0x55, 0x6c, 0x67, 0xbe,
	0x8f, 0x9e, 0xc0, 0x56, 0x98, 0x9c, 0xcf, 0x2c, 0x0a, 0xe8, 0x3d, 0x15, 0x9a, 0x09, 0x00, 0x7d,
	0x06, 0x4d, 0xcf, 0xa2, 0xec, 0x24, 0x0c, 0x3b, 0x16, 0xb3, 0xfa, 0x98, 0x62, 0xc6, 0x1f, 0xb0,
	0x79, 0x47, 0x18, 0xee, 0xab, 0x86, 0x43, 0x77, 0xc6, 0xcf, 0x6d, 0xcd, 0xc2, 0xd6, 0x2e, 0x34,
	0xc4, 0xce, 0x4b, 0x4c, 0x30, 0xb7, 0x7d, 0x15, 0xc6, 0xc7, 0xa4, 0xad, 0x1e, 0xc0, 0xe2, 0x0d,
	0x7d, 0x09, 0xc6, 0x65, 0x0a, 0x92, 0x6b, 0x32, 0xce, 0xc7, 0xaa, 0x5f, 0x9d, 0xab, 0x3f, 0x36,
	0xa0, 0x3e, 0xcf, 0x17, 0x0d, 0xf9, 0x12, 0x46, 0x35, 0xd8, 0x8c, 0xf8, 0xd9, 0x7b, 0x1d, 0xe1,
	0xa6, 0x84, 0x9a, 0x50, 0xa1, 0x09, 0x64, 0x18, 0xfc, 0x84, 0x7d, 0x91, 0x98, 0x52, 0x9c, 0x7c,
	0x2a, 0x1a, 0x6b, 0xd4, 0x3f, 0x17, 0x09, 0x28, 0xa1, 0x67, 0x50, 0x89, 0x32, 0x95, 0xe4, 0xd1,
	0x15, 0xf5, 0x69, 0x49, 0x0b, 0x78, 0x04, 0xe5, 0x68, 0x91, 0x25, 0xf3, 0xee, 0xba, 0x34, 0xee,
	0x43, 0x9d, 0xc4, 0xb9, 0x3b, 0xf1, 0x3c, 0x99, 0x4a, 0x73, 0x93, 0xdb, 0x6c, 0xf3, 0x2f, 0x57,
	0x5d, 0xff, 0xca, 0x65, 0x58, 0x16, 0xdd, 0xdc, 0xd2, 0x15, 0x2f, 0x76, 0xd5, 0x13, 0xb0, 0xb8,
	0xd4, 0xd6, 0x3c, 0x0b, 0xe6, 0xb6, 0x0e, 0x9d, 0xc9, 0xd2, 0x10, 0xca, 0x17, 0x11, 0x9d, 0xb6,
	0x03, 0xdf, 0xe7, 0xd3, 0xb2, 0x94, 0x20, 0x59, 0x5d, 0x69, 0x38, 0x2f, 0x9f, 0xec, 0xa0, 0x95,
	0xd5, 0x35, 0xa0, 0x16, 0x7b, 0xed, 0xb8, 0xd4, 0x4e, 0x1c, 0xb7, 0xfe, 0x2e, 0x43, 0x59, 0x46,
	0x10, 0xcf, 0x1e, 0xfa, 0x14, 0x6a, 0x54, 0x69, 0x66, 0x59, 0xd8, 0x07, 0xaa, 0xcb, 0x5c, 0xc3,
	0x73, 0xab, 0x28, 0x1d, 0xb1, 0x53, 0x8b, 0xd9, 0x53, 0x79, 0x90, 0x07, 0xcb, 0xd9, 0x58, 0x60,
	0xd0, 0x17, 0xb0, 0x93, 0xa9, 0xc5, 0x28, 0x74, 0xe2, 0xfe, 0x4c, 0x1a, 0xfb, 0x9d, 0x95, 0x15,
	0x49, 0x60, 0xe8, 0x73, 0x30, 0x32, 0xb6, 0xdf, 0x45, 0x98, 0x5c, 0xcb, 0xd6, 0x7e, 0x7b, 0xa5,
	0xa9, 0x40, 0xa1, 0x63, 0x68, 0xf0, 0xe0, 0xc7, 0x2e, 0x99, 0x89, 0x11, 0x4c, 0xc3, 0xbc, 0xab,
	0xeb, 0xdf, 0xf6, 0x32, 0x10, 0x75, 0xe1, 0xe1, 0x2c, 0xd9, 0x1e, 0x60, 0xdf, 0x91, 0xab, 0x3f,
	0x38, 0x38, 0x24, 0x98, 0x0f, 0x35, 0x76, 0x44, 0x7f, 0x68, 0x23, 0x90, 0xcf, 0x32, 0x82, 0xaf,
	0xa0, 0x21, 0xfd, 0x74, 0x31, 0xcf, 0x86, 0xda, 0x46, 0x6b, 0xad, 0x3f, 0x82, 0x8a, 0x93, 0x21,
	0x26, 0xd9, 0x4f, 0x07, 0x79, 0xea, 0xc8, 0x50, 0x17, 0xef, 0x7c, 0x77, 0x26, 0x1c, 0x78, 0x81,
	0xe5, 0x98, 0x25, 0x5d, 0xe7, 0xf7, 0x16, 0x00, 0xde, 0x62, 0x0d, 0xcb, 0xb6, 0x71, 0xc8, 0x7a,
	0x4a, 0x9b, 0xc3, 0x9a, 0x36, 0xff, 0x1a, 0x9a, 0x63, 0xce, 0xcb, 0x17, 0x01, 0x65, 0x4a, 0x5c,
	0x65, 0x61, 0xd7, 0x52, 0xed, 0xba, 0x1a, 0x24, 0x3a, 0x85, 0xdd, 0xd4, 0x43, 0x12, 0x6c, 0xea,
	0xa2, 0x22, 0x5c, 0xbc, 0xab, 0x77, 0xa1, 0x40, 0xe3, 0x22, 0x5b, 0x11, 0x0b, 0xec, 0x60, 0x16,
	0x7a, 0x78, 0xe1, 0xa1, 0xaa, 0x2b, 0xf2, 0xc9, 0x32, 0x90, 0x37, 0x74, 0x1d, 0xa7, 0x7a, 0x23,
	0x1b, 0xb3, 0x26, 0x6c, 0xef, 0xab, 0xb6, 0x73, 0x51, 0x3a, 0x77, 0xb9, 0x95, 0x6c, 0xe8, 0x44,
	0x7b, 0xd2, 0x6f, 0xd6, 0x57, 0x15, 0x54, 0x81, 0xc5, 0xe5, 0x09, 0x17, 0x03, 0x6f, 0x1a, 0xba,
	0xf2, 0x64, 0x19, 0x81, 0x8f, 0x5c, 0xa8, 0x8c, 0xb2, 0xb9, 0xa3, 0x1b, 0x39, 0x75, 0xdc, 0x65,
	0xf3, 0x73, 0x0a, 0xa5, 0x4a, 0xf3, 0xa3, 0x15, 0xcd, 0x9f, 0x07, 0xf2, 0xa6, 0x45, 0xe3, 0xb8,
	0x56, 0xd9, 0x3d, 0x6a, 0x36, 0x84, 0xf9, 0xa3, 0x7c, 0x61, 0xf2, 0xb8, 0x98, 0x02, 0xe3, 0xfc,
	0xf4, 0xb9, 0xa2, 0xe1, 0x5f, 0xcc, 0xe6, 0xaa, 0x4e, 0x4a, 0xf6, 0xd1, 0x4b, 0x30, 0x23, 0x91,
	0xfa, 0xac, 0x93, 0x01, 0xb3, 0x58, 0x44, 0xcd, 0x5d, 0x61, 0xfb, 0x7e, 0xce, 0x76, 0x05, 0x3a,
	0x1e, 0x96, 0xf8, 0xbb, 0x6d, 0x8b, 0x38, 0x42, 0x67, 0xf7, 0x74, 0xc3, 0x32, 0xca, 0x20, 0xd0,
	0x07, 0x50, 0xb5, 0xa7, 0x16, 0x99, 0xcc, 0x3b, 0x67, 0x5f, 0x98, 0x34, 0x73, 0x19, 0x12, 0x10,
	0xf4, 0x31, 0x54, 0xc7, 0xc4, 0x5d, 0x90, 0x81, 0x69, 0xea, 0xfc, 0x77, 0x05, 0x64, 0x41, 0x5f,
	0x54, 0x94, 0xbf, 0xcd, 0xdf, 0x26, 0x01, 0xdf, 0xa2, 0xe6, 0x3d, 0x1d, 0x7d, 0x0d, 0x72, 0xa8,
	0xb8, 0x4f, 0x28, 0xf7, 0x93, 0xce, 0xfd, 0xc1, 0x2a, 0x01, 0x93, 0xcf, 0xad, 0x11, 0x54, 0x93,
	0xbf, 0xb1, 0xb4, 0x84, 0x79, 0x6d, 0x4d, 0x04, 0x85, 0xbb, 0x25, 0x0b, 0x19, 0x90, 0xf4, 0x9d,
	0x73, 0x9b, 0xd1, 0x89, 0xd6, 0x3f, 0xdb, 0x50, 0x49, 0xe5, 0x5b, 0x08, 0xc7, 0x0b, 0xa8, 0x53,
	0x55, 0xd5, 0xa5, 0x72, 0x3c, 0x5c, 0xa1, 0x1c, 0x52, 0xfa, 0x3b, 0xb0, 0xa7, 0x4a, 0xc7, 0xdc,
	0x3c, 0x39, 0xc3, 0x7b, 0x37, 0x49, 0xc8, 0xdc, 0xcb, 0xff, 0x53, 0x4a, 0xe4, 0xa9, 0x15, 0x66,
	0xbf, 0xad, 0x7c, 0xe4, 0x05, 0x60, 0x6b, 0xad, 0x00, 0x7c, 0x02, 0x46, 0x46, 0x00, 0xfa, 0x38,
	0xf4, 0xae, 0xa5, 0x6c, 0xdc, 0xa0, 0x02, 0x2f, 0xa0, 0xa9, 0xaa, 0x80, 0x2c, 0x4e, 0x69, 0xbd,
	0x0c, 0xa8, 0x04, 0x2c, 0xed, 0x2a, 0x3a, 0x19, 0x38, 0xd1, 0x20, 0x63, 0xaa, 0xc9, 0x92, 0xa9,
	0xb4, 0xaf, 0xea, 0xa8, 0x66, 0xb4, 0x84, 0x8b, 0xbf, 0xaf, 0x12, 0x9d, 0xb4, 0xaf, 0xe9, 0xbe,
	0xdf, 0xd6, 0x20, 0x57, 0x50, 0x5d, 0xfd, 0x96, 0x54, 0x97, 0xa7, 0x1c, 0x63, 0x2d, 0xe5, 0x3c,
	0x85, 0x5a, 0x4a, 0x39, 0xf2, 0xac, 0x3b, 0x37, 0x70, 0xce, 0x73, 0xa8, 0xa5, 0x9c, 0x23, 0xd1,
	0xe8, 0x3f, 0x91, 0x4e, 0xe3, 0x56, 0xa4, 0xc3, 0x2d, 0x53, 0x49, 0x9e, 0x7f, 0xaf, 0xa9, 0xb3,
	0xec, 0xe6, 0x50, 0xf1, 0x88, 0x84, 0x11, 0x77, 0x66, 0x51, 0xdc, 0x91, 0xb7, 0xbd, 0xf8, 0x56,
	0xb4, 0xab, 0x1b, 0x91, 0x8b, 0x65, 0x60, 0xeb, 0x77, 0x71, 0xbb, 0x4a, 0xf8, 0x4b, 0xba, 0xe4,
	0xa9, 0x25, 0xf2, 0xb9, 0x1d, 0x38, 0x09, 0xcd, 0xd4, 0xf2, 0x81, 0xf7, 0x33, 0x08, 0xf9, 0x13,
	0x2f, 0xde, 0xd3, 0x71, 0x49, 0x6e, 0x14, 0x19, 0x57, 0x82, 0xf6, 0x8a, 0xba, 0x1c, 0x66, 0x69,
	0xee, 0xc9, 0x9f, 0x85, 0x05, 0xef, 0x09, 0xdf, 0x55, 0x28, 0xf5, 0xdb, 0x83, 0x88, 0xcf, 0x08,
	0xa5, 0x46, 0x01, 0x21, 0xa8, 0xf5, 0xdb, 0x3d, 0x3f, 0x8c, 0x58, 0x3b, 0x20, 0x24, 0x0a, 0x99,
	0xb1, 0x91, 0x59, 0xe3, 0xc3, 0x61, 0x79, 0xae, 0x63, 0x14, 0x51, 0x03, 0xea, 0xdc, 0x4c, 0x04,
	0xf6, 0xbd, 0x45, 0x7c, 0xd7, 0x9f, 0x18, 0x77, 0xf8, 0x05, 0xa7, 0x9a, 0x2e, 0x9e, 0x11, 0x12,
	0x10, 0xe3, 0x6e, 0x82, 0xfb, 0x36, 0x60, 0x7c, 0x44, 0xa6, 0xbc, 0x16, 0xaf, 0xb1, 0x63, 0x6c,
	0x26, 0x0e, 0xdb, 0x1e, 0x2f, 0x2d, 0x1b, 0x06, 0xc1, 0x2b, 0xcf, 0x31, 0xb6, 0x92, 0x35, 0x79,
	0x0b, 0x4e, 0x8c, 0xb7, 0xd1, 0x1e, 0x20, 0xbe, 0x26, 0xb3, 0x1a, 0x93, 0x8e, 0x4b, 0xb8, 0x7d,
	0xe9, 0xf4, 0xd9, 0x9b, 0xe3, 0x0d, 0x78, 0xeb, 0xcd, 0x71, 0x11, 0x15, 0x4e, 0xf9, 0xa3, 0x59,
	0x80, 0x03, 0x3e, 0x7e, 0x47, 0xe2, 0x4e, 0x37, 0xe5, 0xb7, 0x35, 0x25, 0xfe, 0xdf, 0x0a, 0x85,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xc2, 0xca, 0xe5, 0xd1, 0x0f, 0x00, 0x00,
}
