// Code generated by protoc-gen-go.
// source: Types.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Globals struct {
	SystemUserID     *string `protobuf:"bytes,1,opt,name=SystemUserID,def=E4227250-C8E5-4DA9-8177-F084020910B8" json:"SystemUserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Globals) Reset()                    { *m = Globals{} }
func (m *Globals) String() string            { return proto.CompactTextString(m) }
func (*Globals) ProtoMessage()               {}
func (*Globals) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

const Default_Globals_SystemUserID string = "E4227250-C8E5-4DA9-8177-F084020910B8"

func (m *Globals) GetSystemUserID() string {
	if m != nil && m.SystemUserID != nil {
		return *m.SystemUserID
	}
	return Default_Globals_SystemUserID
}

type Coordinate struct {
	Latitude         *float64 `protobuf:"fixed64,1,opt,name=latitude,def=-360" json:"latitude,omitempty"`
	Longitude        *float64 `protobuf:"fixed64,2,opt,name=longitude,def=-360" json:"longitude,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Coordinate) Reset()                    { *m = Coordinate{} }
func (m *Coordinate) String() string            { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()               {}
func (*Coordinate) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

const Default_Coordinate_Latitude float64 = -360
const Default_Coordinate_Longitude float64 = -360

func (m *Coordinate) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return Default_Coordinate_Latitude
}

func (m *Coordinate) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return Default_Coordinate_Longitude
}

type Size struct {
	Width            *float64 `protobuf:"fixed64,1,opt,name=width,def=0" json:"width,omitempty"`
	Height           *float64 `protobuf:"fixed64,2,opt,name=height,def=0" json:"height,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Size) Reset()                    { *m = Size{} }
func (m *Size) String() string            { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()               {}
func (*Size) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

const Default_Size_Width float64 = 0
const Default_Size_Height float64 = 0

func (m *Size) GetWidth() float64 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return Default_Size_Width
}

func (m *Size) GetHeight() float64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return Default_Size_Height
}

type CoordinateRegion struct {
	Center           *Coordinate `protobuf:"bytes,1,opt,name=center" json:"center,omitempty"`
	Size             *Size       `protobuf:"bytes,2,opt,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CoordinateRegion) Reset()                    { *m = CoordinateRegion{} }
func (m *CoordinateRegion) String() string            { return proto.CompactTextString(m) }
func (*CoordinateRegion) ProtoMessage()               {}
func (*CoordinateRegion) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *CoordinateRegion) GetCenter() *Coordinate {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *CoordinateRegion) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

type CoordinatePolygon struct {
	Points           []*Coordinate `protobuf:"bytes,1,rep,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CoordinatePolygon) Reset()                    { *m = CoordinatePolygon{} }
func (m *CoordinatePolygon) String() string            { return proto.CompactTextString(m) }
func (*CoordinatePolygon) ProtoMessage()               {}
func (*CoordinatePolygon) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *CoordinatePolygon) GetPoints() []*Coordinate {
	if m != nil {
		return m.Points
	}
	return nil
}

type Location struct {
	Coordinate       *Coordinate `protobuf:"bytes,1,opt,name=coordinate" json:"coordinate,omitempty"`
	Altitude         *float64    `protobuf:"fixed64,2,opt,name=altitude" json:"altitude,omitempty"`
	Speed            *float64    `protobuf:"fixed64,3,opt,name=speed" json:"speed,omitempty"`
	Course           *float64    `protobuf:"fixed64,4,opt,name=course" json:"course,omitempty"`
	Placename        *string     `protobuf:"bytes,5,opt,name=placename" json:"placename,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *Location) GetCoordinate() *Coordinate {
	if m != nil {
		return m.Coordinate
	}
	return nil
}

func (m *Location) GetAltitude() float64 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return 0
}

func (m *Location) GetSpeed() float64 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *Location) GetCourse() float64 {
	if m != nil && m.Course != nil {
		return *m.Course
	}
	return 0
}

func (m *Location) GetPlacename() string {
	if m != nil && m.Placename != nil {
		return *m.Placename
	}
	return ""
}

type Timestamp struct {
	Epoch            *float64 `protobuf:"fixed64,1,req,name=epoch" json:"epoch,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *Timestamp) GetEpoch() float64 {
	if m != nil && m.Epoch != nil {
		return *m.Epoch
	}
	return 0
}

type Timespan struct {
	StartTimestamp   *Timestamp `protobuf:"bytes,1,opt,name=startTimestamp" json:"startTimestamp,omitempty"`
	StopTimestamp    *Timestamp `protobuf:"bytes,2,opt,name=stopTimestamp" json:"stopTimestamp,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Timespan) Reset()                    { *m = Timespan{} }
func (m *Timespan) String() string            { return proto.CompactTextString(m) }
func (*Timespan) ProtoMessage()               {}
func (*Timespan) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *Timespan) GetStartTimestamp() *Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

func (m *Timespan) GetStopTimestamp() *Timestamp {
	if m != nil {
		return m.StopTimestamp
	}
	return nil
}

type Void struct {
	DebugString      *string `protobuf:"bytes,1,opt,name=debugString" json:"debugString,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *Void) GetDebugString() string {
	if m != nil && m.DebugString != nil {
		return *m.DebugString
	}
	return ""
}

type KeyValue struct {
	Key              *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Globals)(nil), "BlitzMessage.Globals")
	proto.RegisterType((*Coordinate)(nil), "BlitzMessage.Coordinate")
	proto.RegisterType((*Size)(nil), "BlitzMessage.Size")
	proto.RegisterType((*CoordinateRegion)(nil), "BlitzMessage.CoordinateRegion")
	proto.RegisterType((*CoordinatePolygon)(nil), "BlitzMessage.CoordinatePolygon")
	proto.RegisterType((*Location)(nil), "BlitzMessage.Location")
	proto.RegisterType((*Timestamp)(nil), "BlitzMessage.Timestamp")
	proto.RegisterType((*Timespan)(nil), "BlitzMessage.Timespan")
	proto.RegisterType((*Void)(nil), "BlitzMessage.Void")
	proto.RegisterType((*KeyValue)(nil), "BlitzMessage.KeyValue")
}

var fileDescriptor5 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0xd9, 0xfc, 0x94, 0x64, 0xd2, 0x56, 0xc9, 0x22, 0x51, 0x2b, 0xbd, 0xa9, 0x2c, 0x84,
	0x22, 0x81, 0x53, 0xd7, 0xa4, 0x24, 0x8d, 0x44, 0x25, 0xd2, 0x06, 0x84, 0x00, 0x09, 0x91, 0xd2,
	0x4b, 0xa4, 0x8d, 0x3d, 0x72, 0x96, 0x3a, 0xde, 0xd5, 0xee, 0xa6, 0x28, 0x15, 0x0f, 0xc0, 0xf3,
	0xf5, 0x89, 0x58, 0x3b, 0x51, 0x9d, 0xdc, 0x94, 0x3b, 0x8f, 0xcf, 0x37, 0x73, 0xce, 0x8c, 0x0d,
	0x8d, 0xab, 0xa5, 0x44, 0xdd, 0x95, 0x4a, 0x18, 0x41, 0x77, 0x47, 0x09, 0x37, 0x77, 0x5f, 0x51,
	0x6b, 0x16, 0x63, 0xfb, 0x50, 0x4c, 0x7f, 0x61, 0x68, 0xf8, 0x2d, 0x86, 0x5e, 0x84, 0x3a, 0x54,
	0x5c, 0x1a, 0xa1, 0x56, 0xa8, 0x3b, 0x86, 0xa7, 0x1f, 0x13, 0x31, 0x65, 0x89, 0xa6, 0x43, 0xd8,
	0x9d, 0x2c, 0xb5, 0xc1, 0xf9, 0x0f, 0x8d, 0xea, 0xd3, 0xa5, 0x43, 0x8e, 0x48, 0xa7, 0x3e, 0x7c,
	0x31, 0xee, 0x05, 0x41, 0x3f, 0x38, 0xf5, 0xbd, 0x8b, 0xc1, 0xf8, 0xd4, 0xeb, 0x5d, 0xbe, 0x3f,
	0xf3, 0x06, 0x27, 0xfd, 0xbe, 0xf7, 0xc1, 0x1f, 0xf4, 0xfc, 0xc0, 0x3f, 0x3b, 0xf1, 0x47, 0x03,
	0xf7, 0x1d, 0xc0, 0x85, 0x10, 0x2a, 0xe2, 0x29, 0x33, 0x48, 0x9f, 0x43, 0x2d, 0x61, 0x86, 0x9b,
	0x45, 0x84, 0xf9, 0x14, 0x32, 0xac, 0x78, 0x6f, 0xde, 0xfa, 0xf4, 0x00, 0xea, 0x89, 0x48, 0xe3,
	0x95, 0x50, 0x2a, 0x04, 0xf7, 0x15, 0x54, 0x26, 0xfc, 0x0e, 0x69, 0x13, 0xaa, 0xbf, 0x79, 0x64,
	0x66, 0xeb, 0x2e, 0xe2, 0xd3, 0x16, 0xec, 0xcc, 0x90, 0xc7, 0x33, 0xb3, 0xe6, 0x89, 0xef, 0xfe,
	0x84, 0x66, 0xe1, 0xf5, 0x1d, 0x63, 0x2e, 0x52, 0xda, 0x81, 0x9d, 0x10, 0x53, 0x83, 0x2a, 0xef,
	0x6c, 0x04, 0x4e, 0x77, 0xf3, 0x04, 0xdd, 0x8d, 0x6c, 0x47, 0x50, 0xd1, 0xd6, 0x2a, 0x1f, 0xd7,
	0x08, 0xe8, 0x36, 0x97, 0x85, 0xb0, 0xbb, 0xb4, 0x0a, 0xfe, 0x9b, 0x48, 0x96, 0xf1, 0xca, 0x40,
	0x0a, 0x9e, 0x1a, 0x6d, 0x0d, 0xca, 0x8f, 0x19, 0xb8, 0x7f, 0xa0, 0xf6, 0x45, 0x84, 0x76, 0x7d,
	0xdb, 0xf5, 0x1a, 0x20, 0x7c, 0x50, 0xfe, 0x1b, 0xad, 0x09, 0x35, 0x96, 0x98, 0x8d, 0xeb, 0xd0,
	0x3d, 0xa8, 0x6a, 0x89, 0x18, 0x39, 0xe5, 0xbc, 0xdc, 0xb7, 0x5b, 0x8a, 0x85, 0xd2, 0xe8, 0x54,
	0xf2, 0xba, 0x05, 0x75, 0x99, 0x30, 0xbb, 0x38, 0x9b, 0xa3, 0x53, 0xcd, 0x3e, 0x97, 0xdb, 0x86,
	0xfa, 0x15, 0x9f, 0xa3, 0x36, 0x6c, 0x2e, 0xb3, 0x76, 0x94, 0x22, 0xcc, 0xce, 0x59, 0xea, 0x10,
	0xf7, 0x06, 0x6a, 0xb9, 0x26, 0x59, 0x4a, 0x8f, 0x61, 0xdf, 0x32, 0xca, 0x3c, 0xc0, 0xeb, 0x74,
	0x07, 0xdb, 0xe9, 0x8a, 0x59, 0x5d, 0xd8, 0xd3, 0x46, 0xc8, 0x82, 0x2f, 0x3d, 0xca, 0xbb, 0x87,
	0x50, 0xb9, 0x16, 0x3c, 0xa2, 0xcf, 0xa0, 0x11, 0xe1, 0x74, 0x11, 0x4f, 0x8c, 0xe2, 0x69, 0xbc,
	0xfa, 0xa9, 0xdc, 0x97, 0x50, 0xfb, 0x8c, 0xcb, 0x6b, 0x96, 0x2c, 0x90, 0x36, 0xa0, 0x7c, 0x83,
	0xcb, 0x95, 0x90, 0x25, 0xbe, 0xcd, 0xde, 0xda, 0xe9, 0xe5, 0x4e, 0x7d, 0x74, 0x7c, 0x7f, 0x5e,
	0x82, 0x27, 0xf7, 0xe7, 0x65, 0x4a, 0x46, 0xf6, 0xd1, 0x21, 0xd0, 0x0e, 0xc5, 0xbc, 0x3b, 0xcd,
	0x2c, 0x67, 0xa8, 0x70, 0xcb, 0xfc, 0x2f, 0x21, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x90, 0xa1,
	0xb3, 0xf4, 0x07, 0x03, 0x00, 0x00,
}
