// Code generated by protoc-gen-go.
// source: UserProfiles.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContactType int32

const (
	ContactType_CTUnknown       ContactType = 0
	ContactType_CTPhoneSMS      ContactType = 1
	ContactType_CTEmail         ContactType = 2
	ContactType_CTChat          ContactType = 3
	ContactType_CTSocialService ContactType = 4
)

var ContactType_name = map[int32]string{
	0: "CTUnknown",
	1: "CTPhoneSMS",
	2: "CTEmail",
	3: "CTChat",
	4: "CTSocialService",
}
var ContactType_value = map[string]int32{
	"CTUnknown":       0,
	"CTPhoneSMS":      1,
	"CTEmail":         2,
	"CTChat":          3,
	"CTSocialService": 4,
}

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}
func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}
func (x *ContactType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContactType_value, data, "ContactType")
	if err != nil {
		return err
	}
	*x = ContactType(value)
	return nil
}
func (ContactType) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

type UserStatus int32

const (
	UserStatus_USUnknown    UserStatus = 0
	UserStatus_USBlocked    UserStatus = 1
	UserStatus_USInvited    UserStatus = 2
	UserStatus_USActive     UserStatus = 3
	UserStatus_USConfirming UserStatus = 4
	UserStatus_USConfirmed  UserStatus = 5
)

var UserStatus_name = map[int32]string{
	0: "USUnknown",
	1: "USBlocked",
	2: "USInvited",
	3: "USActive",
	4: "USConfirming",
	5: "USConfirmed",
}
var UserStatus_value = map[string]int32{
	"USUnknown":    0,
	"USBlocked":    1,
	"USInvited":    2,
	"USActive":     3,
	"USConfirming": 4,
	"USConfirmed":  5,
}

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}
func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (x *UserStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserStatus_value, data, "UserStatus")
	if err != nil {
		return err
	}
	*x = UserStatus(value)
	return nil
}
func (UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

type Gender int32

const (
	Gender_GUnknown Gender = 0
	Gender_GFemale  Gender = 1
	Gender_GMale    Gender = 2
	Gender_GOther   Gender = 3
)

var Gender_name = map[int32]string{
	0: "GUnknown",
	1: "GFemale",
	2: "GMale",
	3: "GOther",
}
var Gender_value = map[string]int32{
	"GUnknown": 0,
	"GFemale":  1,
	"GMale":    2,
	"GOther":   3,
}

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}
func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (x *Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gender_value, data, "Gender")
	if err != nil {
		return err
	}
	*x = Gender(value)
	return nil
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

type ImageContent int32

const (
	ImageContent_ICUnknown        ImageContent = 0
	ImageContent_ICUserProfile    ImageContent = 1
	ImageContent_ICUserBackground ImageContent = 2
)

var ImageContent_name = map[int32]string{
	0: "ICUnknown",
	1: "ICUserProfile",
	2: "ICUserBackground",
}
var ImageContent_value = map[string]int32{
	"ICUnknown":        0,
	"ICUserProfile":    1,
	"ICUserBackground": 2,
}

func (x ImageContent) Enum() *ImageContent {
	p := new(ImageContent)
	*p = x
	return p
}
func (x ImageContent) String() string {
	return proto.EnumName(ImageContent_name, int32(x))
}
func (x *ImageContent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ImageContent_value, data, "ImageContent")
	if err != nil {
		return err
	}
	*x = ImageContent(value)
	return nil
}
func (ImageContent) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

type FriendStatus int32

const (
	FriendStatus_FSUnknown  FriendStatus = 0
	FriendStatus_FSDidAsk   FriendStatus = 1
	FriendStatus_FSIgnored  FriendStatus = 2
	FriendStatus_FSAccepted FriendStatus = 3
	FriendStatus_FSWasAsked FriendStatus = 4
	FriendStatus_FSFriends  FriendStatus = 5
)

var FriendStatus_name = map[int32]string{
	0: "FSUnknown",
	1: "FSDidAsk",
	2: "FSIgnored",
	3: "FSAccepted",
	4: "FSWasAsked",
	5: "FSFriends",
}
var FriendStatus_value = map[string]int32{
	"FSUnknown":  0,
	"FSDidAsk":   1,
	"FSIgnored":  2,
	"FSAccepted": 3,
	"FSWasAsked": 4,
	"FSFriends":  5,
}

func (x FriendStatus) Enum() *FriendStatus {
	p := new(FriendStatus)
	*p = x
	return p
}
func (x FriendStatus) String() string {
	return proto.EnumName(FriendStatus_name, int32(x))
}
func (x *FriendStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FriendStatus_value, data, "FriendStatus")
	if err != nil {
		return err
	}
	*x = FriendStatus(value)
	return nil
}
func (FriendStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

type SocialIdentity struct {
	SocialService    *string    `protobuf:"bytes,1,req,name=socialService" json:"socialService,omitempty"`
	SocialID         *string    `protobuf:"bytes,2,opt,name=socialID" json:"socialID,omitempty"`
	UserName         *string    `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	DisplayName      *string    `protobuf:"bytes,4,opt,name=displayName" json:"displayName,omitempty"`
	UserURI          *string    `protobuf:"bytes,5,opt,name=userURI" json:"userURI,omitempty"`
	AuthToken        *string    `protobuf:"bytes,6,opt,name=authToken" json:"authToken,omitempty"`
	AuthExpire       *Timestamp `protobuf:"bytes,7,opt,name=authExpire" json:"authExpire,omitempty"`
	AuthSecret       *string    `protobuf:"bytes,8,opt,name=authSecret" json:"authSecret,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SocialIdentity) Reset()                    { *m = SocialIdentity{} }
func (m *SocialIdentity) String() string            { return proto.CompactTextString(m) }
func (*SocialIdentity) ProtoMessage()               {}
func (*SocialIdentity) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *SocialIdentity) GetSocialService() string {
	if m != nil && m.SocialService != nil {
		return *m.SocialService
	}
	return ""
}

func (m *SocialIdentity) GetSocialID() string {
	if m != nil && m.SocialID != nil {
		return *m.SocialID
	}
	return ""
}

func (m *SocialIdentity) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *SocialIdentity) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *SocialIdentity) GetUserURI() string {
	if m != nil && m.UserURI != nil {
		return *m.UserURI
	}
	return ""
}

func (m *SocialIdentity) GetAuthToken() string {
	if m != nil && m.AuthToken != nil {
		return *m.AuthToken
	}
	return ""
}

func (m *SocialIdentity) GetAuthExpire() *Timestamp {
	if m != nil {
		return m.AuthExpire
	}
	return nil
}

func (m *SocialIdentity) GetAuthSecret() string {
	if m != nil && m.AuthSecret != nil {
		return *m.AuthSecret
	}
	return ""
}

type ContactInfo struct {
	ContactType      *ContactType `protobuf:"varint,1,req,name=contactType,enum=BlitzMessage.ContactType" json:"contactType,omitempty"`
	Contact          *string      `protobuf:"bytes,2,req,name=contact" json:"contact,omitempty"`
	IsVerified       *bool        `protobuf:"varint,3,opt,name=isVerified" json:"isVerified,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ContactInfo) Reset()                    { *m = ContactInfo{} }
func (m *ContactInfo) String() string            { return proto.CompactTextString(m) }
func (*ContactInfo) ProtoMessage()               {}
func (*ContactInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

func (m *ContactInfo) GetContactType() ContactType {
	if m != nil && m.ContactType != nil {
		return *m.ContactType
	}
	return ContactType_CTUnknown
}

func (m *ContactInfo) GetContact() string {
	if m != nil && m.Contact != nil {
		return *m.Contact
	}
	return ""
}

func (m *ContactInfo) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

type Employment struct {
	JobTitle         *string   `protobuf:"bytes,1,opt,name=jobTitle" json:"jobTitle,omitempty"`
	CompanyName      *string   `protobuf:"bytes,2,opt,name=companyName" json:"companyName,omitempty"`
	Location         *string   `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Industry         *string   `protobuf:"bytes,4,opt,name=industry" json:"industry,omitempty"`
	Timespan         *Timespan `protobuf:"bytes,5,opt,name=timespan" json:"timespan,omitempty"`
	Summary          *string   `protobuf:"bytes,6,opt,name=summary" json:"summary,omitempty"`
	IsHeadlineItem   *bool     `protobuf:"varint,7,opt,name=isHeadlineItem" json:"isHeadlineItem,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Employment) Reset()                    { *m = Employment{} }
func (m *Employment) String() string            { return proto.CompactTextString(m) }
func (*Employment) ProtoMessage()               {}
func (*Employment) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *Employment) GetJobTitle() string {
	if m != nil && m.JobTitle != nil {
		return *m.JobTitle
	}
	return ""
}

func (m *Employment) GetCompanyName() string {
	if m != nil && m.CompanyName != nil {
		return *m.CompanyName
	}
	return ""
}

func (m *Employment) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *Employment) GetIndustry() string {
	if m != nil && m.Industry != nil {
		return *m.Industry
	}
	return ""
}

func (m *Employment) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *Employment) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

func (m *Employment) GetIsHeadlineItem() bool {
	if m != nil && m.IsHeadlineItem != nil {
		return *m.IsHeadlineItem
	}
	return false
}

type Education struct {
	SchoolName       *string   `protobuf:"bytes,1,opt,name=schoolName" json:"schoolName,omitempty"`
	Degree           *string   `protobuf:"bytes,2,opt,name=degree" json:"degree,omitempty"`
	Emphasis         *string   `protobuf:"bytes,3,opt,name=emphasis" json:"emphasis,omitempty"`
	Timespan         *Timespan `protobuf:"bytes,4,opt,name=timespan" json:"timespan,omitempty"`
	Summary          *string   `protobuf:"bytes,5,opt,name=summary" json:"summary,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Education) Reset()                    { *m = Education{} }
func (m *Education) String() string            { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()               {}
func (*Education) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{3} }

func (m *Education) GetSchoolName() string {
	if m != nil && m.SchoolName != nil {
		return *m.SchoolName
	}
	return ""
}

func (m *Education) GetDegree() string {
	if m != nil && m.Degree != nil {
		return *m.Degree
	}
	return ""
}

func (m *Education) GetEmphasis() string {
	if m != nil && m.Emphasis != nil {
		return *m.Emphasis
	}
	return ""
}

func (m *Education) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *Education) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

type ImageData struct {
	ImageContent     *ImageContent `protobuf:"varint,1,opt,name=imageContent,enum=BlitzMessage.ImageContent" json:"imageContent,omitempty"`
	ImageBytes       []byte        `protobuf:"bytes,2,opt,name=imageBytes" json:"imageBytes,omitempty"`
	ContentType      *string       `protobuf:"bytes,3,opt,name=contentType" json:"contentType,omitempty"`
	ImageURL         *string       `protobuf:"bytes,4,opt,name=imageURL" json:"imageURL,omitempty"`
	DateAdded        *Timestamp    `protobuf:"bytes,5,opt,name=dateAdded" json:"dateAdded,omitempty"`
	Crc32            *int64        `protobuf:"varint,6,opt,name=crc32" json:"crc32,omitempty"`
	Deleted          *bool         `protobuf:"varint,7,opt,name=deleted" json:"deleted,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ImageData) Reset()                    { *m = ImageData{} }
func (m *ImageData) String() string            { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()               {}
func (*ImageData) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{4} }

func (m *ImageData) GetImageContent() ImageContent {
	if m != nil && m.ImageContent != nil {
		return *m.ImageContent
	}
	return ImageContent_ICUnknown
}

func (m *ImageData) GetImageBytes() []byte {
	if m != nil {
		return m.ImageBytes
	}
	return nil
}

func (m *ImageData) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *ImageData) GetImageURL() string {
	if m != nil && m.ImageURL != nil {
		return *m.ImageURL
	}
	return ""
}

func (m *ImageData) GetDateAdded() *Timestamp {
	if m != nil {
		return m.DateAdded
	}
	return nil
}

func (m *ImageData) GetCrc32() int64 {
	if m != nil && m.Crc32 != nil {
		return *m.Crc32
	}
	return 0
}

func (m *ImageData) GetDeleted() bool {
	if m != nil && m.Deleted != nil {
		return *m.Deleted
	}
	return false
}

type UserReview struct {
	UserID           *string    `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	ReviewerID       *string    `protobuf:"bytes,2,opt,name=reviewerID" json:"reviewerID,omitempty"`
	Timestamp        *Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
	ConversationID   *string    `protobuf:"bytes,4,opt,name=conversationID" json:"conversationID,omitempty"`
	Responsive       *float64   `protobuf:"fixed64,5,opt,name=responsive" json:"responsive,omitempty"`
	Outgoing         *float64   `protobuf:"fixed64,6,opt,name=outgoing" json:"outgoing,omitempty"`
	Recommended      *float64   `protobuf:"fixed64,7,opt,name=recommended" json:"recommended,omitempty"`
	ReviewText       *string    `protobuf:"bytes,8,opt,name=reviewText" json:"reviewText,omitempty"`
	Tags             []string   `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *UserReview) Reset()                    { *m = UserReview{} }
func (m *UserReview) String() string            { return proto.CompactTextString(m) }
func (*UserReview) ProtoMessage()               {}
func (*UserReview) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{5} }

func (m *UserReview) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *UserReview) GetReviewerID() string {
	if m != nil && m.ReviewerID != nil {
		return *m.ReviewerID
	}
	return ""
}

func (m *UserReview) GetTimestamp() *Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *UserReview) GetConversationID() string {
	if m != nil && m.ConversationID != nil {
		return *m.ConversationID
	}
	return ""
}

func (m *UserReview) GetResponsive() float64 {
	if m != nil && m.Responsive != nil {
		return *m.Responsive
	}
	return 0
}

func (m *UserReview) GetOutgoing() float64 {
	if m != nil && m.Outgoing != nil {
		return *m.Outgoing
	}
	return 0
}

func (m *UserReview) GetRecommended() float64 {
	if m != nil && m.Recommended != nil {
		return *m.Recommended
	}
	return 0
}

func (m *UserReview) GetReviewText() string {
	if m != nil && m.ReviewText != nil {
		return *m.ReviewText
	}
	return ""
}

func (m *UserReview) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type UserProfile struct {
	UserID             *string           `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	UserStatus         *UserStatus       `protobuf:"varint,2,opt,name=userStatus,enum=BlitzMessage.UserStatus" json:"userStatus,omitempty"`
	CreationDate       *Timestamp        `protobuf:"bytes,3,opt,name=creationDate" json:"creationDate,omitempty"`
	LastSeen           *Timestamp        `protobuf:"bytes,4,opt,name=lastSeen" json:"lastSeen,omitempty"`
	Name               *string           `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Gender             *Gender           `protobuf:"varint,6,opt,name=gender,enum=BlitzMessage.Gender" json:"gender,omitempty"`
	Birthday           *Timestamp        `protobuf:"bytes,7,opt,name=birthday" json:"birthday,omitempty"`
	Images             []*ImageData      `protobuf:"bytes,8,rep,name=images" json:"images,omitempty"`
	SocialIdentities   []*SocialIdentity `protobuf:"bytes,9,rep,name=socialIdentities" json:"socialIdentities,omitempty"`
	ContactInfo        []*ContactInfo    `protobuf:"bytes,10,rep,name=contactInfo" json:"contactInfo,omitempty"`
	HeadlineEmployment *Employment       `protobuf:"bytes,11,opt,name=headlineEmployment" json:"headlineEmployment,omitempty"`
	Employment         []*Employment     `protobuf:"bytes,12,rep,name=employment" json:"employment,omitempty"`
	Education          []*Education      `protobuf:"bytes,13,rep,name=education" json:"education,omitempty"`
	EntityTags         []*EntityTag      `protobuf:"bytes,14,rep,name=entityTags" json:"entityTags,omitempty"`
	InterestTags       []string          `protobuf:"bytes,15,rep,name=interestTags" json:"interestTags,omitempty"`
	BackgroundSummary  *string           `protobuf:"bytes,16,opt,name=backgroundSummary" json:"backgroundSummary,omitempty"`
	RatingCount        *int32            `protobuf:"varint,17,opt,name=ratingCount" json:"ratingCount,omitempty"`
	RatingResponsive   *float64          `protobuf:"fixed64,18,opt,name=ratingResponsive" json:"ratingResponsive,omitempty"`
	RatingOutgoing     *float64          `protobuf:"fixed64,19,opt,name=ratingOutgoing" json:"ratingOutgoing,omitempty"`
	RatingRecommended  *float64          `protobuf:"fixed64,20,opt,name=ratingRecommended" json:"ratingRecommended,omitempty"`
	ResponseSeconds    *float64          `protobuf:"fixed64,21,opt,name=responseSeconds" json:"responseSeconds,omitempty"`
	Reviews            []*UserReview     `protobuf:"bytes,22,rep,name=reviews" json:"reviews,omitempty"`
	IsExpert           *bool             `protobuf:"varint,23,opt,name=isExpert" json:"isExpert,omitempty"`
	StripeAccount      *string           `protobuf:"bytes,24,opt,name=stripeAccount" json:"stripeAccount,omitempty"`
	IsFree             *bool             `protobuf:"varint,25,opt,name=isFree" json:"isFree,omitempty"`
	XXX_unrecognized   []byte            `json:"-"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{6} }

func (m *UserProfile) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *UserProfile) GetUserStatus() UserStatus {
	if m != nil && m.UserStatus != nil {
		return *m.UserStatus
	}
	return UserStatus_USUnknown
}

func (m *UserProfile) GetCreationDate() *Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *UserProfile) GetLastSeen() *Timestamp {
	if m != nil {
		return m.LastSeen
	}
	return nil
}

func (m *UserProfile) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserProfile) GetGender() Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Gender_GUnknown
}

func (m *UserProfile) GetBirthday() *Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *UserProfile) GetImages() []*ImageData {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *UserProfile) GetSocialIdentities() []*SocialIdentity {
	if m != nil {
		return m.SocialIdentities
	}
	return nil
}

func (m *UserProfile) GetContactInfo() []*ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *UserProfile) GetHeadlineEmployment() *Employment {
	if m != nil {
		return m.HeadlineEmployment
	}
	return nil
}

func (m *UserProfile) GetEmployment() []*Employment {
	if m != nil {
		return m.Employment
	}
	return nil
}

func (m *UserProfile) GetEducation() []*Education {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *UserProfile) GetEntityTags() []*EntityTag {
	if m != nil {
		return m.EntityTags
	}
	return nil
}

func (m *UserProfile) GetInterestTags() []string {
	if m != nil {
		return m.InterestTags
	}
	return nil
}

func (m *UserProfile) GetBackgroundSummary() string {
	if m != nil && m.BackgroundSummary != nil {
		return *m.BackgroundSummary
	}
	return ""
}

func (m *UserProfile) GetRatingCount() int32 {
	if m != nil && m.RatingCount != nil {
		return *m.RatingCount
	}
	return 0
}

func (m *UserProfile) GetRatingResponsive() float64 {
	if m != nil && m.RatingResponsive != nil {
		return *m.RatingResponsive
	}
	return 0
}

func (m *UserProfile) GetRatingOutgoing() float64 {
	if m != nil && m.RatingOutgoing != nil {
		return *m.RatingOutgoing
	}
	return 0
}

func (m *UserProfile) GetRatingRecommended() float64 {
	if m != nil && m.RatingRecommended != nil {
		return *m.RatingRecommended
	}
	return 0
}

func (m *UserProfile) GetResponseSeconds() float64 {
	if m != nil && m.ResponseSeconds != nil {
		return *m.ResponseSeconds
	}
	return 0
}

func (m *UserProfile) GetReviews() []*UserReview {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *UserProfile) GetIsExpert() bool {
	if m != nil && m.IsExpert != nil {
		return *m.IsExpert
	}
	return false
}

func (m *UserProfile) GetStripeAccount() string {
	if m != nil && m.StripeAccount != nil {
		return *m.StripeAccount
	}
	return ""
}

func (m *UserProfile) GetIsFree() bool {
	if m != nil && m.IsFree != nil {
		return *m.IsFree
	}
	return false
}

type ImageUpload struct {
	ImageData        []*ImageData `protobuf:"bytes,1,rep,name=imageData" json:"imageData,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ImageUpload) Reset()                    { *m = ImageUpload{} }
func (m *ImageUpload) String() string            { return proto.CompactTextString(m) }
func (*ImageUpload) ProtoMessage()               {}
func (*ImageUpload) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{7} }

func (m *ImageUpload) GetImageData() []*ImageData {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type UserProfileUpdate struct {
	Profiles         []*UserProfile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserProfileUpdate) Reset()                    { *m = UserProfileUpdate{} }
func (m *UserProfileUpdate) String() string            { return proto.CompactTextString(m) }
func (*UserProfileUpdate) ProtoMessage()               {}
func (*UserProfileUpdate) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{8} }

func (m *UserProfileUpdate) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type UserProfileQuery struct {
	//  Fetch by userID:
	UserIDs []string `protobuf:"bytes,1,rep,name=userIDs" json:"userIDs,omitempty"`
	//  Fetch some demo profiles:
	FetchDemoProfiles *bool `protobuf:"varint,2,opt,name=fetchDemoProfiles" json:"fetchDemoProfiles,omitempty"`
	//  Fetch by tag:
	EntityTagDeprecated *string  `protobuf:"bytes,3,opt,name=entityTag_deprecated" json:"entityTag_deprecated,omitempty"`
	EntityUserID        *string  `protobuf:"bytes,4,opt,name=entityUserID" json:"entityUserID,omitempty"`
	EntityID            *string  `protobuf:"bytes,5,opt,name=entityID" json:"entityID,omitempty"`
	EntityTags          []string `protobuf:"bytes,6,rep,name=entityTags" json:"entityTags,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *UserProfileQuery) Reset()                    { *m = UserProfileQuery{} }
func (m *UserProfileQuery) String() string            { return proto.CompactTextString(m) }
func (*UserProfileQuery) ProtoMessage()               {}
func (*UserProfileQuery) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{9} }

func (m *UserProfileQuery) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

func (m *UserProfileQuery) GetFetchDemoProfiles() bool {
	if m != nil && m.FetchDemoProfiles != nil {
		return *m.FetchDemoProfiles
	}
	return false
}

func (m *UserProfileQuery) GetEntityTagDeprecated() string {
	if m != nil && m.EntityTagDeprecated != nil {
		return *m.EntityTagDeprecated
	}
	return ""
}

func (m *UserProfileQuery) GetEntityUserID() string {
	if m != nil && m.EntityUserID != nil {
		return *m.EntityUserID
	}
	return ""
}

func (m *UserProfileQuery) GetEntityID() string {
	if m != nil && m.EntityID != nil {
		return *m.EntityID
	}
	return ""
}

func (m *UserProfileQuery) GetEntityTags() []string {
	if m != nil {
		return m.EntityTags
	}
	return nil
}

type ConfirmationRequest struct {
	ContactInfo      *ContactInfo `protobuf:"bytes,1,opt,name=contactInfo" json:"contactInfo,omitempty"`
	UserProfile      *UserProfile `protobuf:"bytes,2,opt,name=userProfile" json:"userProfile,omitempty"`
	ConfirmationCode *string      `protobuf:"bytes,3,opt,name=confirmationCode" json:"confirmationCode,omitempty"`
	InviterUserID    *string      `protobuf:"bytes,4,opt,name=inviterUserID" json:"inviterUserID,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConfirmationRequest) Reset()                    { *m = ConfirmationRequest{} }
func (m *ConfirmationRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfirmationRequest) ProtoMessage()               {}
func (*ConfirmationRequest) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{10} }

func (m *ConfirmationRequest) GetContactInfo() *ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *ConfirmationRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *ConfirmationRequest) GetConfirmationCode() string {
	if m != nil && m.ConfirmationCode != nil {
		return *m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmationRequest) GetInviterUserID() string {
	if m != nil && m.InviterUserID != nil {
		return *m.InviterUserID
	}
	return ""
}

type ProfilesFromContactInfo struct {
	Profiles         []*UserProfile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ProfilesFromContactInfo) Reset()                    { *m = ProfilesFromContactInfo{} }
func (m *ProfilesFromContactInfo) String() string            { return proto.CompactTextString(m) }
func (*ProfilesFromContactInfo) ProtoMessage()               {}
func (*ProfilesFromContactInfo) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{11} }

func (m *ProfilesFromContactInfo) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type FriendUpdate struct {
	FriendStatus     *FriendStatus  `protobuf:"varint,1,opt,name=friendStatus,enum=BlitzMessage.FriendStatus" json:"friendStatus,omitempty"`
	FriendID         *string        `protobuf:"bytes,2,opt,name=friendID" json:"friendID,omitempty"`
	Profiles         []*UserProfile `protobuf:"bytes,3,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *FriendUpdate) Reset()                    { *m = FriendUpdate{} }
func (m *FriendUpdate) String() string            { return proto.CompactTextString(m) }
func (*FriendUpdate) ProtoMessage()               {}
func (*FriendUpdate) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{12} }

func (m *FriendUpdate) GetFriendStatus() FriendStatus {
	if m != nil && m.FriendStatus != nil {
		return *m.FriendStatus
	}
	return FriendStatus_FSUnknown
}

func (m *FriendUpdate) GetFriendID() string {
	if m != nil && m.FriendID != nil {
		return *m.FriendID
	}
	return ""
}

func (m *FriendUpdate) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type UserInvite struct {
	UserID           *string        `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	FriendID         *string        `protobuf:"bytes,2,opt,name=friendID" json:"friendID,omitempty"`
	Message          *string        `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	ContactInfo      *ContactInfo   `protobuf:"bytes,4,opt,name=contactInfo" json:"contactInfo,omitempty"`
	Profiles         []*UserProfile `protobuf:"bytes,5,rep,name=profiles" json:"profiles,omitempty"`
	ConfirmationCode *string        `protobuf:"bytes,6,opt,name=confirmationCode" json:"confirmationCode,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserInvite) Reset()                    { *m = UserInvite{} }
func (m *UserInvite) String() string            { return proto.CompactTextString(m) }
func (*UserInvite) ProtoMessage()               {}
func (*UserInvite) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{13} }

func (m *UserInvite) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *UserInvite) GetFriendID() string {
	if m != nil && m.FriendID != nil {
		return *m.FriendID
	}
	return ""
}

func (m *UserInvite) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *UserInvite) GetContactInfo() *ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *UserInvite) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *UserInvite) GetConfirmationCode() string {
	if m != nil && m.ConfirmationCode != nil {
		return *m.ConfirmationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*SocialIdentity)(nil), "BlitzMessage.SocialIdentity")
	proto.RegisterType((*ContactInfo)(nil), "BlitzMessage.ContactInfo")
	proto.RegisterType((*Employment)(nil), "BlitzMessage.Employment")
	proto.RegisterType((*Education)(nil), "BlitzMessage.Education")
	proto.RegisterType((*ImageData)(nil), "BlitzMessage.ImageData")
	proto.RegisterType((*UserReview)(nil), "BlitzMessage.UserReview")
	proto.RegisterType((*UserProfile)(nil), "BlitzMessage.UserProfile")
	proto.RegisterType((*ImageUpload)(nil), "BlitzMessage.ImageUpload")
	proto.RegisterType((*UserProfileUpdate)(nil), "BlitzMessage.UserProfileUpdate")
	proto.RegisterType((*UserProfileQuery)(nil), "BlitzMessage.UserProfileQuery")
	proto.RegisterType((*ConfirmationRequest)(nil), "BlitzMessage.ConfirmationRequest")
	proto.RegisterType((*ProfilesFromContactInfo)(nil), "BlitzMessage.ProfilesFromContactInfo")
	proto.RegisterType((*FriendUpdate)(nil), "BlitzMessage.FriendUpdate")
	proto.RegisterType((*UserInvite)(nil), "BlitzMessage.UserInvite")
	proto.RegisterEnum("BlitzMessage.ContactType", ContactType_name, ContactType_value)
	proto.RegisterEnum("BlitzMessage.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("BlitzMessage.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("BlitzMessage.ImageContent", ImageContent_name, ImageContent_value)
	proto.RegisterEnum("BlitzMessage.FriendStatus", FriendStatus_name, FriendStatus_value)
}

var fileDescriptor9 = []byte{
	// 1438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xdf, 0x72, 0xdb, 0xc4,
	0x17, 0xae, 0xe2, 0x3f, 0xb1, 0xd7, 0x8e, 0xa3, 0xa8, 0x69, 0xa3, 0xe4, 0xd7, 0x8b, 0x8e, 0xe7,
	0x37, 0x43, 0x1b, 0x68, 0x60, 0x0c, 0xc3, 0x0c, 0x5c, 0x74, 0x48, 0x9c, 0x38, 0x78, 0x86, 0xd2,
	0x12, 0xdb, 0x30, 0xc3, 0x0d, 0xa3, 0x48, 0x27, 0xf6, 0x36, 0x96, 0x56, 0x68, 0xd7, 0x69, 0xcd,
	0x30, 0xc3, 0x2d, 0x8f, 0xc0, 0x13, 0x70, 0xc1, 0x03, 0xf0, 0x04, 0xf0, 0x00, 0xf4, 0x11, 0x78,
	0x12, 0xce, 0x9e, 0x95, 0x2c, 0x25, 0x71, 0x13, 0xb8, 0xd3, 0x9e, 0x3d, 0x7b, 0xf6, 0x7c, 0xdf,
	0x39, 0xe7, 0x5b, 0x31, 0x67, 0x24, 0x21, 0x79, 0x91, 0x88, 0x33, 0x3e, 0x05, 0xb9, 0x17, 0x27,
	0x42, 0x09, 0xa7, 0x79, 0x30, 0xe5, 0xea, 0x87, 0x67, 0x20, 0xa5, 0x37, 0x86, 0x9d, 0xff, 0x89,
	0xd3, 0x97, 0xe0, 0x2b, 0x7e, 0x01, 0xfe, 0x93, 0x00, 0xa4, 0x9f, 0xf0, 0x58, 0x89, 0xc4, 0xb8,
	0xee, 0x34, 0x86, 0xf3, 0x38, 0x3b, 0xb7, 0x63, 0x1f, 0x45, 0x8a, 0xab, 0xf9, 0xd0, 0x1b, 0xa7,
	0x96, 0xf6, 0x9f, 0x16, 0x6b, 0x0d, 0x84, 0xcf, 0xbd, 0x69, 0x3f, 0x00, 0xda, 0x74, 0xee, 0xb1,
	0x35, 0x49, 0x96, 0x01, 0x24, 0x17, 0xdc, 0x07, 0xd7, 0x7a, 0xb8, 0xf2, 0xa8, 0xee, 0xd8, 0xac,
	0x66, 0xcc, 0xfd, 0x43, 0x77, 0xe5, 0xa1, 0x65, 0x2c, 0x33, 0xcc, 0xed, 0x4b, 0x2f, 0x04, 0xb7,
	0x44, 0x96, 0xbb, 0xac, 0x11, 0x70, 0x19, 0x4f, 0xbd, 0x39, 0x19, 0xcb, 0x64, 0x5c, 0x67, 0xab,
	0xda, 0x6d, 0x74, 0xd2, 0x77, 0x2b, 0x64, 0xd8, 0x60, 0x75, 0x6f, 0xa6, 0x26, 0x43, 0x71, 0x0e,
	0x91, 0x5b, 0x25, 0xd3, 0xbb, 0x8c, 0x69, 0xd3, 0xd1, 0xeb, 0x98, 0x27, 0xe0, 0xae, 0xa2, 0xad,
	0xd1, 0xd9, 0xda, 0x2b, 0xa2, 0xdc, 0x1b, 0xf2, 0x10, 0xa4, 0xf2, 0xc2, 0xd8, 0x71, 0x8c, 0xf3,
	0x00, 0xfc, 0x04, 0x94, 0x5b, 0xd3, 0x01, 0xda, 0xa7, 0xac, 0xd1, 0x15, 0x91, 0xf2, 0x7c, 0xd5,
	0x8f, 0xce, 0x84, 0xb3, 0xc7, 0x1a, 0xbe, 0x59, 0x6a, 0xf8, 0x84, 0xa0, 0xd5, 0xd9, 0xbe, 0x1c,
	0xb0, 0x9b, 0x3b, 0xe8, 0x1c, 0x53, 0x7f, 0xc4, 0xa6, 0xd1, 0xe2, 0x1d, 0x5c, 0x7e, 0x0d, 0x09,
	0x3f, 0xe3, 0x10, 0x10, 0xba, 0x5a, 0xfb, 0x37, 0x8b, 0xb1, 0xa3, 0x30, 0x9e, 0x8a, 0x79, 0x88,
	0x54, 0x69, 0xf8, 0x2f, 0xc5, 0xe9, 0x90, 0xab, 0xa9, 0xbe, 0x20, 0x85, 0xef, 0x8b, 0x30, 0xf6,
	0x22, 0x03, 0x7f, 0xc1, 0xd2, 0x54, 0xf8, 0x9e, 0xe2, 0x22, 0x4a, 0x59, 0x42, 0x0b, 0x8f, 0x82,
	0x99, 0x54, 0xc9, 0x3c, 0xa5, 0xe8, 0x11, 0xab, 0x29, 0x0d, 0x0f, 0x8f, 0x12, 0x47, 0x8d, 0xce,
	0xfd, 0x25, 0xe0, 0x71, 0x57, 0x27, 0x2a, 0x67, 0x61, 0xe8, 0xe1, 0x51, 0xc3, 0xdc, 0x7d, 0xd6,
	0xe2, 0xf2, 0x73, 0xf0, 0x82, 0x29, 0x8f, 0xa0, 0xaf, 0x20, 0x24, 0xf6, 0x6a, 0xed, 0x1f, 0x59,
	0xfd, 0x28, 0x98, 0x99, 0x7b, 0x35, 0x1a, 0xe9, 0x4f, 0x84, 0x98, 0x52, 0x5e, 0x26, 0xd9, 0x16,
	0xab, 0x06, 0x30, 0x4e, 0xa0, 0x90, 0x27, 0x84, 0xf1, 0xc4, 0x93, 0x5c, 0xa6, 0x79, 0x16, 0xb3,
	0x2a, 0xff, 0xdb, 0xac, 0xa8, 0xc4, 0xed, 0x3f, 0x2c, 0x56, 0xef, 0x87, 0xe8, 0x73, 0xe8, 0x29,
	0xcf, 0xf9, 0x80, 0x35, 0xb9, 0x5e, 0x68, 0xc6, 0x91, 0x39, 0x4a, 0xa0, 0xd5, 0xd9, 0xb9, 0x1c,
	0xac, 0x5f, 0xf0, 0x20, 0xfa, 0xf5, 0xfa, 0x60, 0xae, 0x40, 0x52, 0x82, 0x4d, 0xc3, 0x2e, 0x6d,
	0x53, 0x4d, 0x73, 0x2e, 0xb5, 0xe3, 0xe8, 0xe4, 0x8b, 0x94, 0xcb, 0x5d, 0x56, 0x0f, 0x3c, 0x05,
	0xfb, 0x41, 0x80, 0x85, 0xab, 0xdc, 0xdc, 0x49, 0x6b, 0xac, 0xe2, 0x27, 0xfe, 0x87, 0x1d, 0xe2,
	0xb2, 0xa4, 0x61, 0x04, 0x30, 0x05, 0x85, 0x07, 0x0d, 0x89, 0x7f, 0x61, 0xc5, 0xf5, 0xf8, 0x9d,
	0xc0, 0x05, 0x87, 0x57, 0x9a, 0x32, 0xdd, 0xc9, 0x38, 0x00, 0x86, 0x42, 0xcc, 0x32, 0xa1, 0x1d,
	0xb2, 0xad, 0x64, 0xd7, 0xab, 0x2c, 0x3e, 0xe5, 0x78, 0xc3, 0xf5, 0x58, 0x3b, 0x44, 0x74, 0x01,
	0x89, 0xa4, 0x32, 0x61, 0x8c, 0x72, 0x1e, 0x57, 0xc6, 0x22, 0x92, 0x38, 0xd3, 0x84, 0xc1, 0xd2,
	0x40, 0xc5, 0x4c, 0x8d, 0x05, 0x8f, 0xc6, 0x94, 0xad, 0xa5, 0xf9, 0x48, 0x00, 0xfb, 0x0d, 0x9b,
	0x31, 0x48, 0x33, 0xb6, 0xf2, 0x94, 0x86, 0xf0, 0x3a, 0x9d, 0x0d, 0xa7, 0xc9, 0xca, 0x0a, 0x27,
	0xde, 0xad, 0x3f, 0x2c, 0x61, 0x69, 0xfe, 0xae, 0xb2, 0x46, 0x41, 0x52, 0xae, 0x81, 0x7a, 0x8f,
	0x31, 0xbd, 0x1e, 0x28, 0x4f, 0xcd, 0x0c, 0xf5, 0xad, 0x8e, 0x7b, 0x19, 0xc1, 0x68, 0xb1, 0xef,
	0x3c, 0x61, 0x4d, 0x9c, 0x42, 0x4a, 0x1f, 0x4b, 0x0d, 0xb7, 0x21, 0x7e, 0x8c, 0xc3, 0xe0, 0x49,
	0x35, 0x00, 0xc8, 0x5a, 0xea, 0xad, 0xae, 0x98, 0x75, 0xa4, 0xbb, 0xd5, 0x68, 0xc6, 0xff, 0x59,
	0x75, 0xac, 0x71, 0x26, 0x04, 0xbe, 0xd5, 0xd9, 0xbc, 0x7c, 0xec, 0x98, 0xf6, 0x74, 0xf8, 0x53,
	0x9e, 0xa8, 0x49, 0xe0, 0xcd, 0x6f, 0x13, 0x91, 0x77, 0x58, 0x95, 0x1a, 0x47, 0x22, 0x49, 0xa5,
	0xeb, 0x8e, 0x79, 0xf3, 0x7e, 0xcc, 0x6c, 0x59, 0x14, 0x48, 0x0e, 0x86, 0xc9, 0x46, 0xe7, 0xc1,
	0xe5, 0x23, 0x57, 0x64, 0x34, 0x97, 0x20, 0xad, 0x48, 0x2e, 0xa3, 0x23, 0xcb, 0x25, 0x88, 0x24,
	0xeb, 0x23, 0xe6, 0x4c, 0xd2, 0x31, 0xce, 0x45, 0xc6, 0x6d, 0x10, 0x8a, 0x2b, 0xfc, 0x17, 0x44,
	0x08, 0xab, 0x05, 0xb9, 0x77, 0x93, 0x2e, 0x79, 0xbb, 0x37, 0x36, 0x27, 0x64, 0xa2, 0xe0, 0xae,
	0x2d, 0xc3, 0x9d, 0x6b, 0x06, 0x4a, 0x32, 0x2c, 0x5e, 0x0b, 0xb7, 0xb5, 0xd4, 0x39, 0xdb, 0x77,
	0x36, 0x71, 0xc2, 0x71, 0x34, 0xb1, 0x6b, 0x15, 0xb9, 0xaf, 0xeb, 0x56, 0x73, 0xb6, 0xd9, 0xc6,
	0xa9, 0xe7, 0x9f, 0x8f, 0x13, 0x31, 0x8b, 0x82, 0x41, 0x2a, 0x10, 0x76, 0x26, 0x95, 0x09, 0xde,
	0x13, 0x8d, 0xbb, 0xb8, 0xa7, 0xdc, 0x0d, 0x34, 0x56, 0x1c, 0x97, 0xd9, 0xc6, 0x78, 0x92, 0x77,
	0xbf, 0x43, 0x6d, 0x8d, 0x93, 0x62, 0x76, 0x9e, 0x67, 0x33, 0x70, 0x97, 0xec, 0x78, 0x43, 0x76,
	0x22, 0x9f, 0x84, 0x4d, 0xda, 0xda, 0x62, 0xeb, 0xe9, 0x10, 0x01, 0xbe, 0x14, 0x22, 0x0a, 0xa4,
	0x7b, 0x8f, 0x36, 0x1e, 0xb3, 0x55, 0x33, 0x22, 0xd2, 0xbd, 0xbf, 0x8c, 0xaf, 0xc2, 0xc0, 0x6b,
	0x75, 0x91, 0xf8, 0x28, 0x41, 0xa2, 0xdc, 0x2d, 0xad, 0x08, 0xf4, 0x38, 0x2a, 0x7c, 0x60, 0x61,
	0xdf, 0xf7, 0x29, 0x73, 0x37, 0x13, 0x53, 0x2e, 0x7b, 0x5a, 0x4c, 0xb7, 0x49, 0x38, 0x3e, 0x61,
	0x0d, 0xea, 0xa0, 0x11, 0x52, 0xef, 0x05, 0x9a, 0x77, 0x9e, 0x35, 0x14, 0x8e, 0xd9, 0x4d, 0xfd,
	0xd6, 0xfe, 0x8c, 0x6d, 0x14, 0xc6, 0x73, 0x14, 0x6b, 0x31, 0xc3, 0x62, 0xd4, 0xe2, 0xf4, 0x17,
	0x20, 0x3d, 0xbf, 0x7d, 0x3d, 0xe9, 0xf4, 0x48, 0xfb, 0x17, 0x8b, 0xd9, 0x85, 0xf5, 0x57, 0x33,
	0x48, 0xe6, 0xd9, 0x2b, 0xdc, 0x3f, 0x34, 0x01, 0xa8, 0x38, 0x67, 0xa0, 0xfc, 0xc9, 0x21, 0x84,
	0x22, 0xfb, 0xbd, 0xa0, 0x71, 0xaf, 0x39, 0x0f, 0xd8, 0xe6, 0xa2, 0xf4, 0xdf, 0x05, 0x10, 0xa3,
	0xcc, 0x78, 0x2a, 0x7d, 0x06, 0xeb, 0xba, 0xd6, 0x66, 0x77, 0x64, 0x64, 0xa3, 0xbc, 0x78, 0x3e,
	0xc8, 0x8a, 0x96, 0x4a, 0xa6, 0x62, 0x85, 0x06, 0xaa, 0x92, 0xf8, 0xfc, 0x6a, 0xb1, 0xbb, 0xd8,
	0xf4, 0x67, 0x3c, 0x09, 0xa9, 0xcb, 0x4e, 0xe0, 0xfb, 0x19, 0xf6, 0xcc, 0xd5, 0x61, 0xb1, 0xa8,
	0xeb, 0x6f, 0x18, 0x16, 0xf4, 0x9f, 0xe5, 0x08, 0x29, 0xed, 0x9b, 0x28, 0xd1, 0x9d, 0xe5, 0x17,
	0xae, 0xed, 0x8a, 0x20, 0x7b, 0x40, 0xb0, 0xa0, 0x3c, 0xba, 0xe0, 0xd8, 0xbb, 0x45, 0x38, 0xed,
	0x1e, 0xdb, 0xca, 0x48, 0xe9, 0x25, 0x22, 0x2c, 0xde, 0xfd, 0x9f, 0x6a, 0xf1, 0x13, 0x6b, 0xf6,
	0x12, 0x8e, 0x7d, 0x99, 0x16, 0x12, 0x9f, 0xc2, 0x33, 0x5a, 0xa7, 0xfa, 0xba, 0xf4, 0x29, 0xec,
	0x15, 0x3c, 0x34, 0xb1, 0xe6, 0xc4, 0xe2, 0x89, 0x29, 0x26, 0x50, 0xba, 0x2d, 0x81, 0xdf, 0xd3,
	0x27, 0xac, 0x4f, 0x20, 0xaf, 0xa9, 0xfd, 0xf5, 0xe8, 0xd8, 0x28, 0xa1, 0x89, 0x93, 0x32, 0x74,
	0xa5, 0x36, 0xe5, 0xdb, 0x6a, 0x53, 0x4c, 0xaf, 0x72, 0x4b, 0x7a, 0x4b, 0x0b, 0x43, 0x3f, 0x36,
	0xbb, 0xdf, 0x2e, 0xfe, 0xe8, 0xe8, 0x0f, 0x6d, 0x8d, 0xd5, 0xbb, 0xc3, 0x51, 0x74, 0x1e, 0x89,
	0x57, 0x91, 0x7d, 0x07, 0x71, 0xb0, 0xee, 0xf0, 0xc5, 0x44, 0x44, 0x30, 0x78, 0x36, 0xb0, 0x2d,
	0xa7, 0xc1, 0x56, 0xbb, 0xc3, 0xa3, 0xd0, 0xe3, 0x53, 0x7b, 0x05, 0x1b, 0xaf, 0xda, 0x1d, 0x76,
	0x27, 0x9e, 0xb2, 0x4b, 0x28, 0x34, 0xeb, 0xdd, 0xe1, 0xa0, 0xf8, 0x3f, 0x6b, 0x97, 0x77, 0x5f,
	0x1a, 0x4e, 0x52, 0x86, 0x31, 0xf4, 0x68, 0x90, 0x87, 0xa6, 0xe5, 0x01, 0xfe, 0xb3, 0x9d, 0x43,
	0x80, 0x91, 0x69, 0x69, 0xd8, 0x0b, 0x30, 0x76, 0x93, 0xd5, 0x46, 0x83, 0x7d, 0xfa, 0xdb, 0xc6,
	0xe8, 0x36, 0x6b, 0x8e, 0x06, 0x69, 0x43, 0xa3, 0x0a, 0xd9, 0x65, 0xa4, 0xaf, 0xb1, 0xb0, 0xe0,
	0x81, 0xca, 0xee, 0xa7, 0xac, 0x9a, 0xbe, 0x4e, 0x78, 0xf4, 0x38, 0xbf, 0x06, 0x33, 0x3e, 0xee,
	0x41, 0xe8, 0x4d, 0x01, 0x2f, 0xa9, 0xb3, 0xca, 0xf1, 0x33, 0xfd, 0x49, 0xc9, 0x1f, 0x3f, 0x57,
	0x13, 0x48, 0xec, 0xd2, 0x6e, 0x8f, 0x35, 0x2f, 0xfd, 0x16, 0x61, 0x2e, 0xfd, 0x6e, 0x1e, 0x62,
	0x83, 0xad, 0xe1, 0x32, 0x67, 0x13, 0x03, 0x6d, 0x32, 0xdb, 0x98, 0x0e, 0x16, 0xc2, 0x6b, 0xaf,
	0xec, 0xf2, 0xac, 0x0b, 0x73, 0xc4, 0xbd, 0x02, 0x62, 0x4c, 0xac, 0x37, 0x38, 0xe4, 0xc1, 0xbe,
	0x3c, 0x37, 0x80, 0x7b, 0x83, 0xfe, 0x38, 0x12, 0x09, 0x01, 0x46, 0xa6, 0x7b, 0x08, 0xd8, 0x87,
	0x58, 0x13, 0x50, 0x32, 0xeb, 0x6f, 0x3c, 0x89, 0xce, 0xb8, 0x2e, 0x1b, 0x77, 0x13, 0x5d, 0xda,
	0x95, 0x83, 0xf7, 0xdf, 0x3c, 0x5d, 0x61, 0x77, 0xde, 0x3c, 0x2d, 0x39, 0xd6, 0x01, 0x7e, 0xba,
	0x16, 0xdb, 0x41, 0x65, 0xde, 0x3b, 0xd5, 0x0d, 0x80, 0xa0, 0xe0, 0x52, 0x2b, 0xfc, 0x6c, 0x59,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x57, 0x2e, 0x7e, 0x19, 0xe0, 0x0c, 0x00, 0x00,
}
