// Code generated by protoc-gen-go.
// source: UserMessages.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserMessageType int32

const (
	UserMessageType_MTUnknown      UserMessageType = 0
	UserMessageType_MTSystem       UserMessageType = 1
	UserMessageType_MTConversation UserMessageType = 2
	UserMessageType_MTNotification UserMessageType = 3
)

var UserMessageType_name = map[int32]string{
	0: "MTUnknown",
	1: "MTSystem",
	2: "MTConversation",
	3: "MTNotification",
}
var UserMessageType_value = map[string]int32{
	"MTUnknown":      0,
	"MTSystem":       1,
	"MTConversation": 2,
	"MTNotification": 3,
}

func (x UserMessageType) Enum() *UserMessageType {
	p := new(UserMessageType)
	*p = x
	return p
}
func (x UserMessageType) String() string {
	return proto.EnumName(UserMessageType_name, int32(x))
}
func (x *UserMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserMessageType_value, data, "UserMessageType")
	if err != nil {
		return err
	}
	*x = UserMessageType(value)
	return nil
}
func (UserMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

type UserMessageStatus int32

const (
	UserMessageStatus_MSUnknown  UserMessageStatus = 0
	UserMessageStatus_MSNew      UserMessageStatus = 1
	UserMessageStatus_MSRead     UserMessageStatus = 2
	UserMessageStatus_MSArchived UserMessageStatus = 3
)

var UserMessageStatus_name = map[int32]string{
	0: "MSUnknown",
	1: "MSNew",
	2: "MSRead",
	3: "MSArchived",
}
var UserMessageStatus_value = map[string]int32{
	"MSUnknown":  0,
	"MSNew":      1,
	"MSRead":     2,
	"MSArchived": 3,
}

func (x UserMessageStatus) Enum() *UserMessageStatus {
	p := new(UserMessageStatus)
	*p = x
	return p
}
func (x UserMessageStatus) String() string {
	return proto.EnumName(UserMessageStatus_name, int32(x))
}
func (x *UserMessageStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserMessageStatus_value, data, "UserMessageStatus")
	if err != nil {
		return err
	}
	*x = UserMessageStatus(value)
	return nil
}
func (UserMessageStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

type Conversation struct {
	ConversationID   *string    `protobuf:"bytes,1,opt,name=conversationID" json:"conversationID,omitempty"`
	ParentFeedPostID *string    `protobuf:"bytes,2,opt,name=parentFeedPostID" json:"parentFeedPostID,omitempty"`
	CreationDate     *Timestamp `protobuf:"bytes,3,opt,name=creationDate" json:"creationDate,omitempty"`
	LastActivityDate *Timestamp `protobuf:"bytes,4,opt,name=lastActivityDate" json:"lastActivityDate,omitempty"`
	MemberIDs        []string   `protobuf:"bytes,5,rep,name=memberIDs" json:"memberIDs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Conversation) Reset()                    { *m = Conversation{} }
func (m *Conversation) String() string            { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()               {}
func (*Conversation) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *Conversation) GetConversationID() string {
	if m != nil && m.ConversationID != nil {
		return *m.ConversationID
	}
	return ""
}

func (m *Conversation) GetParentFeedPostID() string {
	if m != nil && m.ParentFeedPostID != nil {
		return *m.ParentFeedPostID
	}
	return ""
}

func (m *Conversation) GetCreationDate() *Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *Conversation) GetLastActivityDate() *Timestamp {
	if m != nil {
		return m.LastActivityDate
	}
	return nil
}

func (m *Conversation) GetMemberIDs() []string {
	if m != nil {
		return m.MemberIDs
	}
	return nil
}

type UserMessage struct {
	MessageID        *string            `protobuf:"bytes,1,opt,name=messageID" json:"messageID,omitempty"`
	SenderID         *string            `protobuf:"bytes,2,opt,name=senderID" json:"senderID,omitempty"`
	ConversationID   *string            `protobuf:"bytes,3,opt,name=conversationID" json:"conversationID,omitempty"`
	Recipients       []string           `protobuf:"bytes,4,rep,name=recipients" json:"recipients,omitempty"`
	CreationDate     *Timestamp         `protobuf:"bytes,5,opt,name=creationDate" json:"creationDate,omitempty"`
	NotificationDate *Timestamp         `protobuf:"bytes,6,opt,name=notificationDate" json:"notificationDate,omitempty"`
	ReadDate         *Timestamp         `protobuf:"bytes,7,opt,name=readDate" json:"readDate,omitempty"`
	MessageType      *UserMessageType   `protobuf:"varint,8,opt,name=messageType,enum=BlitzMessage.UserMessageType" json:"messageType,omitempty"`
	MessageStatus    *UserMessageStatus `protobuf:"varint,9,opt,name=messageStatus,enum=BlitzMessage.UserMessageStatus" json:"messageStatus,omitempty"`
	MessageText      *string            `protobuf:"bytes,10,opt,name=messageText" json:"messageText,omitempty"`
	ActionIcon       *string            `protobuf:"bytes,11,opt,name=actionIcon" json:"actionIcon,omitempty"`
	ActionURL        *string            `protobuf:"bytes,12,opt,name=actionURL" json:"actionURL,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *UserMessage) GetMessageID() string {
	if m != nil && m.MessageID != nil {
		return *m.MessageID
	}
	return ""
}

func (m *UserMessage) GetSenderID() string {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return ""
}

func (m *UserMessage) GetConversationID() string {
	if m != nil && m.ConversationID != nil {
		return *m.ConversationID
	}
	return ""
}

func (m *UserMessage) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *UserMessage) GetCreationDate() *Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *UserMessage) GetNotificationDate() *Timestamp {
	if m != nil {
		return m.NotificationDate
	}
	return nil
}

func (m *UserMessage) GetReadDate() *Timestamp {
	if m != nil {
		return m.ReadDate
	}
	return nil
}

func (m *UserMessage) GetMessageType() UserMessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return UserMessageType_MTUnknown
}

func (m *UserMessage) GetMessageStatus() UserMessageStatus {
	if m != nil && m.MessageStatus != nil {
		return *m.MessageStatus
	}
	return UserMessageStatus_MSUnknown
}

func (m *UserMessage) GetMessageText() string {
	if m != nil && m.MessageText != nil {
		return *m.MessageText
	}
	return ""
}

func (m *UserMessage) GetActionIcon() string {
	if m != nil && m.ActionIcon != nil {
		return *m.ActionIcon
	}
	return ""
}

func (m *UserMessage) GetActionURL() string {
	if m != nil && m.ActionURL != nil {
		return *m.ActionURL
	}
	return ""
}

type UserMessageUpdate struct {
	Timespan         *Timespan      `protobuf:"bytes,1,opt,name=timespan" json:"timespan,omitempty"`
	Messages         []*UserMessage `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserMessageUpdate) Reset()                    { *m = UserMessageUpdate{} }
func (m *UserMessageUpdate) String() string            { return proto.CompactTextString(m) }
func (*UserMessageUpdate) ProtoMessage()               {}
func (*UserMessageUpdate) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{2} }

func (m *UserMessageUpdate) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *UserMessageUpdate) GetMessages() []*UserMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*Conversation)(nil), "BlitzMessage.Conversation")
	proto.RegisterType((*UserMessage)(nil), "BlitzMessage.UserMessage")
	proto.RegisterType((*UserMessageUpdate)(nil), "BlitzMessage.UserMessageUpdate")
	proto.RegisterEnum("BlitzMessage.UserMessageType", UserMessageType_name, UserMessageType_value)
	proto.RegisterEnum("BlitzMessage.UserMessageStatus", UserMessageStatus_name, UserMessageStatus_value)
}

var fileDescriptor8 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x97, 0x86, 0x8e, 0xe4, 0xa4, 0x2b, 0x99, 0x91, 0x86, 0x29, 0x42, 0x4c, 0xbd, 0x2a,
	0x43, 0x2b, 0xa2, 0x17, 0x5c, 0x4e, 0x5a, 0xa9, 0x90, 0x2a, 0x91, 0x09, 0x2d, 0x2d, 0xf7, 0xa9,
	0x73, 0x60, 0x1e, 0x4b, 0x1c, 0xd9, 0x66, 0xa3, 0x3c, 0x01, 0xf7, 0x3c, 0x0b, 0x2f, 0xb2, 0x27,
	0xc2, 0x71, 0x32, 0x9a, 0xc2, 0xd6, 0xdd, 0xb9, 0xc7, 0xff, 0x7f, 0x7c, 0xbe, 0xff, 0x34, 0x40,
	0xe6, 0x0a, 0x65, 0x84, 0x4a, 0x25, 0x5f, 0x50, 0x0d, 0x0b, 0x29, 0xb4, 0x20, 0x9d, 0xf1, 0x05,
	0xd7, 0x3f, 0xea, 0x62, 0xef, 0x99, 0x58, 0x9c, 0x23, 0xd3, 0xfc, 0x12, 0xd9, 0x61, 0x8a, 0x8a,
	0x49, 0x5e, 0x68, 0x21, 0x2b, 0x69, 0x2f, 0x98, 0x2d, 0x8b, 0x1b, 0x5f, 0xff, 0xb7, 0x03, 0x9d,
	0x77, 0x22, 0xbf, 0x44, 0xa9, 0x12, 0xcd, 0x45, 0x4e, 0xf6, 0xa0, 0xcb, 0x1a, 0xbf, 0xa7, 0x13,
	0xea, 0xec, 0x3b, 0x03, 0x9f, 0x50, 0x08, 0x8b, 0x44, 0x62, 0xae, 0xdf, 0x23, 0xa6, 0x1f, 0x85,
	0xd2, 0xe6, 0xa6, 0x65, 0x6f, 0x0e, 0xa1, 0xc3, 0x24, 0x5a, 0xf5, 0x24, 0xd1, 0x48, 0x5d, 0x53,
	0x0d, 0x46, 0x4f, 0x86, 0xcd, 0x89, 0x86, 0x33, 0x9e, 0xa1, 0xd2, 0x49, 0x56, 0x90, 0x37, 0x10,
	0x5e, 0x24, 0x4a, 0x1f, 0x97, 0xe3, 0x71, 0xbd, 0xb4, 0x96, 0x07, 0x9b, 0x2d, 0xbb, 0xe0, 0x67,
	0x98, 0x2d, 0x50, 0x4e, 0x27, 0x8a, 0xb6, 0xf7, 0xdd, 0x81, 0xdf, 0xff, 0xe5, 0x42, 0xd0, 0x88,
	0xa1, 0x92, 0xd8, 0xe3, 0xdf, 0x89, 0x43, 0xf0, 0x14, 0xe6, 0x69, 0xe9, 0xaa, 0x27, 0xfd, 0x9f,
	0xcd, 0xb5, 0x75, 0x02, 0x20, 0x91, 0xf1, 0x82, 0x1b, 0x3c, 0x65, 0x86, 0x71, 0x6f, 0xa1, 0x6a,
	0xdf, 0x4b, 0x95, 0x0b, 0xcd, 0x3f, 0x73, 0xb6, 0xb2, 0x6c, 0x6f, 0xb6, 0xbc, 0x04, 0xcf, 0x3c,
	0x90, 0x5a, 0xe9, 0xc3, 0xcd, 0xd2, 0x11, 0x04, 0x35, 0x5d, 0xb9, 0x3b, 0xea, 0x19, 0x75, 0x77,
	0xf4, 0x7c, 0x5d, 0xdd, 0x48, 0xa3, 0x14, 0x91, 0xb7, 0xb0, 0x53, 0x7b, 0x62, 0x9d, 0xe8, 0x6f,
	0x8a, 0xfa, 0xd6, 0xf5, 0xe2, 0x4e, 0x57, 0x25, 0x23, 0x8f, 0x57, 0x6f, 0xe1, 0x77, 0x4d, 0xe1,
	0x26, 0xa1, 0x84, 0xd9, 0xcc, 0x4c, 0x80, 0x34, 0xb0, 0x35, 0x13, 0x79, 0x55, 0x9b, 0x9f, 0x7e,
	0xa0, 0x9d, 0xb2, 0xd4, 0x3f, 0x87, 0xdd, 0x46, 0xc3, 0x79, 0x91, 0x1a, 0x36, 0x32, 0x00, 0x4f,
	0x97, 0x24, 0x45, 0x92, 0xdb, 0xcd, 0x04, 0xa3, 0xbd, 0x5b, 0x38, 0xcd, 0x2d, 0x79, 0x05, 0x5e,
	0xfd, 0xb4, 0x32, 0x1b, 0x73, 0x8d, 0xf2, 0xe9, 0x9d, 0xd3, 0x1e, 0x7c, 0x82, 0x47, 0xff, 0x22,
	0xef, 0x80, 0x1f, 0xcd, 0xe6, 0xf9, 0xd7, 0x5c, 0x5c, 0xe5, 0xe1, 0x16, 0xe9, 0x80, 0x17, 0xcd,
	0xe2, 0xa5, 0xd2, 0x98, 0x85, 0x8e, 0x41, 0xe8, 0x46, 0xb3, 0xe6, 0x5f, 0x3d, 0x6c, 0x55, 0xb5,
	0x93, 0xc6, 0xde, 0x42, 0xf7, 0x60, 0xba, 0xc6, 0x50, 0x87, 0x52, 0x76, 0x8e, 0x57, 0x9d, 0x7d,
	0x68, 0x47, 0xf1, 0x09, 0x5e, 0x99, 0xb6, 0x00, 0xdb, 0x51, 0x7c, 0x6a, 0xf6, 0x68, 0xda, 0x75,
	0x01, 0xa2, 0xf8, 0x58, 0xb2, 0x33, 0xf3, 0xe1, 0xa5, 0xa1, 0x3b, 0x7e, 0x7d, 0x7d, 0xd4, 0x82,
	0xad, 0xeb, 0x23, 0x97, 0x38, 0x63, 0x73, 0xa4, 0x0e, 0xf4, 0x98, 0xc8, 0x86, 0x8b, 0x12, 0xe9,
	0x0c, 0x25, 0xae, 0xc1, 0xfd, 0x74, 0x9c, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x49, 0x91,
	0xb7, 0xda, 0x03, 0x00, 0x00,
}
