// Code generated by protoc-gen-go.
// source: UserMessages.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UserMessageType int32

const (
	UserMessageType_MTUnknown      UserMessageType = 0
	UserMessageType_MTSystem       UserMessageType = 1
	UserMessageType_MTNotification UserMessageType = 2
)

var UserMessageType_name = map[int32]string{
	0: "MTUnknown",
	1: "MTSystem",
	2: "MTNotification",
}
var UserMessageType_value = map[string]int32{
	"MTUnknown":      0,
	"MTSystem":       1,
	"MTNotification": 2,
}

func (x UserMessageType) Enum() *UserMessageType {
	p := new(UserMessageType)
	*p = x
	return p
}
func (x UserMessageType) String() string {
	return proto.EnumName(UserMessageType_name, int32(x))
}
func (x *UserMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserMessageType_value, data, "UserMessageType")
	if err != nil {
		return err
	}
	*x = UserMessageType(value)
	return nil
}
func (UserMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

type UserMessageStatus int32

const (
	UserMessageStatus_MSNew    UserMessageStatus = 0
	UserMessageStatus_MSHidden UserMessageStatus = 1
	UserMessageStatus_MSRead   UserMessageStatus = 2
)

var UserMessageStatus_name = map[int32]string{
	0: "MSNew",
	1: "MSHidden",
	2: "MSRead",
}
var UserMessageStatus_value = map[string]int32{
	"MSNew":    0,
	"MSHidden": 1,
	"MSRead":   2,
}

func (x UserMessageStatus) Enum() *UserMessageStatus {
	p := new(UserMessageStatus)
	*p = x
	return p
}
func (x UserMessageStatus) String() string {
	return proto.EnumName(UserMessageStatus_name, int32(x))
}
func (x *UserMessageStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserMessageStatus_value, data, "UserMessageStatus")
	if err != nil {
		return err
	}
	*x = UserMessageStatus(value)
	return nil
}
func (UserMessageStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

type UserMessage struct {
	MessageID        *string            `protobuf:"bytes,1,opt,name=messageID" json:"messageID,omitempty"`
	SenderID         *string            `protobuf:"bytes,2,opt,name=senderID" json:"senderID,omitempty"`
	Recipients       []string           `protobuf:"bytes,3,rep,name=recipients" json:"recipients,omitempty"`
	CreationDate     *Timestamp         `protobuf:"bytes,4,opt,name=creationDate" json:"creationDate,omitempty"`
	NotificationDate *Timestamp         `protobuf:"bytes,5,opt,name=notificationDate" json:"notificationDate,omitempty"`
	ReadDate         *Timestamp         `protobuf:"bytes,6,opt,name=readDate" json:"readDate,omitempty"`
	MessageType      *UserMessageType   `protobuf:"varint,7,opt,name=messageType,enum=BlitzMessage.UserMessageType" json:"messageType,omitempty"`
	MessageText      *string            `protobuf:"bytes,8,opt,name=messageText" json:"messageText,omitempty"`
	MessageStatus    *UserMessageStatus `protobuf:"varint,9,opt,name=messageStatus,enum=BlitzMessage.UserMessageStatus" json:"messageStatus,omitempty"`
	ActionIcon       *string            `protobuf:"bytes,10,opt,name=actionIcon" json:"actionIcon,omitempty"`
	ActionURL        *string            `protobuf:"bytes,11,opt,name=actionURL" json:"actionURL,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UserMessage) Reset()                    { *m = UserMessage{} }
func (m *UserMessage) String() string            { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()               {}
func (*UserMessage) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

func (m *UserMessage) GetMessageID() string {
	if m != nil && m.MessageID != nil {
		return *m.MessageID
	}
	return ""
}

func (m *UserMessage) GetSenderID() string {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return ""
}

func (m *UserMessage) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *UserMessage) GetCreationDate() *Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *UserMessage) GetNotificationDate() *Timestamp {
	if m != nil {
		return m.NotificationDate
	}
	return nil
}

func (m *UserMessage) GetReadDate() *Timestamp {
	if m != nil {
		return m.ReadDate
	}
	return nil
}

func (m *UserMessage) GetMessageType() UserMessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return UserMessageType_MTUnknown
}

func (m *UserMessage) GetMessageText() string {
	if m != nil && m.MessageText != nil {
		return *m.MessageText
	}
	return ""
}

func (m *UserMessage) GetMessageStatus() UserMessageStatus {
	if m != nil && m.MessageStatus != nil {
		return *m.MessageStatus
	}
	return UserMessageStatus_MSNew
}

func (m *UserMessage) GetActionIcon() string {
	if m != nil && m.ActionIcon != nil {
		return *m.ActionIcon
	}
	return ""
}

func (m *UserMessage) GetActionURL() string {
	if m != nil && m.ActionURL != nil {
		return *m.ActionURL
	}
	return ""
}

type UserMessageUpdate struct {
	Timespan         *Timespan      `protobuf:"bytes,1,opt,name=timespan" json:"timespan,omitempty"`
	Messages         []*UserMessage `protobuf:"bytes,2,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserMessageUpdate) Reset()                    { *m = UserMessageUpdate{} }
func (m *UserMessageUpdate) String() string            { return proto.CompactTextString(m) }
func (*UserMessageUpdate) ProtoMessage()               {}
func (*UserMessageUpdate) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *UserMessageUpdate) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *UserMessageUpdate) GetMessages() []*UserMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMessage)(nil), "BlitzMessage.UserMessage")
	proto.RegisterType((*UserMessageUpdate)(nil), "BlitzMessage.UserMessageUpdate")
	proto.RegisterEnum("BlitzMessage.UserMessageType", UserMessageType_name, UserMessageType_value)
	proto.RegisterEnum("BlitzMessage.UserMessageStatus", UserMessageStatus_name, UserMessageStatus_value)
}

var fileDescriptor8 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x6e, 0xd4, 0x30,
	0x14, 0x85, 0x9b, 0x84, 0x96, 0xe4, 0x66, 0x5a, 0x52, 0x23, 0x81, 0x19, 0x84, 0xa8, 0xba, 0x2a,
	0x45, 0x0d, 0x22, 0x0b, 0xc4, 0xaa, 0x8b, 0xa8, 0x0b, 0x2a, 0x91, 0x2e, 0x9a, 0xe4, 0x01, 0x52,
	0xe7, 0x02, 0x2e, 0xc4, 0x8e, 0x6c, 0x43, 0x19, 0x9e, 0x80, 0xe7, 0x9b, 0xd7, 0x61, 0x83, 0xf3,
	0x83, 0x26, 0x83, 0x3a, 0xb3, 0xb3, 0x4e, 0xce, 0x3d, 0x39, 0xdf, 0xbd, 0x40, 0x4a, 0x8d, 0x2a,
	0x43, 0xad, 0xab, 0xcf, 0xa8, 0xe3, 0x56, 0x49, 0x23, 0xc9, 0x2c, 0xfd, 0xc6, 0xcd, 0xaf, 0x51,
	0x9c, 0x3f, 0x97, 0x37, 0xb7, 0xc8, 0x0c, 0xff, 0x81, 0xec, 0xac, 0x46, 0xcd, 0x14, 0x6f, 0x8d,
	0x54, 0x83, 0x75, 0x1e, 0x16, 0x8b, 0xf6, 0xdf, 0xdc, 0xf1, 0x1f, 0x17, 0xc2, 0x49, 0x1c, 0x39,
	0x84, 0xa0, 0x19, 0x9e, 0x97, 0x17, 0xd4, 0x39, 0x72, 0x4e, 0x02, 0x12, 0x81, 0xaf, 0x51, 0xd4,
	0xa8, 0xac, 0xe2, 0xf6, 0x0a, 0x01, 0x50, 0xc8, 0x78, 0xcb, 0x51, 0x18, 0x4d, 0xbd, 0x23, 0xcf,
	0x6a, 0x67, 0x30, 0x63, 0x0a, 0x2b, 0xc3, 0xa5, 0xb8, 0xa8, 0x0c, 0xd2, 0x07, 0xd6, 0x19, 0x26,
	0x4f, 0xe3, 0x69, 0xaf, 0xb8, 0xe0, 0x36, 0xdc, 0x54, 0x4d, 0x4b, 0xde, 0x42, 0x24, 0xa4, 0xe1,
	0x9f, 0x38, 0x5b, 0x8d, 0xec, 0x6e, 0x1f, 0x79, 0x05, 0xbe, 0xfd, 0x41, 0xdd, 0x5b, 0xf7, 0xb6,
	0x5b, 0x13, 0x08, 0x47, 0x8a, 0x8e, 0x95, 0x3e, 0xb4, 0xee, 0x83, 0xe4, 0xc5, 0xba, 0x7b, 0x42,
	0xdd, 0x99, 0xc8, 0xe3, 0xd5, 0x0c, 0xfe, 0x34, 0xd4, 0xef, 0x49, 0xdf, 0xc1, 0xfe, 0x28, 0xe6,
	0xa6, 0x32, 0xdf, 0x35, 0x0d, 0xfa, 0xa8, 0x97, 0x1b, 0xa3, 0x06, 0x5b, 0xb7, 0xa1, 0x8a, 0x75,
	0x60, 0x97, 0x4c, 0x0a, 0x0a, 0x7d, 0x96, 0x5d, 0xed, 0xa0, 0x95, 0xd7, 0x1f, 0x69, 0xd8, 0x49,
	0xc7, 0xb7, 0x70, 0x38, 0x99, 0x2d, 0xdb, 0xda, 0xb2, 0x91, 0x13, 0xf0, 0x4d, 0x47, 0xd2, 0x56,
	0xa2, 0xbf, 0x40, 0x98, 0x3c, 0xb9, 0x87, 0xd3, 0x7e, 0x25, 0xaf, 0xc1, 0x1f, 0xdb, 0x69, 0x7b,
	0x19, 0xcf, 0x3a, 0x9f, 0x6d, 0x2c, 0x76, 0x9a, 0xc2, 0xa3, 0xff, 0x91, 0xf7, 0x21, 0xc8, 0x8a,
	0x52, 0x7c, 0x15, 0xf2, 0x4e, 0x44, 0x3b, 0x64, 0x06, 0x7e, 0x56, 0xe4, 0x0b, 0x6d, 0xb0, 0x89,
	0x1c, 0x8b, 0x70, 0x90, 0x15, 0x57, 0x93, 0x1b, 0x45, 0xee, 0xe9, 0xfb, 0xb5, 0xbe, 0x23, 0x6b,
	0x00, 0xbb, 0x59, 0x7e, 0x85, 0x77, 0x63, 0x42, 0xfe, 0x81, 0xd7, 0x35, 0x0a, 0x9b, 0x00, 0xb0,
	0x97, 0xe5, 0xd7, 0xf6, 0x64, 0x91, 0x9b, 0xbe, 0x59, 0x9e, 0xbb, 0xb0, 0xb3, 0x3c, 0xf7, 0x88,
	0x93, 0xda, 0x27, 0x75, 0x60, 0xce, 0x64, 0x13, 0xdf, 0x74, 0x6d, 0xbf, 0xa0, 0xc2, 0xb5, 0xde,
	0xbf, 0x1d, 0xe7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0x80, 0xf3, 0xfc, 0xe5, 0x02, 0x00,
	0x00,
}
