// Code generated by protoc-gen-go.
// source: UserProfiles.proto
// DO NOT EDIT!

package BlitzMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"


// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContactType int32

const (
	ContactType_CTUnknown       ContactType = 0
	ContactType_CTPhoneSMS      ContactType = 1
	ContactType_CTEmail         ContactType = 2
	ContactType_CTChat          ContactType = 3
	ContactType_CTSocialService ContactType = 4
)

var ContactType_name = map[int32]string{
	0: "CTUnknown",
	1: "CTPhoneSMS",
	2: "CTEmail",
	3: "CTChat",
	4: "CTSocialService",
}
var ContactType_value = map[string]int32{
	"CTUnknown":       0,
	"CTPhoneSMS":      1,
	"CTEmail":         2,
	"CTChat":          3,
	"CTSocialService": 4,
}

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}
func (x ContactType) String() string {
	return proto.EnumName(ContactType_name, int32(x))
}
func (x *ContactType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ContactType_value, data, "ContactType")
	if err != nil {
		return err
	}
	*x = ContactType(value)
	return nil
}
func (ContactType) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

type UserStatus int32

const (
	UserStatus_USUnknown    UserStatus = 0
	UserStatus_USBlocked    UserStatus = 1
	UserStatus_USInvited    UserStatus = 2
	UserStatus_USActive     UserStatus = 3
	UserStatus_USConfirming UserStatus = 4
	UserStatus_USConfirmed  UserStatus = 5
)

var UserStatus_name = map[int32]string{
	0: "USUnknown",
	1: "USBlocked",
	2: "USInvited",
	3: "USActive",
	4: "USConfirming",
	5: "USConfirmed",
}
var UserStatus_value = map[string]int32{
	"USUnknown":    0,
	"USBlocked":    1,
	"USInvited":    2,
	"USActive":     3,
	"USConfirming": 4,
	"USConfirmed":  5,
}

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}
func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}
func (x *UserStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserStatus_value, data, "UserStatus")
	if err != nil {
		return err
	}
	*x = UserStatus(value)
	return nil
}
func (UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

type Gender int32

const (
	Gender_GUnknown Gender = 0
	Gender_GFemale  Gender = 1
	Gender_GMale    Gender = 2
	Gender_GOther   Gender = 3
)

var Gender_name = map[int32]string{
	0: "GUnknown",
	1: "GFemale",
	2: "GMale",
	3: "GOther",
}
var Gender_value = map[string]int32{
	"GUnknown": 0,
	"GFemale":  1,
	"GMale":    2,
	"GOther":   3,
}

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}
func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}
func (x *Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gender_value, data, "Gender")
	if err != nil {
		return err
	}
	*x = Gender(value)
	return nil
}
func (Gender) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

type ImageContent int32

const (
	ImageContent_ICUnknown        ImageContent = 0
	ImageContent_ICUserProfile    ImageContent = 1
	ImageContent_ICUserBackground ImageContent = 2
)

var ImageContent_name = map[int32]string{
	0: "ICUnknown",
	1: "ICUserProfile",
	2: "ICUserBackground",
}
var ImageContent_value = map[string]int32{
	"ICUnknown":        0,
	"ICUserProfile":    1,
	"ICUserBackground": 2,
}

func (x ImageContent) Enum() *ImageContent {
	p := new(ImageContent)
	*p = x
	return p
}
func (x ImageContent) String() string {
	return proto.EnumName(ImageContent_name, int32(x))
}
func (x *ImageContent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ImageContent_value, data, "ImageContent")
	if err != nil {
		return err
	}
	*x = ImageContent(value)
	return nil
}
func (ImageContent) EnumDescriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

type SocialIdentity struct {
	SocialService    *string    `protobuf:"bytes,1,req,name=socialService" json:"socialService,omitempty"`
	SocialID         *string    `protobuf:"bytes,2,opt,name=socialID" json:"socialID,omitempty"`
	UserName         *string    `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	DisplayName      *string    `protobuf:"bytes,4,opt,name=displayName" json:"displayName,omitempty"`
	UserURI          *string    `protobuf:"bytes,5,opt,name=userURI" json:"userURI,omitempty"`
	AuthToken        *string    `protobuf:"bytes,6,opt,name=authToken" json:"authToken,omitempty"`
	AuthExpire       *Timestamp `protobuf:"bytes,7,opt,name=authExpire" json:"authExpire,omitempty"`
	AuthSecret       *string    `protobuf:"bytes,8,opt,name=authSecret" json:"authSecret,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *SocialIdentity) Reset()                    { *m = SocialIdentity{} }
func (m *SocialIdentity) String() string            { return proto.CompactTextString(m) }
func (*SocialIdentity) ProtoMessage()               {}
func (*SocialIdentity) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *SocialIdentity) GetSocialService() string {
	if m != nil && m.SocialService != nil {
		return *m.SocialService
	}
	return ""
}

func (m *SocialIdentity) GetSocialID() string {
	if m != nil && m.SocialID != nil {
		return *m.SocialID
	}
	return ""
}

func (m *SocialIdentity) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *SocialIdentity) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *SocialIdentity) GetUserURI() string {
	if m != nil && m.UserURI != nil {
		return *m.UserURI
	}
	return ""
}

func (m *SocialIdentity) GetAuthToken() string {
	if m != nil && m.AuthToken != nil {
		return *m.AuthToken
	}
	return ""
}

func (m *SocialIdentity) GetAuthExpire() *Timestamp {
	if m != nil {
		return m.AuthExpire
	}
	return nil
}

func (m *SocialIdentity) GetAuthSecret() string {
	if m != nil && m.AuthSecret != nil {
		return *m.AuthSecret
	}
	return ""
}

type ContactInfo struct {
	ContactType      *ContactType `protobuf:"varint,1,req,name=contactType,enum=BlitzMessage.ContactType" json:"contactType,omitempty"`
	Contact          *string      `protobuf:"bytes,2,req,name=contact" json:"contact,omitempty"`
	IsVerified       *bool        `protobuf:"varint,3,opt,name=isVerified" json:"isVerified,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ContactInfo) Reset()                    { *m = ContactInfo{} }
func (m *ContactInfo) String() string            { return proto.CompactTextString(m) }
func (*ContactInfo) ProtoMessage()               {}
func (*ContactInfo) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *ContactInfo) GetContactType() ContactType {
	if m != nil && m.ContactType != nil {
		return *m.ContactType
	}
	return ContactType_CTUnknown
}

func (m *ContactInfo) GetContact() string {
	if m != nil && m.Contact != nil {
		return *m.Contact
	}
	return ""
}

func (m *ContactInfo) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

type Employment struct {
	JobTitle         *string   `protobuf:"bytes,1,opt,name=jobTitle" json:"jobTitle,omitempty"`
	CompanyName      *string   `protobuf:"bytes,2,opt,name=companyName" json:"companyName,omitempty"`
	Location         *string   `protobuf:"bytes,3,opt,name=location" json:"location,omitempty"`
	Industry         *string   `protobuf:"bytes,4,opt,name=industry" json:"industry,omitempty"`
	Timespan         *Timespan `protobuf:"bytes,5,opt,name=timespan" json:"timespan,omitempty"`
	Summary          *string   `protobuf:"bytes,6,opt,name=summary" json:"summary,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Employment) Reset()                    { *m = Employment{} }
func (m *Employment) String() string            { return proto.CompactTextString(m) }
func (*Employment) ProtoMessage()               {}
func (*Employment) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *Employment) GetJobTitle() string {
	if m != nil && m.JobTitle != nil {
		return *m.JobTitle
	}
	return ""
}

func (m *Employment) GetCompanyName() string {
	if m != nil && m.CompanyName != nil {
		return *m.CompanyName
	}
	return ""
}

func (m *Employment) GetLocation() string {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return ""
}

func (m *Employment) GetIndustry() string {
	if m != nil && m.Industry != nil {
		return *m.Industry
	}
	return ""
}

func (m *Employment) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

func (m *Employment) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

type Education struct {
	SchoolName       *string   `protobuf:"bytes,1,opt,name=schoolName" json:"schoolName,omitempty"`
	Degree           *string   `protobuf:"bytes,2,opt,name=degree" json:"degree,omitempty"`
	Emphasis         *string   `protobuf:"bytes,3,opt,name=emphasis" json:"emphasis,omitempty"`
	Timespan         *Timespan `protobuf:"bytes,4,opt,name=timespan" json:"timespan,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Education) Reset()                    { *m = Education{} }
func (m *Education) String() string            { return proto.CompactTextString(m) }
func (*Education) ProtoMessage()               {}
func (*Education) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *Education) GetSchoolName() string {
	if m != nil && m.SchoolName != nil {
		return *m.SchoolName
	}
	return ""
}

func (m *Education) GetDegree() string {
	if m != nil && m.Degree != nil {
		return *m.Degree
	}
	return ""
}

func (m *Education) GetEmphasis() string {
	if m != nil && m.Emphasis != nil {
		return *m.Emphasis
	}
	return ""
}

func (m *Education) GetTimespan() *Timespan {
	if m != nil {
		return m.Timespan
	}
	return nil
}

type ImageData struct {
	ImageContent     *ImageContent `protobuf:"varint,1,opt,name=imageContent,enum=BlitzMessage.ImageContent" json:"imageContent,omitempty"`
	ImageBytes       []byte        `protobuf:"bytes,2,opt,name=imageBytes" json:"imageBytes,omitempty"`
	ContentType      *string       `protobuf:"bytes,3,opt,name=contentType" json:"contentType,omitempty"`
	ImageURL         *string       `protobuf:"bytes,4,opt,name=imageURL" json:"imageURL,omitempty"`
	DateAdded        *Timestamp    `protobuf:"bytes,5,opt,name=dateAdded" json:"dateAdded,omitempty"`
	Crc32            *int64        `protobuf:"varint,6,opt,name=crc32" json:"crc32,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ImageData) Reset()                    { *m = ImageData{} }
func (m *ImageData) String() string            { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()               {}
func (*ImageData) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *ImageData) GetImageContent() ImageContent {
	if m != nil && m.ImageContent != nil {
		return *m.ImageContent
	}
	return ImageContent_ICUnknown
}

func (m *ImageData) GetImageBytes() []byte {
	if m != nil {
		return m.ImageBytes
	}
	return nil
}

func (m *ImageData) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *ImageData) GetImageURL() string {
	if m != nil && m.ImageURL != nil {
		return *m.ImageURL
	}
	return ""
}

func (m *ImageData) GetDateAdded() *Timestamp {
	if m != nil {
		return m.DateAdded
	}
	return nil
}

func (m *ImageData) GetCrc32() int64 {
	if m != nil && m.Crc32 != nil {
		return *m.Crc32
	}
	return 0
}

type UserProfile struct {
	UserID             *string           `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	UserStatus         *UserStatus       `protobuf:"varint,2,opt,name=userStatus,enum=BlitzMessage.UserStatus" json:"userStatus,omitempty"`
	CreationDate       *Timestamp        `protobuf:"bytes,3,opt,name=creationDate" json:"creationDate,omitempty"`
	LastSeen           *Timestamp        `protobuf:"bytes,4,opt,name=lastSeen" json:"lastSeen,omitempty"`
	Name               *string           `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Gender             *Gender           `protobuf:"varint,6,opt,name=gender,enum=BlitzMessage.Gender" json:"gender,omitempty"`
	Birthday           *Timestamp        `protobuf:"bytes,7,opt,name=birthday" json:"birthday,omitempty"`
	Images             []*ImageData      `protobuf:"bytes,8,rep,name=images" json:"images,omitempty"`
	SocialIdentities   []*SocialIdentity `protobuf:"bytes,9,rep,name=socialIdentities" json:"socialIdentities,omitempty"`
	ContactInfo        []*ContactInfo    `protobuf:"bytes,10,rep,name=contactInfo" json:"contactInfo,omitempty"`
	HeadlineEmployment *Employment       `protobuf:"bytes,11,opt,name=headlineEmployment" json:"headlineEmployment,omitempty"`
	Employment         []*Employment     `protobuf:"bytes,12,rep,name=employment" json:"employment,omitempty"`
	Education          []*Education      `protobuf:"bytes,13,rep,name=education" json:"education,omitempty"`
	ExpertiseTags      []*EntityTag      `protobuf:"bytes,14,rep,name=expertiseTags" json:"expertiseTags,omitempty"`
	InterestTags       []string          `protobuf:"bytes,15,rep,name=interestTags" json:"interestTags,omitempty"`
	BackgroundSummary  *string           `protobuf:"bytes,16,opt,name=backgroundSummary" json:"backgroundSummary,omitempty"`
	XXX_unrecognized   []byte            `json:"-"`
}

func (m *UserProfile) Reset()                    { *m = UserProfile{} }
func (m *UserProfile) String() string            { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()               {}
func (*UserProfile) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

func (m *UserProfile) GetUserID() string {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return ""
}

func (m *UserProfile) GetUserStatus() UserStatus {
	if m != nil && m.UserStatus != nil {
		return *m.UserStatus
	}
	return UserStatus_USUnknown
}

func (m *UserProfile) GetCreationDate() *Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *UserProfile) GetLastSeen() *Timestamp {
	if m != nil {
		return m.LastSeen
	}
	return nil
}

func (m *UserProfile) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserProfile) GetGender() Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Gender_GUnknown
}

func (m *UserProfile) GetBirthday() *Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *UserProfile) GetImages() []*ImageData {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *UserProfile) GetSocialIdentities() []*SocialIdentity {
	if m != nil {
		return m.SocialIdentities
	}
	return nil
}

func (m *UserProfile) GetContactInfo() []*ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *UserProfile) GetHeadlineEmployment() *Employment {
	if m != nil {
		return m.HeadlineEmployment
	}
	return nil
}

func (m *UserProfile) GetEmployment() []*Employment {
	if m != nil {
		return m.Employment
	}
	return nil
}

func (m *UserProfile) GetEducation() []*Education {
	if m != nil {
		return m.Education
	}
	return nil
}

func (m *UserProfile) GetExpertiseTags() []*EntityTag {
	if m != nil {
		return m.ExpertiseTags
	}
	return nil
}

func (m *UserProfile) GetInterestTags() []string {
	if m != nil {
		return m.InterestTags
	}
	return nil
}

func (m *UserProfile) GetBackgroundSummary() string {
	if m != nil && m.BackgroundSummary != nil {
		return *m.BackgroundSummary
	}
	return ""
}

type ImageUpload struct {
	ImageData        []*ImageData `protobuf:"bytes,1,rep,name=imageData" json:"imageData,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ImageUpload) Reset()                    { *m = ImageUpload{} }
func (m *ImageUpload) String() string            { return proto.CompactTextString(m) }
func (*ImageUpload) ProtoMessage()               {}
func (*ImageUpload) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *ImageUpload) GetImageData() []*ImageData {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type UserProfileUpdate struct {
	Profiles         []*UserProfile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *UserProfileUpdate) Reset()                    { *m = UserProfileUpdate{} }
func (m *UserProfileUpdate) String() string            { return proto.CompactTextString(m) }
func (*UserProfileUpdate) ProtoMessage()               {}
func (*UserProfileUpdate) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

func (m *UserProfileUpdate) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type UserProfileQuery struct {
	UserIDs          []string `protobuf:"bytes,1,rep,name=userIDs" json:"userIDs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserProfileQuery) Reset()                    { *m = UserProfileQuery{} }
func (m *UserProfileQuery) String() string            { return proto.CompactTextString(m) }
func (*UserProfileQuery) ProtoMessage()               {}
func (*UserProfileQuery) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *UserProfileQuery) GetUserIDs() []string {
	if m != nil {
		return m.UserIDs
	}
	return nil
}

type ConfirmationRequest struct {
	ContactInfo      *ContactInfo `protobuf:"bytes,1,opt,name=contactInfo" json:"contactInfo,omitempty"`
	UserProfile      *UserProfile `protobuf:"bytes,2,opt,name=userProfile" json:"userProfile,omitempty"`
	ConfirmationCode *string      `protobuf:"bytes,3,opt,name=confirmationCode" json:"confirmationCode,omitempty"`
	InviterUserID    *string      `protobuf:"bytes,4,opt,name=inviterUserID" json:"inviterUserID,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConfirmationRequest) Reset()                    { *m = ConfirmationRequest{} }
func (m *ConfirmationRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfirmationRequest) ProtoMessage()               {}
func (*ConfirmationRequest) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{9} }

func (m *ConfirmationRequest) GetContactInfo() *ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *ConfirmationRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *ConfirmationRequest) GetConfirmationCode() string {
	if m != nil && m.ConfirmationCode != nil {
		return *m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmationRequest) GetInviterUserID() string {
	if m != nil && m.InviterUserID != nil {
		return *m.InviterUserID
	}
	return ""
}

type ProfilesFromContactInfo struct {
	Profiles         []*UserProfile `protobuf:"bytes,1,rep,name=profiles" json:"profiles,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *ProfilesFromContactInfo) Reset()                    { *m = ProfilesFromContactInfo{} }
func (m *ProfilesFromContactInfo) String() string            { return proto.CompactTextString(m) }
func (*ProfilesFromContactInfo) ProtoMessage()               {}
func (*ProfilesFromContactInfo) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{10} }

func (m *ProfilesFromContactInfo) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*SocialIdentity)(nil), "BlitzMessage.SocialIdentity")
	proto.RegisterType((*ContactInfo)(nil), "BlitzMessage.ContactInfo")
	proto.RegisterType((*Employment)(nil), "BlitzMessage.Employment")
	proto.RegisterType((*Education)(nil), "BlitzMessage.Education")
	proto.RegisterType((*ImageData)(nil), "BlitzMessage.ImageData")
	proto.RegisterType((*UserProfile)(nil), "BlitzMessage.UserProfile")
	proto.RegisterType((*ImageUpload)(nil), "BlitzMessage.ImageUpload")
	proto.RegisterType((*UserProfileUpdate)(nil), "BlitzMessage.UserProfileUpdate")
	proto.RegisterType((*UserProfileQuery)(nil), "BlitzMessage.UserProfileQuery")
	proto.RegisterType((*ConfirmationRequest)(nil), "BlitzMessage.ConfirmationRequest")
	proto.RegisterType((*ProfilesFromContactInfo)(nil), "BlitzMessage.ProfilesFromContactInfo")
	proto.RegisterEnum("BlitzMessage.ContactType", ContactType_name, ContactType_value)
	proto.RegisterEnum("BlitzMessage.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterEnum("BlitzMessage.Gender", Gender_name, Gender_value)
	proto.RegisterEnum("BlitzMessage.ImageContent", ImageContent_name, ImageContent_value)
}

var fileDescriptor10 = []byte{
	// 1056 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x72, 0xdb, 0x54,
	0x10, 0xae, 0xe2, 0xd8, 0xb5, 0x57, 0xb6, 0xa3, 0xa8, 0x81, 0x2a, 0x81, 0x8b, 0x8e, 0x61, 0x86,
	0x12, 0xa8, 0x61, 0x0c, 0xc3, 0x0c, 0x5c, 0x74, 0xa8, 0x9d, 0x9f, 0xf1, 0x0c, 0x81, 0x12, 0x59,
	0x5c, 0x70, 0x77, 0x2c, 0x6d, 0xec, 0x93, 0xe8, 0x8f, 0xa3, 0xe3, 0x50, 0xf3, 0x00, 0x0c, 0xd7,
	0x3c, 0x04, 0x2f, 0xc0, 0x33, 0xf0, 0x02, 0x7d, 0x22, 0xf6, 0x1c, 0xc9, 0x96, 0x9c, 0xa6, 0x66,
	0xb8, 0xd3, 0x59, 0xed, 0xef, 0xb7, 0xfb, 0xed, 0x82, 0xed, 0x65, 0x28, 0x5e, 0x8a, 0xe4, 0x8a,
	0x87, 0x98, 0xf5, 0x53, 0x91, 0xc8, 0xc4, 0x6e, 0x0f, 0x43, 0x2e, 0x7f, 0xbb, 0xc0, 0x2c, 0x63,
	0x33, 0x3c, 0x7a, 0x2f, 0x99, 0x5e, 0xa3, 0x2f, 0xf9, 0x2d, 0xfa, 0xcf, 0x02, 0xcc, 0x7c, 0xc1,
	0x53, 0x99, 0x88, 0x5c, 0xf5, 0xc8, 0x9c, 0x2c, 0xd3, 0x95, 0xdd, 0x91, 0x75, 0x1a, 0x4b, 0x2e,
	0x97, 0x13, 0x36, 0x2b, 0x24, 0xbd, 0x7f, 0x0c, 0xe8, 0xba, 0x89, 0xcf, 0x59, 0x38, 0x0e, 0x50,
	0xff, 0xb4, 0xdf, 0x81, 0x4e, 0xa6, 0x25, 0x2e, 0x8a, 0x5b, 0xee, 0xa3, 0x63, 0x3c, 0xd9, 0x79,
	0xda, 0xb2, 0x2d, 0x68, 0xe6, 0xe2, 0xf1, 0x89, 0xb3, 0xf3, 0xc4, 0xc8, 0x25, 0x0b, 0xca, 0xed,
	0x7b, 0x16, 0xa1, 0x53, 0xd3, 0x92, 0x47, 0x60, 0x06, 0x3c, 0x4b, 0x43, 0xb6, 0xd4, 0xc2, 0x5d,
	0x2d, 0xdc, 0x83, 0x87, 0x4a, 0xcd, 0xbb, 0x1c, 0x3b, 0x75, 0x2d, 0xd8, 0x87, 0x16, 0x5b, 0xc8,
	0xf9, 0x24, 0xb9, 0xc1, 0xd8, 0x69, 0x68, 0xd1, 0x27, 0x00, 0x4a, 0x74, 0xfa, 0x2a, 0xe5, 0x02,
	0x9d, 0x87, 0x24, 0x33, 0x07, 0x8f, 0xfb, 0xd5, 0x2a, 0xfb, 0x13, 0x1e, 0x61, 0x26, 0x59, 0x94,
	0xda, 0x76, 0xae, 0xec, 0xa2, 0x2f, 0x50, 0x3a, 0x4d, 0xe5, 0xa0, 0x37, 0x05, 0x73, 0x94, 0xc4,
	0x92, 0xf9, 0x72, 0x1c, 0x5f, 0x25, 0x76, 0x1f, 0x4c, 0x3f, 0x7f, 0xaa, 0xf2, 0x75, 0x05, 0xdd,
	0xc1, 0xe1, 0xa6, 0xc3, 0x51, 0xa9, 0xa0, 0x72, 0x2c, 0xf4, 0xa9, 0x36, 0x55, 0x2d, 0xc5, 0xe0,
	0xd9, 0x4f, 0x28, 0xf8, 0x15, 0xc7, 0x40, 0x57, 0xd7, 0xec, 0xfd, 0x69, 0x00, 0x9c, 0x46, 0x69,
	0x98, 0x2c, 0x23, 0x82, 0x4a, 0x95, 0x7f, 0x9d, 0x4c, 0x27, 0x5c, 0x86, 0x2a, 0x40, 0x51, 0xbe,
	0x9f, 0x44, 0x29, 0x8b, 0xf3, 0xf2, 0xd7, 0x28, 0x85, 0x89, 0xcf, 0x24, 0x4f, 0xe2, 0x02, 0x25,
	0x92, 0xf0, 0x38, 0x58, 0x64, 0x52, 0x2c, 0x0b, 0x88, 0x9e, 0x42, 0x53, 0xaa, 0xf2, 0xc8, 0x54,
	0x63, 0x64, 0x0e, 0xde, 0xbd, 0xa7, 0x78, 0xfa, 0xab, 0x12, 0xcd, 0x16, 0x51, 0xc4, 0xc8, 0x54,
	0x23, 0xd7, 0xbb, 0x81, 0xd6, 0x69, 0xb0, 0xc8, 0xfd, 0xab, 0xac, 0x33, 0x7f, 0x9e, 0x24, 0xa1,
	0x8e, 0x9f, 0x27, 0xd5, 0x85, 0x46, 0x80, 0x33, 0x81, 0x95, 0x7c, 0x30, 0x4a, 0xe7, 0x2c, 0xe3,
	0x59, 0x91, 0x4f, 0x35, 0xfa, 0xee, 0xb6, 0xe8, 0xbd, 0xbf, 0x0d, 0x68, 0x8d, 0x23, 0x12, 0x9d,
	0x30, 0xc9, 0xec, 0xcf, 0xa1, 0xcd, 0xd5, 0x43, 0x01, 0x49, 0x80, 0xe8, 0x78, 0xdd, 0xc1, 0xd1,
	0xa6, 0xed, 0xb8, 0xa2, 0xa1, 0x51, 0x55, 0xef, 0xe1, 0x52, 0x62, 0xa6, 0xf3, 0x69, 0xe7, 0xa0,
	0xe9, 0xdf, 0xba, 0x55, 0x25, 0x44, 0x4a, 0xd1, 0xbb, 0xfc, 0xae, 0x80, 0xe8, 0x18, 0x5a, 0x01,
	0x93, 0xf8, 0x22, 0x08, 0xa8, 0x1f, 0xf5, 0xed, 0x03, 0xd2, 0x81, 0xba, 0x2f, 0xfc, 0x2f, 0x06,
	0x1a, 0xa2, 0x5a, 0xef, 0xf7, 0x3a, 0x98, 0x15, 0x12, 0x29, 0x44, 0xd4, 0x40, 0xd2, 0x1c, 0xe7,
	0x08, 0x7d, 0x0a, 0xa0, 0xde, 0xae, 0x64, 0x72, 0x91, 0x67, 0xd5, 0x1d, 0x38, 0x9b, 0xbe, 0xbd,
	0xf5, 0x7f, 0xfb, 0x19, 0xb4, 0x69, 0xee, 0x34, 0xde, 0x84, 0x42, 0x9e, 0xf0, 0x96, 0x5c, 0x3e,
	0xa6, 0xf6, 0xb3, 0x4c, 0xba, 0x88, 0x2b, 0x70, 0xdf, 0xaa, 0xda, 0x86, 0xdd, 0x58, 0xf5, 0x2d,
	0x67, 0xc9, 0x87, 0xd0, 0x98, 0x61, 0x1c, 0xa0, 0xd0, 0x55, 0x74, 0x07, 0x07, 0x9b, 0x66, 0xe7,
	0xfa, 0x9f, 0x72, 0x3f, 0xe5, 0x42, 0xce, 0x03, 0xb6, 0xfc, 0x2f, 0xda, 0x7c, 0x04, 0x0d, 0x8d,
	0x69, 0x46, 0x94, 0xa9, 0xbd, 0xa9, 0x58, 0xf6, 0xf5, 0x2b, 0xb0, 0xb2, 0xea, 0x4a, 0xe0, 0x64,
	0xd2, 0xd2, 0x26, 0xef, 0x6f, 0x9a, 0xdc, 0x59, 0x1c, 0x25, 0xe9, 0x14, 0x07, 0x1d, 0xd0, 0x26,
	0xf7, 0x93, 0x4e, 0x93, 0xf4, 0x4b, 0xb0, 0xe7, 0xc8, 0x82, 0x90, 0xc7, 0x58, 0xd2, 0xca, 0x31,
	0x75, 0x15, 0x77, 0xf0, 0xaf, 0xd0, 0x8e, 0xba, 0x85, 0xa5, 0x76, 0x5b, 0x07, 0x79, 0xbb, 0x36,
	0x8d, 0x0d, 0xae, 0xe8, 0xe1, 0x74, 0xee, 0xab, 0xbb, 0x64, 0x4f, 0x1f, 0x3a, 0xf8, 0x2a, 0x45,
	0x21, 0x79, 0x86, 0x6a, 0x45, 0x3a, 0xdd, 0x7b, 0xf5, 0x57, 0x2b, 0xd4, 0x3e, 0xa0, 0xf9, 0xa7,
	0xc1, 0x15, 0x84, 0xaf, 0x56, 0xdf, 0x23, 0xf5, 0x96, 0x7d, 0x08, 0xfb, 0x53, 0xe6, 0xdf, 0xcc,
	0x44, 0xb2, 0x88, 0x03, 0xb7, 0xe0, 0xaa, 0xa5, 0xb9, 0xfa, 0x35, 0x98, 0x1a, 0x65, 0x8f, 0xd2,
	0x63, 0x81, 0xca, 0x8d, 0xaf, 0x40, 0xa7, 0x51, 0xdc, 0xd6, 0x93, 0xde, 0xb7, 0xb0, 0x5f, 0x19,
	0x61, 0x2f, 0x55, 0x5c, 0xa0, 0xad, 0xd9, 0x4c, 0x8b, 0xc3, 0x50, 0xd8, 0x1f, 0xbe, 0x39, 0xb6,
	0x85, 0x49, 0xef, 0x03, 0xb0, 0x2a, 0xcf, 0x1f, 0x17, 0x28, 0x96, 0xab, 0xd5, 0x3c, 0x3e, 0xc9,
	0xed, 0x5b, 0xbd, 0xbf, 0x0c, 0x78, 0x44, 0x2d, 0xba, 0xe2, 0x22, 0xd2, 0x98, 0x5c, 0xe2, 0x2f,
	0x0b, 0x2a, 0xef, 0x6e, 0x6b, 0x0d, 0xdd, 0xa3, 0x2d, 0xad, 0x25, 0xfd, 0x45, 0x19, 0x4c, 0x73,
	0x6a, 0x5b, 0x72, 0xb6, 0x03, 0x96, 0x5f, 0x09, 0x3b, 0x4a, 0x82, 0xd5, 0x26, 0xa0, 0x6b, 0xc4,
	0xe3, 0x5b, 0x4e, 0x30, 0x7b, 0x39, 0x67, 0xf5, 0x3a, 0xe8, 0x9d, 0xc1, 0xe3, 0xd5, 0x4d, 0x3c,
	0x13, 0x49, 0x54, 0x8d, 0xfd, 0x7f, 0x50, 0x39, 0xfe, 0x79, 0x7d, 0x37, 0xf4, 0x1d, 0xe8, 0x40,
	0x6b, 0x34, 0xf1, 0xe2, 0x9b, 0x38, 0xf9, 0x35, 0xb6, 0x1e, 0xd0, 0xa6, 0x80, 0xd1, 0xe4, 0xe5,
	0x3c, 0x89, 0xd1, 0xbd, 0x70, 0x2d, 0xc3, 0x36, 0xe1, 0xe1, 0x68, 0x72, 0x1a, 0x31, 0x1e, 0x5a,
	0x3b, 0xb4, 0xcb, 0x1a, 0xa3, 0xc9, 0x68, 0xce, 0xa4, 0x55, 0xa3, 0x25, 0xb6, 0x37, 0x9a, 0xb8,
	0xd5, 0xab, 0x69, 0xed, 0x1e, 0x5f, 0x03, 0x54, 0xf6, 0x06, 0xb9, 0xf6, 0xdc, 0xd2, 0xb5, 0x7e,
	0x0e, 0xe9, 0x32, 0xdc, 0x60, 0x40, 0x9e, 0xf5, 0x73, 0xac, 0x0b, 0x0d, 0xc8, 0x77, 0x1b, 0x9a,
	0x9e, 0xfb, 0x42, 0xdf, 0x74, 0xf2, 0x6e, 0x41, 0xdb, 0x73, 0x8b, 0xb6, 0xf0, 0x78, 0x66, 0xed,
	0x52, 0xe3, 0xcc, 0xb5, 0x84, 0x0c, 0xea, 0xc7, 0xdf, 0x40, 0xa3, 0xd8, 0x08, 0x64, 0x7a, 0x5e,
	0x86, 0xa1, 0x8c, 0xcf, 0xcf, 0x30, 0x62, 0x21, 0x52, 0x90, 0x16, 0xd4, 0xcf, 0x2f, 0xd4, 0xa7,
	0x4e, 0xfe, 0xfc, 0x07, 0x39, 0x47, 0x61, 0xd5, 0x8e, 0xcf, 0xa0, 0xbd, 0xb1, 0xa5, 0x29, 0x97,
	0xf1, 0xa8, 0x74, 0xb1, 0x0f, 0x1d, 0x7a, 0x96, 0x98, 0x91, 0xa3, 0x03, 0xb0, 0x72, 0xd1, 0x70,
	0x3d, 0xe9, 0xd6, 0xce, 0xf0, 0xb3, 0xd7, 0xcf, 0x77, 0xe0, 0xc1, 0xeb, 0xe7, 0x35, 0xdb, 0x18,
	0xd2, 0xa7, 0x63, 0xc0, 0x11, 0x9d, 0xc3, 0xfe, 0x54, 0x61, 0x4f, 0x91, 0x70, 0xa3, 0x0b, 0x7f,
	0x18, 0xc6, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x18, 0x8c, 0x09, 0xdb, 0x08, 0x00, 0x00,
}
